// tests/source-fields.test.ts — proof for src/pipeline/build-source-fields.ts and the file it
// generates, data/schema/source-fields.json (the capability matrix the gap ledger reasons from).
//
//   npx tsx tests/source-fields.test.ts                                            pure half
//   NETZSPEC_DB=test DATABASE_URL_TEST=postgres://…/netzspec_test5 npx tsx tests/source-fields.test.ts   + the database half
//
// Pure half (no database):
//   * the committed file lists ONLY keys the dictionary defines, every list is non-empty, and every
//     enabled lookup source (queue.ts LOOKUP_TASK) has at least one key or a recorded reason for
//     none (its inventory was read and mapped no spec field, with the labels listed);
//   * the derivation from a real label inventory yields dictionary keys and nothing else; the
//     golden files yield the switch and server keys they hold;
//   * SABOTAGE on the checker: an unknown key, an empty list, an enabled lookup source with no key
//     and no explanation — each named in the problems; the explained case is NOT a problem.
// Database half (skipped with a MISS-free notice when NETZSPEC_DB is not `test`, so `npm test`
// stays pure; run it with the flag to prove it):
//   * build() against the test database — no html_table facts — falls back to the golden files for
//     the Cisco sources and reproduces the committed inventory-derived lists exactly (deterministic);
//   * the test registry has cdw ENABLED with no inventory, so the built file's own problems name
//     cdw — the "forgot to inventory a source" refusal, fired for real;
//   * loadSourceFields loads the committed file (rows inserted, no unknown key);
//   * SABOTAGE: a file with an unknown key under provantage is rejected by loadSourceFields naming
//     `provantage/*/not_a_field`, and no row for it exists afterwards.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  dictionaryKeys, keysFromInventory, keysFromGolden, sourceFieldsProblems, problemsOf, filterKeys, GOLDEN_CATEGORY,
  type BuiltSourceFields,
} from "../src/pipeline/build-source-fields.js";
import { LOOKUP_TASK } from "../src/pipeline/queue.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FILE = path.join(ROOT, "data", "schema", "source-fields.json");
const DB_MODE = process.env.NETZSPEC_DB === "test";

let pass = 0;
let sabotages = 0;
let skipped = 0;
const misses: string[] = [];
function check(name: string, cond: boolean, detail?: unknown): void {
  if (cond) { pass++; console.log(`PASS  ${name}`); }
  else { misses.push(name); console.log(`MISS  ${name}${detail === undefined ? "" : " -> " + JSON.stringify(detail)}`); }
}

const dict = dictionaryKeys();
const committed = JSON.parse(fs.readFileSync(FILE, "utf8")) as BuiltSourceFields;

// =================================================================================================
// the committed file
// =================================================================================================
{
  check(`dictionary in code has keys (${dict.size})`, dict.size > 100);
  check("committed file: generated by the builder (has generated_at, evidence, sources)", typeof committed.generated_at === "string" && !!committed.evidence && !!committed.sources && /GENERATED/.test(committed._about));
  const problems = problemsOf(committed, dict);
  check("committed file: only dictionary keys, no empty list, every enabled lookup source has a key or a recorded reason", problems.length === 0, problems);
  const enabledLookup = Object.keys(LOOKUP_TASK).filter((s) => committed.evidence.sources[s]?.enabled);
  check(`committed file: the enabled lookup sources are known (${enabledLookup.join(", ")})`, enabledLookup.length >= 1, committed.evidence.lookup_sources);
  for (const s of enabledLookup) {
    const n = Object.values(committed.sources[s] ?? {}).reduce((a, ks) => a + ks.length, 0);
    const explained = committed.evidence.lookup_sources_without_spec_fields.includes(s);
    const ev = committed.evidence.sources[s];
    check(`committed file: ${s} has ${n} key(s)${explained ? " — none, and the inventory explains why" : ""}`,
      n > 0 || (explained && ev.method === "label-inventory" && (ev.labels ?? 0) > 0 && ev.mapped === 0 && (ev.unmapped_labels?.length ?? 0) > 0), ev);
  }
  check("committed file: the Cisco datasheet sources are present with per-category lists (never '*')",
    !!committed.sources["cisco-datasheets"] && !("*" in committed.sources["cisco-datasheets"]) && Object.keys(committed.sources["cisco-datasheets"]).length >= 1
      && !!committed.sources["cisco-datasheet-pdf"] && !("*" in committed.sources["cisco-datasheet-pdf"]), Object.keys(committed.sources));
  check("committed file: inventory-derived sources sit under '*' and say which inventory they came from",
    ["provantage", "router-switch", "meraki"].every((s) => committed.sources[s]?.["*"]?.length > 0 && committed.evidence.sources[s]?.method === "label-inventory" && /runs\/vocab\/.*labels\.json/.test(committed.evidence.sources[s].inventory ?? "")));
  check("committed file: every list is sorted and de-duplicated", Object.values(committed.sources).every((byCat) => Object.values(byCat).every((ks) => ks.join() === [...new Set(ks)].sort().join())));
  check("committed file: keys not in the dictionary were dropped AND listed (the list is what makes a stale alias visible)", Array.isArray(committed.evidence.keys_not_in_dictionary));
}

// =================================================================================================
// the derivation, pure
// =================================================================================================
{
  const inv = JSON.parse(fs.readFileSync(path.join(ROOT, "runs", "vocab", "provantage", "labels.json"), "utf8"));
  const r = keysFromInventory(inv);
  check(`keysFromInventory(provantage): ${r.keys.length} keys from ${inv.labels.length} labels (${r.mapped} mapped, ${r.unmapped} unmapped, ${r.sentinels} sentinels), all in the dictionary`,
    r.keys.length > 0 && r.keys.every((k) => dict.has(k)) && r.mapped + r.unmapped + r.sentinels === inv.labels.length && r.unmapped_labels.length === r.unmapped, r);
  check("keysFromInventory: 'PoE budget' style labels map through the SAME alias rules apply-acquired uses",
    keysFromInventory({ source: "x", labels: [{ label: "PoE budget" }, { label: "Switching capacity" }, { label: "Some Label Nobody Maps" }, { label: "Description" }] }).keys.join(",") === "poe_budget,switching_capacity");
  const empty = keysFromInventory({ source: "x", labels: [{ label: "Description" }, { label: "Orderability" }] });
  check("keysFromInventory: an inventory of non-spec labels yields no key and lists the unmapped labels", empty.keys.length === 0 && empty.unmapped_labels.join() === "Orderability" && empty.sentinels === 1, empty);
  const g = keysFromGolden();
  check("keysFromGolden: switching_capacity under switches, cpu_cores under servers-unified-computing, both files read",
    g.byCategory.switches?.includes("switching_capacity") && g.byCategory["servers-unified-computing"]?.includes("cpu_cores") && g.files.length === Object.keys(GOLDEN_CATEGORY).length, g);
  const dropped: string[] = [];
  const f = filterKeys({ "*": ["poe_budget", "not_a_field", "poe_budget"], switches: ["no_such_key"] }, dict, "src", dropped);
  sabotages++;
  check("SABOTAGE filterKeys: an unknown key is dropped and listed as source/category/key; a category left empty disappears; duplicates fold",
    f["*"]?.join() === "poe_budget" && !("switches" in f) && dropped.join() === "src/*/not_a_field,src/switches/no_such_key", { f, dropped });
}
{
  const good = { sources: { provantage: { "*": ["poe_budget"] } } };
  check("sourceFieldsProblems: a sound file has none", sourceFieldsProblems(good, { dictionary: dict, enabledLookupSources: ["provantage"] }).length === 0);
  sabotages++;
  const p1 = sourceFieldsProblems({ sources: { provantage: { "*": ["poe_budget", "not_a_field"] } } }, { dictionary: dict, enabledLookupSources: ["provantage"] });
  check("SABOTAGE checker: an unknown key is named", p1.length === 1 && /provantage\/\*\/not_a_field: not in the dictionary/.test(p1[0]), p1);
  sabotages++;
  const p2 = sourceFieldsProblems({ sources: { provantage: { switches: [] } } }, { dictionary: dict, enabledLookupSources: ["provantage"] });
  check("SABOTAGE checker: an empty list is named, and the source then counts as having no key", p2.length === 2 && /provantage\/switches: empty key list/.test(p2[0]) && /provantage: enabled lookup source with no field key/.test(p2[1]), p2);
  sabotages++;
  const p3 = sourceFieldsProblems(good, { dictionary: dict, enabledLookupSources: ["provantage", "cdw"] });
  check("SABOTAGE checker: an enabled lookup source with no key and no explanation is named", p3.length === 1 && /^cdw: enabled lookup source with no field key/.test(p3[0]), p3);
  const p4 = sourceFieldsProblems(good, { dictionary: dict, enabledLookupSources: ["provantage", "itprice"], explainedEmpty: ["itprice"] });
  check("checker: an enabled lookup source whose inventory explains its empty list is NOT a problem", p4.length === 0, p4);
}

// =================================================================================================
// the database half
// =================================================================================================
if (!DB_MODE) {
  skipped = 4;
  console.log("SKIP  4 database checks (build against the test database, the cdw refusal, loadSourceFields, the unknown-key sabotage): run with NETZSPEC_DB=test and DATABASE_URL_TEST to prove them");
} else {
  const { query, closePool, resolveDatabaseUrl, databaseName } = await import("../src/store/db.js");
  const dbName = databaseName(resolveDatabaseUrl());
  if (!/_test\d*$/.test(dbName)) { console.error(`refusing: database "${dbName}" is not a _test database`); process.exit(1); }
  console.log(`source-fields.test: database ${dbName}`);
  const { syncDictionary } = await import("../src/store/dictionary.js");
  const { loadSourceFields } = await import("../src/pipeline/queue.js");
  const { build } = await import("../src/pipeline/build-source-fields.js");

  await syncDictionary({ quiet: true });
  await query("TRUNCATE source_fields");
  const cdwEnabled = (await query<{ enabled: boolean }>("SELECT enabled FROM sources WHERE slug = 'cdw'")).rows[0]?.enabled;
  const htmlFacts = (await query<{ n: number }>("SELECT count(*)::int AS n FROM facts WHERE method = 'html_table' AND superseded_by IS NULL")).rows[0].n;

  const built = await build();
  const vocabSlugs = Object.entries(committed.evidence.sources).filter(([, ev]) => ev.method === "label-inventory").map(([s]) => s);
  check(`build (test db): the inventory-derived lists reproduce the committed file exactly for ${vocabSlugs.join(", ")} (deterministic)`,
    vocabSlugs.length >= 3 && vocabSlugs.every((s) => JSON.stringify(built.sources[s] ?? null) === JSON.stringify(committed.sources[s] ?? null)),
    vocabSlugs.map((s) => [s, built.sources[s], committed.sources[s]]));
  check(`build (test db): with ${htmlFacts} html_table facts the Cisco sources fall back to the golden files (${htmlFacts === 0 ? "golden" : "facts"})`,
    built.evidence.sources["cisco-datasheets"].method === (htmlFacts === 0 ? "golden" : "facts") && built.evidence.sources["cisco-datasheet-pdf"].method === "golden"
      && built.sources["cisco-datasheet-pdf"]["servers-unified-computing"]?.includes("cpu_cores"), built.evidence.sources["cisco-datasheets"]);
  sabotages++;
  const built_problems = problemsOf(built, dict);
  check(`SABOTAGE build (test db): the registry has cdw ${cdwEnabled ? "ENABLED" : "disabled"} with no inventory -> ${cdwEnabled ? "named as a problem" : "no problem"}`,
    cdwEnabled ? built_problems.some((p) => /^cdw: enabled lookup source with no field key/.test(p)) : built_problems.length === 0, built_problems);

  const loaded = await loadSourceFields(FILE);
  const rows = (await query<{ n: number }>("SELECT count(*)::int AS n FROM source_fields")).rows[0].n;
  check("loadSourceFields(committed file): every key inserted, none unknown", loaded.unknownFields.length === 0 && loaded.inserted > 0 && rows === loaded.inserted, loaded);

  sabotages++;
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "nz-sf-"));
  const sab = path.join(tmp, "sabotage.json");
  fs.writeFileSync(sab, JSON.stringify({ sources: { provantage: { "*": ["poe_budget", "not_a_field"] } } }));
  const s = await loadSourceFields(sab);
  const bad = (await query<{ n: number }>("SELECT count(*)::int AS n FROM source_fields WHERE field_key = 'not_a_field'")).rows[0].n;
  check("SABOTAGE loadSourceFields: an entry with an unknown key is rejected naming provantage/*/not_a_field, and no row for it exists", s.unknownFields.join() === "provantage/*/not_a_field" && bad === 0, s);
  fs.rmSync(tmp, { recursive: true, force: true });
  await query("TRUNCATE source_fields");
  await closePool();
}

console.log(`\n${pass} passed, ${misses.length} missed (${sabotages} sabotage cases${skipped ? `, ${skipped} database checks skipped` : ""})`);
if (misses.length) { for (const m of misses) console.log(`  MISS ${m}`); process.exit(1); }
