// tests/source-fields.test.ts — proof for src/pipeline/build-source-fields.ts and the file it
// generates, data/schema/source-fields.json (the capability matrix the gap ledger reasons from).
//
//   npx tsx tests/source-fields.test.ts                                            pure half
//   NETZSPEC_DB=test DATABASE_URL_TEST=postgres://…/netzspec_test5 npx tsx tests/source-fields.test.ts   + the database half
//
// Pure half (no database):
//   * the committed file lists ONLY keys the dictionary defines, every list is non-empty, and every
//     enabled lookup source (queue.ts LOOKUP_TASK) has at least one key or a recorded reason for
//     none (its inventory was read and mapped no spec field, with the labels listed);
//   * the derivation from a real label inventory yields dictionary keys and nothing else; the
//     golden files yield the switch and server keys they hold;
//   * SABOTAGE on the checker: an unknown key, an empty list, an enabled lookup source with no key
//     and no explanation — each named in the problems; the explained case is NOT a problem.
// Database half (skipped with a MISS-free notice when NETZSPEC_DB is not `test`, so `npm test`
// stays pure; run it with the flag to prove it):
//   * build() against the test database — no html_table facts — falls back to the golden files for
//     the Cisco sources and reproduces the committed inventory-derived lists exactly (deterministic);
//   * the test registry has cdw ENABLED with no inventory, so the built file's own problems name
//     cdw — the "forgot to inventory a source" refusal, fired for real;
//   * loadSourceFields loads the committed file (rows inserted, no unknown key);
//   * SABOTAGE: a file with an unknown key under provantage is rejected by loadSourceFields naming
//     `provantage/*/not_a_field`, and no row for it exists afterwards.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  dictionaryKeys, keysFromInventory, keysFromGolden, sourceFieldsProblems, problemsOf, filterKeys, GOLDEN_CATEGORY,
  requiredKeysByCategory, requiredProfileKeys, requiredFieldCoverageProblems, capableSources, enabledSources,
  ANY_CATEGORY_SOURCES, type BuiltSourceFields,
} from "../src/pipeline/build-source-fields.js";
import { LOOKUP_TASK } from "../src/pipeline/queue.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FILE = path.join(ROOT, "data", "schema", "source-fields.json");
const DB_MODE = process.env.NETZSPEC_DB === "test";

let pass = 0;
let sabotages = 0;
let skipped = 0;
const misses: string[] = [];
function check(name: string, cond: boolean, detail?: unknown): void {
  if (cond) { pass++; console.log(`PASS  ${name}`); }
  else { misses.push(name); console.log(`MISS  ${name}${detail === undefined ? "" : " -> " + JSON.stringify(detail)}`); }
}

const dict = dictionaryKeys();
const committed = JSON.parse(fs.readFileSync(FILE, "utf8")) as BuiltSourceFields;

// A label inventory is a GENERATED artifact under runs/ (gitignored), so a fresh clone or a brand
// worktree has none. Prefer provantage, the widest one, but take any slug: what this proves is that
// keysFromInventory maps a REAL inventory to dictionary keys, and any real inventory does that.
function inventoryPath(): string | null {
  const base = path.join(ROOT, "runs", "vocab");
  let slugs: string[];
  try { slugs = fs.readdirSync(base); } catch { return null; }
  for (const slug of ["provantage", ...slugs.filter((s) => s !== "provantage")]) {
    const p = path.join(base, slug, "labels.json");
    if (fs.existsSync(p)) return p;
  }
  return null;
}

// =================================================================================================
// the committed file
// =================================================================================================
{
  check(`dictionary in code has keys (${dict.size})`, dict.size > 100);
  check("committed file: generated by the builder (has generated_at, evidence, sources)", typeof committed.generated_at === "string" && !!committed.evidence && !!committed.sources && /GENERATED/.test(committed._about));
  const problems = problemsOf(committed, dict);
  check("committed file: only dictionary keys, no empty list, every enabled lookup source has a key or a recorded reason", problems.length === 0, problems);
  const enabledLookup = Object.keys(LOOKUP_TASK).filter((s) => committed.evidence.sources[s]?.enabled);
  // EVERY LOOKUP SOURCE BEING DISABLED IS A REAL STATE, not a broken file. On 8 Sep 2026
  // provantage, router-switch, itprice and cdw were all `enabled = false` in `sources` — itprice
  // since its Cloudflare block — so `enabledLookup` is legitimately empty and the per-source loop
  // below has nothing to iterate. The original assertion demanded at least one and went red for a
  // condition the DATA had changed, not the file.
  //
  // It still must not read as a pass: an empty list means the checks underneath proved nothing,
  // and that has to be visible rather than silent. So the state is named, and the assertion only
  // fires when the file disagrees with itself — sources marked enabled that carry no evidence row.
  const knownLookup = Object.keys(LOOKUP_TASK).filter((s) => committed.evidence.sources[s]);
  if (enabledLookup.length === 0) {
    console.log(`  note  no lookup source is currently ENABLED (${knownLookup.join(", ")} are known but off) `
      + `— the per-source key checks below are skipped and prove nothing`);
  }
  check(`committed file: every lookup source has an evidence row (${knownLookup.length} known, ${enabledLookup.length} enabled)`,
    knownLookup.length >= 1, committed.evidence.lookup_sources);
  for (const s of enabledLookup) {
    const n = Object.values(committed.sources[s] ?? {}).reduce((a, ks) => a + ks.length, 0);
    const explained = committed.evidence.lookup_sources_without_spec_fields.includes(s);
    const ev = committed.evidence.sources[s];
    check(`committed file: ${s} has ${n} key(s)${explained ? " — none, and the inventory explains why" : ""}`,
      n > 0 || (explained && ev.method === "label-inventory" && (ev.labels ?? 0) > 0 && ev.mapped === 0 && (ev.unmapped_labels?.length ?? 0) > 0), ev);
  }
  check("committed file: the Cisco datasheet sources carry BOTH per-category lists (the evidence) and a '*' list (the capability it implies)",
    ANY_CATEGORY_SOURCES.every((s) => !!committed.sources[s]?.["*"]?.length && Object.keys(committed.sources[s]).some((c) => c !== "*")),
    Object.fromEntries(ANY_CATEGORY_SOURCES.map((s) => [s, Object.keys(committed.sources[s] ?? {})])));
  for (const s of ANY_CATEGORY_SOURCES) {
    const byCat = committed.sources[s] ?? {};
    const perCat = new Set(Object.entries(byCat).filter(([c]) => c !== "*").flatMap(([, ks]) => ks));
    const star = new Set(byCat["*"] ?? []);
    check(`committed file: ${s} '*' (${star.size}) is a superset of every per-category list (${perCat.size} keys) and of every profile-required key`,
      [...perCat].every((k) => star.has(k)) && requiredProfileKeys().every((k) => star.has(k) || !dict.has(k)),
      { missing_from_star: [...perCat].filter((k) => !star.has(k)), required_missing: requiredProfileKeys().filter((k) => !star.has(k)) });
    check(`committed file: ${s} evidence explains the '*' list (seen + required)`,
      committed.evidence.sources[s]?.any_category?.keys === star.size, committed.evidence.sources[s]?.any_category);
  }
  // A CARRIED-FORWARD SOURCE IS STILL INVENTORY-DERIVED, and its provenance is still recorded —
  // just in `carried_forward.why` rather than in `inventory`, because this build had no inventory
  // to read. Requiring `method === "label-inventory"` made the check fail on exactly the sources
  // the carry-forward exists to protect: a build on a machine without the lookup fixtures would
  // either delete provantage and router-switch, or keep them and go red for keeping them.
  // The invariant that matters is unchanged: the keys sit under '*' and the file SAYS where they
  // came from — an inventory path, or the reason there was none this time.
  check("committed file: inventory-derived sources sit under '*' and say where their keys came from",
    ["provantage", "router-switch", "meraki"].every((s) => {
      const ev = committed.evidence.sources[s];
      if (!(committed.sources[s]?.["*"]?.length > 0)) return false;
      const fromInventory = ev?.method === "label-inventory"
        && /runs\/vocab\/.*labels\.json/.test(ev.inventory ?? "");
      const carried = !!ev?.carried_forward?.why && (ev.carried_forward.keys ?? 0) > 0;
      return fromInventory || carried;
    }),
    Object.fromEntries(["provantage", "router-switch", "meraki"].map((s) => [s, {
      method: committed.evidence.sources[s]?.method,
      carried: committed.evidence.sources[s]?.carried_forward?.why ?? null,
    }])));
  check("committed file: every list is sorted and de-duplicated", Object.values(committed.sources).every((byCat) => Object.values(byCat).every((ks) => ks.join() === [...new Set(ks)].sort().join())));
  check("committed file: keys not in the dictionary were dropped AND listed (the list is what makes a stale alias visible)", Array.isArray(committed.evidence.keys_not_in_dictionary));
}

// =================================================================================================
// THE invariant this file exists for: nothing a profile REQUIRES may be uncoverable.
// docs/CISCO_GAPS.md finding 5 — 100,167 gap_ledger entries had sources_capable = 0, and a gap with
// no capable source can never reach gap_confirmed and never becomes a queue task.
// =================================================================================================
{
  const byCat = requiredKeysByCategory();
  const cats = Object.keys(byCat).sort();
  const total = Object.values(byCat).reduce((n, ks) => n + ks.length, 0);
  // The set is DERIVED (a profile with any req/cond field), so it grows on its own as required
  // fields are promoted into the generated profiles — 8 hand-written categories on 3 Sep, 13 on
  // 4 Sep. The floor is a floor, not the count: what matters is that the list is non-trivial and
  // that every field in it is covered below.
  check(`the hardware profiles state ${total} required-or-conditional fields across ${cats.length} categories (${cats.join(", ")})`, cats.length >= 8 && total >= 50, { cats, total });
  const enabled = enabledSources(committed.evidence);
  const uncovered = requiredFieldCoverageProblems(committed, enabled);
  check(`committed file: EVERY required field of every hardware category has at least one ENABLED capable source (${total} fields, ${enabled.length} enabled sources)`, uncovered.length === 0, uncovered.slice(0, 20));
  // `mgmt_ports` was in this list until 10 Sep 2026, when it was demoted in every category — zero
  // facts across every vendor and state, no per-category source, no label anywhere to alias. It is
  // no longer required, so "it now has a source" is not a claim worth asserting about it, and
  // keeping it here made this check red for the opposite of a regression. The rest of finding 5
  // stands and is still asserted.
  //
  // `layer` LEFT THIS LIST ON 12 Sep 2026, by exactly the mgmt_ports precedent above. It was
  // demoted to `opt` in switches (round-6 B2) because it had NO fill path: 1,054 operator seeds and
  // nothing else, the only required cup in the catalogue whose observed_fill_path was false. Once
  // it was optional, build-source-fields stopped adding it on a profile's say-so, and this check
  // went red — for the removal of a circular claim, which is the opposite of a regression. Its
  // real fill path is src/core/layerFromSku.ts, measured at precision 1.000 over the seeds.
  check("committed file: the fields finding 5 named as uncoverable now have a source",
    (["uplink_ports", "heat_dissipation", "power_typical", "psu_config"] as const).every((f) => capableSources(committed, "switches", f, enabled).length > 0)
    && capableSources(committed, "routers", "router_throughput", enabled).length > 0,
    Object.fromEntries((["uplink_ports", "heat_dissipation", "power_typical", "psu_config"] as const).map((f) => [f, capableSources(committed, "switches", f, enabled)])));

  sabotages++;
  // THE SABOTAGE KEY IS DERIVED, NOT NAMED. It was hardcoded to `mgmt_ports` until 10 Sep 2026,
  // when that field was demoted everywhere (zero facts across every vendor and state, zero sources
  // publishing it, zero labels to alias). No category required it any more, so `mustNameFor` was
  // EMPTY and this sabotage asserted nothing at all — a check that had quietly stopped checking,
  // which is the failure mode this whole file exists to catch. Picking the key from the profiles
  // means a future demotion moves the sabotage instead of hollowing it.
  const shared = Object.entries(requiredKeysByCategory())
    .flatMap(([cat, keys]) => (keys as string[]).map((k) => [cat, k] as const));
  const inBothStars = new Set((committed.sources["cisco-datasheets"]?.["*"] ?? [])
    .filter((k) => (committed.sources["cisco-datasheet-pdf"]?.["*"] ?? []).includes(k)));
  // `vendor` and `series` come from the parts ROW, so the coverage checker never reports them and
  // a sabotage on one names nothing. Excluded here rather than discovered again next time.
  const IDENTITY = new Set(["vendor", "series"]);
  const victim = shared.map(([, k]) => k).find((k) => inBothStars.has(k) && !IDENTITY.has(k));
  check("a sabotage key exists at all — a required field carried by both '*' lists", !!victim,
    "no required field is in both star lists, so this sabotage cannot fire");
  const drop = (src: string) => ({ ...committed.sources[src], "*": (committed.sources[src]?.["*"] ?? []).filter((k) => k !== victim) });
  const holed = { ...committed, sources: { ...committed.sources, "cisco-datasheets": drop("cisco-datasheets"), "cisco-datasheet-pdf": drop("cisco-datasheet-pdf") } };
  const p5 = requiredFieldCoverageProblems(holed, enabled);
  // WHAT THE SABOTAGE ACTUALLY CLAIMS: holing the file CREATES coverage problems, and every new
  // one names the key that was removed. Predicting the exact category set is fragile — a category
  // with its own per-category seen-list stays covered when the '*' entry goes, so an expected-set
  // assertion goes red for a reason that has nothing to do with the check working. Comparing
  // BEFORE against AFTER states the claim directly and cannot be stale.
  const before = requiredFieldCoverageProblems(committed, enabled);
  const created = p5.filter((m) => !before.includes(m));
  check(`SABOTAGE coverage: dropping "${victim}" from the '*' lists creates problems, all naming it (${created.length})`,
    created.length > 0 && created.every((m) => m.includes(`/${victim}:`)),
    { victim, before: before.length, after: p5.length, created: created.slice(0, 5) });
  sabotages++;
  const withoutVendor = enabled.filter((s) => !(ANY_CATEGORY_SOURCES as readonly string[]).includes(s));
  const p6 = requiredFieldCoverageProblems(committed, withoutVendor);
  check("SABOTAGE coverage: disabling both vendor-datasheet sources leaves required fields uncoverable (the check is not a tautology)", p6.length > 20, p6.length);
  sabotages++;
  // THE CONTROL FIELD IS DERIVED, for the same reason the victim above is. This injected
  // `mgmt_ports` as a required field that IS covered, proving the checker names the fake one and
  // not the real one. On 10 Sep 2026 mgmt_ports was demoted everywhere (zero facts across every
  // vendor and state, no source, no label to alias), so it left the '*' lists and the control
  // started being named too — the sabotage went red for a reason that had nothing to do with the
  // check. Picking a covered field from the committed file cannot go stale that way.
  const covered = (committed.sources["cisco-datasheets"]?.["*"] ?? []).find((k) => k !== "vendor" && k !== "series");
  check("a covered control field exists", !!covered, "the '*' list is empty, so this sabotage has no control");
  const extraReq = { switches: { [covered as string]: { kind: "req" }, nz_not_a_real_field: { kind: "req" } } };
  const p7 = requiredFieldCoverageProblems(committed, enabled, extraReq);
  check(`SABOTAGE coverage: a NEW required field is named and the covered control ("${covered}") is not`,
    p7.join() === "switches/nz_not_a_real_field: required by the profile and no enabled source publishes it", { covered, got: p7 });
  check("coverage: a conditional field counts as required (it is `req` for any part that trips it and lands in completeness.missing)",
    (requiredKeysByCategory().switches ?? []).includes("rack_units") && (requiredKeysByCategory().transceiver ?? []).includes("fiber_type"));
}

// =================================================================================================
// the derivation, pure
// =================================================================================================
{
  // This block used to open the inventory with a bare readFileSync on a hardcoded `provantage`.
  // In a tree without the artifact that THREW, which did not cost one check — it aborted the
  // module, so the twelve checks below (the synthetic inventories, keysFromGolden, filterKeys and
  // every sourceFieldsProblems sabotage) never ran and the whole file reported as one ENOENT.
  // A missing generated artifact must cost exactly the proof it carries: say so and carry on.
  const invPath = inventoryPath();
  if (invPath === null) {
    misses.push("no label inventory under runs/vocab/*/labels.json — keysFromInventory was NOT "
      + "proved against a real inventory (the synthetic cases below still ran). Rebuild with: "
      + "python3.11 scraper/tools/label_inventory.py <slug> --acquired");
    console.log("MISS  keysFromInventory(real inventory): no runs/vocab/*/labels.json in this tree");
  } else {
  const slug = path.basename(path.dirname(invPath));
  const inv = JSON.parse(fs.readFileSync(invPath, "utf8"));
  const r = keysFromInventory(inv);
  check(`keysFromInventory(${slug}): ${r.keys.length} keys from ${inv.labels.length} labels (${r.mapped} mapped, ${r.unmapped} unmapped, ${r.sentinels} sentinels), all in the dictionary`,
    r.keys.length > 0 && r.keys.every((k) => dict.has(k)) && r.mapped + r.unmapped + r.sentinels === inv.labels.length && r.unmapped_labels.length === r.unmapped, r);
  }
  check("keysFromInventory: 'PoE budget' style labels map through the SAME alias rules apply-acquired uses",
    keysFromInventory({ source: "x", labels: [{ label: "PoE budget" }, { label: "Switching capacity" }, { label: "Some Label Nobody Maps" }, { label: "Description" }] }).keys.join(",") === "poe_budget,switching_capacity");
  const empty = keysFromInventory({ source: "x", labels: [{ label: "Description" }, { label: "Orderability" }] });
  check("keysFromInventory: an inventory of non-spec labels yields no key and lists the unmapped labels", empty.keys.length === 0 && empty.unmapped_labels.join() === "Orderability" && empty.sentinels === 1, empty);
  const g = keysFromGolden();
  check("keysFromGolden: switching_capacity under switches, cpu_cores under servers-unified-computing, both files read",
    g.byCategory.switches?.includes("switching_capacity") && g.byCategory["servers-unified-computing"]?.includes("cpu_cores") && g.files.length === Object.keys(GOLDEN_CATEGORY).length, g);
  const dropped: string[] = [];
  const f = filterKeys({ "*": ["poe_budget", "not_a_field", "poe_budget"], switches: ["no_such_key"] }, dict, "src", dropped);
  sabotages++;
  check("SABOTAGE filterKeys: an unknown key is dropped and listed as source/category/key; a category left empty disappears; duplicates fold",
    f["*"]?.join() === "poe_budget" && !("switches" in f) && dropped.join() === "src/*/not_a_field,src/switches/no_such_key", { f, dropped });
}
{
  const good = { sources: { provantage: { "*": ["poe_budget"] } } };
  check("sourceFieldsProblems: a sound file has none", sourceFieldsProblems(good, { dictionary: dict, enabledLookupSources: ["provantage"] }).length === 0);
  sabotages++;
  const p1 = sourceFieldsProblems({ sources: { provantage: { "*": ["poe_budget", "not_a_field"] } } }, { dictionary: dict, enabledLookupSources: ["provantage"] });
  check("SABOTAGE checker: an unknown key is named", p1.length === 1 && /provantage\/\*\/not_a_field: not in the dictionary/.test(p1[0]), p1);
  sabotages++;
  const p2 = sourceFieldsProblems({ sources: { provantage: { switches: [] } } }, { dictionary: dict, enabledLookupSources: ["provantage"] });
  check("SABOTAGE checker: an empty list is named, and the source then counts as having no key", p2.length === 2 && /provantage\/switches: empty key list/.test(p2[0]) && /provantage: enabled lookup source with no field key/.test(p2[1]), p2);
  sabotages++;
  const p3 = sourceFieldsProblems(good, { dictionary: dict, enabledLookupSources: ["provantage", "cdw"] });
  check("SABOTAGE checker: an enabled lookup source with no key and no explanation is named", p3.length === 1 && /^cdw: enabled lookup source with no field key/.test(p3[0]), p3);
  const p4 = sourceFieldsProblems(good, { dictionary: dict, enabledLookupSources: ["provantage", "itprice"], explainedEmpty: ["itprice"] });
  check("checker: an enabled lookup source whose inventory explains its empty list is NOT a problem", p4.length === 0, p4);
}

// =================================================================================================
// the database half
// =================================================================================================
if (!DB_MODE) {
  skipped = 6;
  console.log("SKIP  6 database checks (build against the test database, the cdw refusal, loadSourceFields, the '*' rows landing as category_id IS NULL, the required-field coverage through the gap_ledger JOIN, the unknown-key sabotage): run with NETZSPEC_DB=test and DATABASE_URL_TEST to prove them");
} else {
  const { query, closePool, resolveDatabaseUrl, databaseName } = await import("../src/store/db.js");
  const dbName = databaseName(resolveDatabaseUrl());
  if (!/_test\d*$/.test(dbName)) { console.error(`refusing: database "${dbName}" is not a _test database`); process.exit(1); }
  console.log(`source-fields.test: database ${dbName}`);
  const { syncDictionary } = await import("../src/store/dictionary.js");
  const { loadSourceFields } = await import("../src/pipeline/queue.js");
  const { build } = await import("../src/pipeline/build-source-fields.js");

  await syncDictionary({ quiet: true });
  await query("TRUNCATE source_fields");
  const cdwEnabled = (await query<{ enabled: boolean }>("SELECT enabled FROM sources WHERE slug = 'cdw'")).rows[0]?.enabled;
  const htmlFacts = (await query<{ n: number }>("SELECT count(*)::int AS n FROM facts WHERE method = 'html_table' AND superseded_by IS NULL")).rows[0].n;

  // `previous` is what the CLI passes (the file being replaced), so a source whose inventory
  // rebuilt empty keeps its keys instead of vanishing — without it meraki drops here and the
  // determinism check below would be comparing against a file built with different inputs.
  const built = await build({ previous: committed });
  const vocabSlugs = Object.entries(committed.evidence.sources).filter(([, ev]) => ev.method === "label-inventory").map(([s]) => s);
  check(`build (test db): the inventory-derived lists reproduce the committed file exactly for ${vocabSlugs.join(", ")} (deterministic)`,
    vocabSlugs.length >= 3 && vocabSlugs.every((s) => JSON.stringify(built.sources[s] ?? null) === JSON.stringify(committed.sources[s] ?? null)),
    vocabSlugs.map((s) => [s, built.sources[s], committed.sources[s]]));
  check(`build (test db): with ${htmlFacts} html_table facts the Cisco sources fall back to the golden files (${htmlFacts === 0 ? "golden" : "facts"})`,
    built.evidence.sources["cisco-datasheets"].method === (htmlFacts === 0 ? "golden" : "facts") && built.evidence.sources["cisco-datasheet-pdf"].method === "golden"
      && built.sources["cisco-datasheet-pdf"]["servers-unified-computing"]?.includes("cpu_cores"), built.evidence.sources["cisco-datasheets"]);
  sabotages++;
  const built_problems = problemsOf(built, dict);
  check(`SABOTAGE build (test db): the registry has cdw ${cdwEnabled ? "ENABLED" : "disabled"} with no inventory -> ${cdwEnabled ? "named as a problem" : "no problem"}`,
    cdwEnabled ? built_problems.some((p) => /^cdw: enabled lookup source with no field key/.test(p)) : built_problems.length === 0, built_problems);

  const loaded = await loadSourceFields(FILE);
  const rows = (await query<{ n: number }>("SELECT count(*)::int AS n FROM source_fields")).rows[0].n;
  check("loadSourceFields(committed file): every key inserted, none unknown", loaded.unknownFields.length === 0 && loaded.inserted > 0 && rows === loaded.inserted, loaded);
  const anyRows = (await query<{ slug: string; n: number }>(
    "SELECT s.slug, count(*)::int AS n FROM source_fields sf JOIN sources s ON s.id = sf.source_id WHERE sf.category_id IS NULL GROUP BY 1 ORDER BY 1")).rows;
  check("loadSourceFields: the '*' lists landed as category_id IS NULL rows for both vendor-datasheet sources",
    ANY_CATEGORY_SOURCES.every((s) => (anyRows.find((r) => r.slug === s)?.n ?? 0) > 0), anyRows);

  // The invariant proved through the JOIN the gap_ledger view itself uses, not through the file:
  // a required field with no capable source is a gap that can never close.
  {
    const wanted = Object.entries(requiredKeysByCategory()).flatMap(([cat, keys]) => keys.map((k) => ({ cat, k })));
    const uncovered = (await query<{ category: string; field_key: string }>(
      `WITH want(category, field_key) AS (SELECT * FROM unnest($1::text[], $2::text[]))
       SELECT w.category, w.field_key FROM want w
         JOIN categories c ON c.slug = w.category
        WHERE NOT EXISTS (
          SELECT 1 FROM source_fields sf JOIN sources s ON s.id = sf.source_id
           WHERE s.enabled AND sf.field_key = w.field_key AND (sf.category_id IS NULL OR sf.category_id = c.id))
        ORDER BY 1, 2`,
      [wanted.map((w) => w.cat), wanted.map((w) => w.k)])).rows;
    check(`loadSourceFields: through the gap_ledger JOIN, every one of the ${wanted.length} required (category, field) pairs has an enabled capable source`,
      uncovered.length === 0, uncovered.slice(0, 20));
  }

  sabotages++;
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "nz-sf-"));
  const sab = path.join(tmp, "sabotage.json");
  fs.writeFileSync(sab, JSON.stringify({ sources: { provantage: { "*": ["poe_budget", "not_a_field"] } } }));
  const s = await loadSourceFields(sab);
  const bad = (await query<{ n: number }>("SELECT count(*)::int AS n FROM source_fields WHERE field_key = 'not_a_field'")).rows[0].n;
  check("SABOTAGE loadSourceFields: an entry with an unknown key is rejected naming provantage/*/not_a_field, and no row for it exists", s.unknownFields.join() === "provantage/*/not_a_field" && bad === 0, s);
  fs.rmSync(tmp, { recursive: true, force: true });
  await query("TRUNCATE source_fields");
  await closePool();
}

console.log(`\n${pass} passed, ${misses.length} missed (${sabotages} sabotage cases${skipped ? `, ${skipped} database checks skipped` : ""})`);
if (misses.length) { for (const m of misses) console.log(`  MISS ${m}`); process.exit(1); }
