// Keyword hints for "printed but not mapped": labels the current mapper sends to null / __backlog / __not_a_spec that
// look like the cup's row. A HINT ONLY — an upper bound that also catches feature bullets. Never used for a verdict.
export const HINTS: Record<string, RegExp> = {
  ports: /(^|[^a-z])ports?([^a-z]|$)|interfaces?$/i,
  uplink_ports: /uplink/i,
  switching_capacity: /switching capacity|switching bandwidth|backplane/i,
  forwarding_rate: /forwarding rate|throughput.*pps|mpps/i,
  mac_table: /mac (address|table|entries)|mac addresses/i,
  vlan_max: /(number of|maximum|max|active|total) (active )?vlans?|vlan ids/i,
  jumbo_mtu: /jumbo|mtu/i,
  packet_buffer: /buffer/i,
  mgmt_class: /managed|unmanaged|smart switch/i,
  psu_config: /power suppl|psu/i,
  psu_redundant: /redundan/i,
  cooling: /fan|cooling|fanless|airflow/i,
  poe_standard: /poe|power over ethernet|802\.3 ?(af|at|bt)|upoe/i,
  poe_budget: /poe (power|budget)|available poe|power budget/i,
  poe_ports: /poe ports|ports.*poe|poe.*ports/i,
  stackable: /stack/i,
  stacking_bandwidth: /stack.*bandwidth|stackwise/i,
  module_slots: /slots?([^a-z]|$)/i,
  power_max: /power consumption|max(imum)? power|power draw|power \(w|watts/i,
  power_typical: /typical power|power consumption/i,
  form_factor: /form factor|desktop|rack[- ]?mount|din rail/i,
  rack_units: /rack units?|(^|[^a-z])ru([^a-z]|$)/i,
  dimensions: /dimension|h x w x d|(^|[^a-z])(height|width|depth)/i,
  weight: /weight/i,
  temp_operating: /operating temp|temperature/i,
  humidity_operating: /humidity/i,
  certifications: /certif|compliance|safety|emc|emission/i,
  altitude_max: /altitude/i,
  temp_storage: /storage temp|nonoperating|non-operating/i,
  mtbf: /mtbf|mean time/i,
  heat_dissipation: /heat|btu/i,
  input_voltage: /input voltage|voltage|ac input|dc input/i,
  ieee_standards: /ieee|802\./i,
  dram: /dram|memory|(^|[^a-z])ram([^a-z]|$)/i,
  flash: /flash|storage/i,
  latency: /latency/i,
  fabric_bandwidth: /fabric|backplane/i,
  ip_rating: /(^|[^a-z])ip ?[0-9]{2}|ingress|ip rating/i,
  mounting: /mount/i,
  wifi_generation: /wi-?fi ?[4567]|802\.11 ?(ax|ac|be|n)/i,
  radio_bands: /band|frequenc|ghz/i,
  radio_count: /radios?([^a-z]|$)/i,
  spatial_streams: /spatial|mimo|streams/i,
  antenna_type: /antenna/i,
  antenna_connector: /antenna connector|rp-tnc|n-type|connector/i,
  router_throughput: /throughput|forwarding/i,
  wan_interfaces: /wan/i,
  lan_interfaces: /lan|switch ports|ethernet ports/i,
  cellular_bands: /lte|band|cellular|5g/i,
  display: /display|screen|lcd/i,
  voice_lines: /lines?([^a-z]|$)|line keys/i,
  audio_codecs: /codec|g\.7|opus/i,
  supported_protocols: /protocol|sip|sccp/i,
  data_rate: /data rate|speed|gbps|bit rate/i,
  connector: /connector/i,
  reach_max: /reach|distance/i,
  wavelength: /wavelength|nm([^a-z]|$)/i,
  tx_power: /transmit|launch power|tx power|output power/i,
  rx_sensitivity: /sensitivity|receive power|rx power/i,
  cpu_cores: /cores?([^a-z]|$)/i,
  clock_speed: /frequency|clock|ghz/i,
  cpu_cache: /cache/i,
  tdp: /tdp|power/i,
  memory_speed_max: /memory speed|ddr|mhz|mt\/s/i,
  storage_capacity: /capacity|size \(gb|tb/i,
  drive_interface: /interface|sas|sata|nvme/i,
  cpu_sockets_max: /socket|processor/i,
  memory_max: /memory/i,
  dimm_slots: /dimm/i,
  drive_bays: /drive|bays?/i,
  pcie_slots: /pci/i,
  firewall_throughput: /firewall|throughput/i,
  threat_throughput: /threat|ngfw|ips/i,
  ipsec_throughput: /ipsec|vpn/i,
  concurrent_sessions: /concurrent|sessions|connections/i,
  new_conn_per_sec: /per second|cps/i,
  product_compatibility: /compatib|supported (platform|switch|router|chassis)|for use with/i,
  rf_input_level: /rf input|input level/i,
};
