// The reviewer's spec v2 Part I.4 archetypes + Part II deltas, transcribed as data (kind-layer III.0, agent/kindlayer-A).
// Cup syntax: "key" required · "key:opt" optional · "key:g=gate" pending on gate · "a|b" either key evidences the cup
//             ":new" marks a key the spec calls NEW. Later entries override earlier ones with the same cup name.
export type Cup = { cup: string; keys: string[]; status: "req" | "pending" | "opt"; gate?: string; isNew: boolean; origin: string };

export function parse(spec: string, origin: string): Cup {
  const [head, ...mods] = spec.split(":");
  let status: Cup["status"] = "req"; let gate: string | undefined; let isNew = false;
  for (const m of mods) {
    if (m === "opt") status = "opt";
    else if (m === "new") isNew = true;
    else if (m.startsWith("g=")) { status = "pending"; gate = m.slice(2); }
    else if (m === "req") status = "req";
    else throw new Error(`bad cup modifier ${m} in ${spec}`);
  }
  return { cup: head, keys: head.split("|"), status, gate, isNew, origin };
}
export function compose(...blocks: [string, string[]][]): Cup[] {
  const out = new Map<string, Cup>();
  for (const [origin, specs] of blocks) for (const s of specs) { const c = parse(s, origin); out.set(c.cup, c); }
  return [...out.values()];
}

// ---------------- I.4 archetypes ----------------
export const A: Record<string, string[]> = {
  ENV: ["dimensions", "weight", "power_max", "temp_operating", "humidity_operating", "certifications", "form_factor", "rack_units:g=form_factor"],
  ENVPLUS: ["altitude_max", "temp_storage", "mtbf", "heat_dissipation", "power_typical", "input_voltage"],
  COMPAT: ["product_compatibility"],
  ETH: ["ports", "uplink_ports:g=form_factor", "switching_capacity", "forwarding_rate", "mac_table", "vlan_max", "jumbo_mtu", "packet_buffer",
    "mgmt_class", "psu_config", "psu_redundant:g=psu_config", "cooling", "airflow:opt", "ieee_standards", "poe_standard",
    "poe_budget:g=poe_standard", "poe_ports:g=poe_standard", "stackable", "stacking_bandwidth:g=stackable",
    "module_slots:g=form_factor", "ipv4_routes:opt", "ipv6_routes:opt", "layer:opt", "dram:opt", "flash:opt"],
  PSU: ["psu_rated_output", "input_voltage", "airflow", "product_compatibility", "input_freq:opt", "psu_efficiency:opt", "holdup_time:opt",
    "power_input_connector:opt", "dimensions:opt", "weight:opt"],
  FAN: ["airflow", "product_compatibility", "fan_hot_swap:opt", "acoustic_noise:opt"],
  LINECARD: ["ports", "data_rate", "power_max", "product_compatibility", "connector:opt", "slots_occupied:opt"],
  MODULE: ["ports", "data_rate", "product_compatibility", "power_max:opt", "connector:opt"],
  SUPERVISOR: ["product_compatibility", "switching_capacity", "forwarding_rate", "dram", "flash", "mgmt_ports:opt", "console_ports:opt"],
  FABRIC: ["fabric_bandwidth", "product_compatibility"],
  CHASSIS: ["module_slots", "form_factor", "rack_units", "dimensions", "weight", "psu_config", "psu_count:opt", "fan_tray_bays:opt",
    "fabric_bandwidth:opt", "power_max:opt", "airflow:opt"],
  CABLE: ["cable_length", "connector", "media", "data_rate:opt", "jacket_color:opt", "product_compatibility:opt"],
  STACKCABLE: ["cable_length", "connector", "media", "data_rate:opt", "jacket_color:opt", "product_compatibility:opt", "stacking_technology:opt"],
  POWERCORD: ["cable_length", "plug_type", "power_cord_rating", "product_compatibility:opt"],
  MECHANICAL: ["mounting", "product_compatibility"],
  ACCESSORY: ["product_compatibility"],
  OPTIC: ["form_factor", "data_rate", "connector", "reach_max", "wavelength", "media|fiber_type", "tx_power", "rx_sensitivity", "power_max",
    "temp_operating", "ddm:opt", "msa:opt", "standard:opt", "rx_max_input_power:opt"],
  BIDI_ADD: ["rx_wavelength"],
  TUNABLE_ADD: ["tuning_range", "channel_spacing:opt"],
  BREAKOUT: ["form_factor_a", "form_factor_b", "breakout_count", "cable_length", "data_rate", "media"],
  ADAPTER: ["form_factor_a", "form_factor_b", "product_compatibility"],
  CPU: ["cpu_cores", "clock_speed", "cpu_cache", "tdp", "memory_speed_max", "product_compatibility", "cpu_threads:opt", "cpu_boost_clock:opt"],
  MEMORY: ["dram", "memory_speed_max", "product_compatibility", "dimm_ranks:opt", "dimm_voltage:opt"],
  DRIVE: ["storage_capacity", "drive_interface", "drive_form_factor:new", "product_compatibility", "drive_endurance_dwpd:opt:new",
    "iops_random_read_4k:opt", "sequential_write_throughput:opt", "pack_quantity:opt"],
  NIC: ["ports", "data_rate", "pcie_card_size", "product_compatibility", "power_max:opt"],
  GPU: ["tdp", "pcie_card_size", "gpu_memory:new", "product_compatibility"],
  STORCTL: ["raid_level", "drive_interface", "product_compatibility", "controller_cache:opt:new"],
  SERVER: ["form_factor", "rack_units:g=form_factor", "cpu_sockets_max", "memory_max", "dimm_slots", "drive_bays", "pcie_slots", "memory_speed_max",
    "power_max", "dimensions", "weight", "temp_operating", "humidity_operating", "certifications", "cpu:opt", "onboard_nics:opt",
    "raid_controller:opt", "psu_config:opt", "gpu_max:opt"],
  AP: ["wifi_generation", "radio_bands", "radio_count", "spatial_streams", "antenna_type", "poe_standard", "power_max", "ports", "dimensions",
    "weight", "temp_operating", "certifications", "data_rate_per_radio:opt", "antenna_gain:opt", "ap_max_clients:opt", "max_ssids:opt",
    "regulatory_domain:opt", "ip_rating:g=deploy_role", "humidity_operating:opt"],
  ANTENNA_WIFI: ["antenna_type", "antenna_gain", "antenna_connector", "radio_bands", "polarization:opt", "beamwidth_azimuth:opt", "ip_rating:opt", "product_compatibility"],
  ANTENNA_CELL: ["antenna_type", "antenna_gain", "antenna_connector", "cellular_bands", "polarization:opt", "beamwidth_azimuth:opt", "ip_rating:opt", "product_compatibility"],
  WLC: ["wlc_ap_capacity", "wlc_client_capacity", "ports", "wlc_throughput:opt:new"],
  POWERINJ: ["poe_standard", "psu_rated_output", "input_voltage", "product_compatibility"],
  ROUTER: ["router_throughput", "wan_interfaces", "lan_interfaces", "module_slots:g=form_factor", "dram", "flash", "console_ports:opt",
    "ipsec_throughput:opt", "sdwan_capable:opt", "poe_ports:opt", "cellular_bands:g=deploy_role", "psu_config:opt"],
  SPCORE_ADD: ["forwarding_rate", "switching_capacity", "fabric_bandwidth", "redundancy:opt", "power_max", "temp_operating"],
  APPLIANCE_ADD: ["ports", "dram:opt", "storage_capacity:opt", "psu_config:opt", "management_interfaces:opt"],
  FIREWALL_ADD: ["firewall_throughput", "threat_throughput", "ipsec_throughput", "concurrent_sessions", "new_conn_per_sec", "ips_throughput:opt",
    "vpn_peers:opt", "security_contexts:opt", "high_availability:opt"],
  PHONE: ["display", "voice_lines", "ports", "poe_standard", "audio_codecs", "supported_protocols", "dimensions", "weight", "handset:opt",
    "headset_support:opt", "bluetooth_version:opt", "wifi_generation:g=deploy_role", "power_max:opt"],
  VIDEODEVICE: ["max_resolution", "video_codecs", "audio_codecs", "camera_zoom", "field_of_view", "display:opt", "mounting", "power_max", "dimensions",
    "weight", "supported_protocols:opt"],
  VIDEOCODEC: ["max_resolution", "video_codecs", "audio_codecs", "video_inputs", "video_outputs", "power_max", "dimensions", "weight"],
  CAMERA: ["max_resolution", "camera_zoom", "field_of_view", "image_sensor:opt", "product_compatibility", "mounting"],
  MICROPHONE: ["mic_type", "mic_pickup_range", "product_compatibility"],
  SPEAKER: ["speaker_size:opt", "speaker_frequency_response:opt", "product_compatibility"],
  DISPLAY: ["display_size:new", "max_resolution", "touchscreen", "mounting", "power_max"],
  TOUCHPANEL: ["display_size:new", "touchscreen", "product_compatibility"],
  HEADSET: ["headset_support", "bluetooth_version:opt", "battery_life:opt"],
  DECTBASE: ["handset", "supported_protocols", "product_compatibility"],
  EXPANSION: ["keys_buttons", "product_compatibility"],
  GATEWAY: ["fxs_ports", "fxo_ports", "ports", "supported_protocols", "audio_codecs", "voice_lines:opt"],
  ATA: ["fxs_ports", "ports", "supported_protocols", "audio_codecs"],
  TRANSMITTER: ["tx_power", "wavelength", "rf_input_level:opt", "power_max:opt", "product_compatibility"],
  NODE: ["rf_gain", "rf_output_level", "input_power_range", "power_max", "dimensions", "weight", "temp_operating"],
  RECEIVER: ["input_power_range", "rf_output_level", "product_compatibility"],
  RFAMP: ["gain", "rf_output_level", "power_max"],
  AMPLIFIER: ["gain", "gain_range:opt", "noise_figure", "total_output_power", "input_power_range"],
  PASSIVE: ["insertion_loss_max", "return_loss:opt", "channel_count:opt"],
  PLUGIN: ["product_compatibility", "power_max:opt"],
  TRANSPONDER: ["data_rate", "wavelength|tuning_range", "modulation_format", "fec:opt", "reach_max:opt", "power_max", "product_compatibility"],
  MUX: ["channel_count", "channel_spacing", "insertion_loss_max", "product_compatibility"],
  DCU: ["dispersion_compensation", "insertion_loss_max", "product_compatibility"],
  CELLULAR: ["cellular_bands", "cellular_category", "cellular_max_speed:opt", "product_compatibility"],
  RADIO: ["ieee_standards", "radio_bands", "product_compatibility"],
  MERAKI: ["cloud_management", "license_type:opt"],
};

const ETH_NO_POE_STACK = A.ETH.filter((s) => !/^(poe_standard|poe_budget|poe_ports|stackable|stacking_bandwidth)(:|$)/.test(s));

export type KindDef = { category: string; kind: string; target: string; cups: Cup[]; note?: string;
  roles?: Record<string, { add: Cup[]; demote: string[]; note?: string }> };

const k = (category: string, kind: string, target: string, blocks: [string, string[]][], note?: string): KindDef =>
  ({ category, kind, target, cups: compose(...blocks), note });
const ucs = (cat: string): KindDef[] => [
  k(cat, "cpu", "cpu (CPU)", [["CPU", A.CPU]]),
  k(cat, "server", "server (SERVER)", [["SERVER", A.SERVER]]),
  k(cat, "drive", "drive (DRIVE)", [["DRIVE", A.DRIVE]]),
  k(cat, "memory", "memory (MEMORY)", [["MEMORY", A.MEMORY]]),
  k(cat, "nic", "nic (NIC)", [["NIC", A.NIC]]),
  k(cat, "gpu", "gpu (GPU)", [["GPU", A.GPU]]),
  k(cat, "storage-controller", "storage-controller (STORAGE-CONTROLLER)", [["STORAGE-CONTROLLER", A.STORCTL]]),
  k(cat, "chassis", "chassis (CHASSIS + COMPAT)", [["CHASSIS", A.CHASSIS], ["COMPAT", A.COMPAT]]),
  k(cat, "fabric-interconnect", "fabric-interconnect (ETH minus PoE/stacking + ENV)", [["ETH-SWITCHING-FI", ETH_NO_POE_STACK], ["ENV", A.ENV], ["FI", ["product_compatibility:opt"]]]),
  k(cat, "psu", "power (PSU) — rename psu->power", [["PSU", A.PSU]]),
  k(cat, "io-module", "io-module (MODULE + COMPAT)", [["MODULE", A.MODULE]]),
  k(cat, "pdu", "pdu (PSU minus airflow)", [["PDU", ["psu_rated_output", "input_voltage", "receptacles"]]]),
  k(cat, "tpm", "tpm (COMPAT)", [["COMPAT", A.COMPAT]]),
  k(cat, "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k(cat, "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  k(cat, "unknown", "unknown (asks product_compatibility at most)", [["ACCESSORY", A.ACCESSORY]]),
];

export const KINDS: KindDef[] = [
  // ---- II.1 switches ----
  {
    ...k("switches", "switch", "switch (ETH-SWITCHING + ENV; ports unconditional)", [["ETH-SWITCHING", A.ETH], ["ENV", A.ENV], ["II.1", ["ports"]]]),
    roles: {
      smb: { add: [], demote: ["altitude_max", "temp_storage", "mtbf", "heat_dissipation", "power_typical", "dram", "flash"],
        note: "ieee_standards and packet_buffer stay (core)." },
      access: { add: compose(["ENV+", A.ENVPLUS]), demote: [] },
      "core-agg": { add: compose(["ENV+", A.ENVPLUS], ["core-agg", ["fabric_bandwidth", "psu_redundant"]]), demote: [] },
      datacenter: { add: compose(["ENV+", A.ENVPLUS], ["datacenter", ["latency", "fabric_bandwidth:g=form_factor", "max_ports_100g:opt", "max_ports_25g:opt", "max_ports_10g:opt"]]), demote: [] },
      industrial: { add: compose(["industrial", ["ip_rating", "input_voltage", "mounting", "temp_operating_extended:opt"]]), demote: [] },
    },
  },
  k("switches", "fex", "fex (NOT ETH-SWITCHING)", [["FEX", ["ports", "uplink_ports", "power_max", "psu_config", "airflow", "product_compatibility"]], ["ENV", A.ENV]]),
  k("switches", "supervisor", "supervisor (SUPERVISOR)", [["SUPERVISOR", A.SUPERVISOR]]),
  k("switches", "linecard", "linecard (LINECARD)", [["LINECARD", A.LINECARD]]),
  k("switches", "module", "module (MODULE)", [["MODULE", A.MODULE]]),
  k("switches", "daughter", "module (MODULE) — daughter folds into module", [["MODULE", A.MODULE]]),
  k("switches", "stack-module", "module (MODULE) — stack-module folds into module", [["MODULE", A.MODULE]]),
  k("switches", "fabric", "fabric (FABRIC)", [["FABRIC", A.FABRIC]]),
  k("switches", "power", "power (PSU)", [["PSU", A.PSU]]),
  k("switches", "fan", "fan (FAN)", [["FAN", A.FAN]]),
  k("switches", "stack-cable", "stack-cable (STACK-CABLE)", [["STACK-CABLE", A.STACKCABLE]]),
  k("switches", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("switches", "power-cord", "power-cord (POWER-CORD)", [["POWER-CORD", A.POWERCORD]]),
  k("switches", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("switches", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.2 transceiver ----
  k("transceiver", "pluggable", "pluggable (OPTIC)", [["OPTIC", A.OPTIC]], "DAC/AOC cables still inside this kind today (spec: move to a new `cable` kind) — measured as-is"),
  k("transceiver", "bidi", "bidi (OPTIC + rx_wavelength)", [["OPTIC", A.OPTIC], ["BIDI", A.BIDI_ADD]]),
  k("transceiver", "tunable", "tunable (OPTIC + tuning_range)", [["OPTIC", A.OPTIC], ["TUNABLE", A.TUNABLE_ADD]]),
  k("transceiver", "breakout-cable", "breakout-cable (BREAKOUT)", [["BREAKOUT", A.BREAKOUT]]),
  k("transceiver", "adapter", "adapter (ADAPTER)", [["ADAPTER", A.ADAPTER]]),
  k("transceiver", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("transceiver", "accessory", "accessory -> 0 after the read", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.3 routers ----
  {
    ...k("routers", "enterprise", "router (ROUTER + ENV) — rename enterprise->router", [["ROUTER", A.ROUTER], ["ENV", A.ENV]],
      "Rows the spec moves out (HWIC, WAE, ENCS, CRS, ASR 9000, NCS 5500, 8000) are measured inside the kind-level table and EXCLUDED from every role table."),
    roles: {
      branch: { add: compose(["ENV+", A.ENVPLUS]), demote: [] },
      smb: { add: [], demote: ["module_slots"], note: "RV: no ENV+ added; module_slots demotion candidate." },
      edge: { add: compose(["ENV+", A.ENVPLUS], ["edge", ["module_slots", "fabric_bandwidth:opt", "redundancy:opt"]]), demote: [] },
      "industrial-iot": { add: compose(["industrial-iot", ["cellular_bands", "ip_rating", "input_voltage", "temp_operating"]]), demote: ["flash", "dram"] },
    },
  },
  k("routers", "sp-core", "sp-core (SP-CORE = CHASSIS + deltas)", [["CHASSIS", A.CHASSIS], ["SP-CORE", A.SPCORE_ADD]]),
  k("routers", "chassis", "chassis (CHASSIS)", [["CHASSIS", A.CHASSIS]]),
  k("routers", "linecard", "linecard (LINECARD)", [["LINECARD", A.LINECARD]]),
  k("routers", "forwarding", "linecard (LINECARD) — forwarding folds into linecard", [["LINECARD", A.LINECARD]]),
  k("routers", "processor", "processor (SUPERVISOR)", [["SUPERVISOR", A.SUPERVISOR]]),
  k("routers", "fabric", "fabric (FABRIC)", [["FABRIC", A.FABRIC]]),
  k("routers", "module", "module (MODULE)", [["MODULE", A.MODULE]]),
  k("routers", "antenna", "antenna (ANTENNA, cellular_bands)", [["ANTENNA", A.ANTENNA_CELL]]),
  k("routers", "power", "power (PSU)", [["PSU", A.PSU]]),
  k("routers", "fan", "fan (FAN)", [["FAN", A.FAN]]),
  k("routers", "memory", "memory (MEMORY)", [["MEMORY", A.MEMORY]]),
  k("routers", "flash", "flash (MEMORY + storage_capacity)", [["MEMORY", A.MEMORY], ["flash", ["storage_capacity"]]]),
  k("routers", "drive", "drive (DRIVE)", [["DRIVE", A.DRIVE]]),
  k("routers", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("routers", "power-cord", "power-cord (POWER-CORD)", [["POWER-CORD", A.POWERCORD]]),
  k("routers", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("routers", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  k("routers", "transceiver", "-> category transceiver (OPTIC)", [["OPTIC", A.OPTIC]]),
  // ---- II.4 wireless ----
  {
    ...k("wireless", "ap", "ap (AP)", [["AP", A.AP]]),
    roles: {
      indoor: { add: [], demote: [] },
      outdoor: { add: compose(["outdoor", ["ip_rating", "temp_operating", "wind_rating:opt", "antenna_connector"]]), demote: [] },
      industrial: { add: compose(["industrial", ["ip_rating", "certifications", "input_voltage"]]), demote: [] },
      smb: { add: [], demote: ["regulatory_domain", "ap_max_clients"], note: "both are already optional in the AP archetype; measured anyway" },
      "mesh-extender": { add: compose(["mesh-extender", ["max_mesh_extenders:opt"]]), demote: ["ports"] },
    },
  },
  k("wireless", "antenna", "antenna (ANTENNA, radio_bands)", [["ANTENNA", A.ANTENNA_WIFI]]),
  k("wireless", "wlc", "wlc (WLC + ENV)", [["WLC", A.WLC], ["ENV", A.ENV]]),
  k("wireless", "backhaul", "backhaul (AP + link_budget, max_roaming_speed)", [["AP", A.AP], ["backhaul", ["link_budget", "max_roaming_speed"]]]),
  k("wireless", "power-injector", "power-injector (POWER-INJECTOR)", [["POWER-INJECTOR", A.POWERINJ]]),
  k("wireless", "module", "module (MODULE)", [["MODULE", A.MODULE]]),
  k("wireless", "power", "power (PSU)", [["PSU", A.PSU]]),
  k("wireless", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("wireless", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("wireless", "appliance", "appliance (APPLIANCE)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD]]),
  k("wireless", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  k("wireless", "other", "unknown (rename other->unknown)", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.5 / II.6 / II.7 UCS ----
  ...ucs("servers-unified-computing"), ...ucs("hyperconverged-systems"), ...ucs("hyperconverged-infrastructure"),
  // ---- II.8 security ----
  k("security", "firewall", "firewall (FIREWALL = APPLIANCE + deltas)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD], ["FIREWALL", A.FIREWALL_ADD]]),
  k("security", "ips", "ips (APPLIANCE + ips_throughput)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD], ["IPS", ["ips_throughput"]]]),
  k("security", "management", "management (APPLIANCE + managed_devices_max)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD], ["MANAGEMENT", ["managed_devices_max"]]]),
  k("security", "analytics", "analytics (APPLIANCE + flows_per_second)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD], ["ANALYTICS", ["flows_per_second", "events_per_second:opt"]]]),
  k("security", "web-gateway", "web-gateway (APPLIANCE + recommended_users)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD], ["WEB-GATEWAY", ["recommended_users"]]]),
  k("security", "email-gateway", "email-gateway (APPLIANCE + recommended_users)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD], ["EMAIL-GATEWAY", ["recommended_users"]]]),
  k("security", "identity", "identity (APPLIANCE + max_endpoints)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD], ["IDENTITY", ["max_endpoints"]]]),
  k("security", "compute", "compute (SERVER)", [["SERVER", A.SERVER]]),
  k("security", "appliance", "appliance -> 0 (APPLIANCE measured)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD]]),
  k("security", "module", "module (MODULE)", [["MODULE", A.MODULE]]),
  k("security", "security-module", "module (MODULE) — folds into module", [["MODULE", A.MODULE]]),
  k("security", "ips-module", "module (MODULE) — folds into module", [["MODULE", A.MODULE]]),
  k("security", "drive", "drive (DRIVE)", [["DRIVE", A.DRIVE]]),
  k("security", "memory", "memory (MEMORY)", [["MEMORY", A.MEMORY]]),
  k("security", "nic", "nic (NIC)", [["NIC", A.NIC]]),
  k("security", "power", "power (PSU)", [["PSU", A.PSU]]),
  k("security", "fan", "fan (FAN)", [["FAN", A.FAN]]),
  k("security", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("security", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("security", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.9 video ----
  k("video", "transmitter", "transmitter (TRANSMITTER)", [["TRANSMITTER", A.TRANSMITTER]], "II.9 candidates to promote: rf_input_level, optical_agc_range, power_max"),
  k("video", "node", "node (NODE)", [["NODE", A.NODE]]),
  k("video", "receiver", "receiver (RECEIVER)", [["RECEIVER", A.RECEIVER]]),
  k("video", "rf-amplifier", "rf-amplifier (RF-AMPLIFIER)", [["RF-AMPLIFIER", A.RFAMP]]),
  k("video", "amplifier", "amplifier (AMPLIFIER)", [["AMPLIFIER", A.AMPLIFIER]]),
  k("video", "passive", "passive (PASSIVE)", [["PASSIVE", A.PASSIVE]]),
  k("video", "plug-in", "plug-in (PLUG-IN)", [["PLUG-IN", A.PLUGIN]]),
  k("video", "system", "system (CHASSIS)", [["CHASSIS", A.CHASSIS]]),
  k("video", "chassis", "chassis (CHASSIS)", [["CHASSIS", A.CHASSIS]]),
  k("video", "line-card", "linecard (LINECARD) — rename line-card->linecard", [["LINECARD", A.LINECARD]]),
  k("video", "optic", "optic (OPTIC) or -> transceiver", [["OPTIC", A.OPTIC]]),
  k("video", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("video", "power", "power (PSU)", [["PSU", A.PSU]]),
  k("video", "fan", "fan (FAN)", [["FAN", A.FAN]]),
  k("video", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("video", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  k("video", "unknown", "unknown", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.10 collaboration-endpoints ----
  {
    ...k("collaboration-endpoints", "phone", "phone (PHONE)", [["PHONE", A.PHONE]]),
    roles: {
      desk: { add: [], demote: [] },
      wireless: { add: compose(["wireless", ["wifi_generation", "battery_life:opt"]]), demote: ["poe_standard"],
        note: "II.10: wireless phones are asked wifi_generation/battery_life, desk ones poe_standard — poe_standard read as the implied demotion" },
      dect: { add: [], demote: ["poe_standard"], note: "no delta written in the spec; poe_standard measured as an implied demotion (DECT handsets)" },
      conference: { add: [], demote: [], note: "no delta written in the spec" },
    },
  },
  k("collaboration-endpoints", "video-device", "video-device (VIDEO-DEVICE)", [["VIDEO-DEVICE", A.VIDEODEVICE]]),
  k("collaboration-endpoints", "video-codec", "video-codec (VIDEO-CODEC)", [["VIDEO-CODEC", A.VIDEOCODEC]]),
  k("collaboration-endpoints", "camera", "camera (CAMERA)", [["CAMERA", A.CAMERA]]),
  k("collaboration-endpoints", "microphone", "microphone (MICROPHONE)", [["MICROPHONE", A.MICROPHONE]]),
  k("collaboration-endpoints", "speaker", "speaker (SPEAKER)", [["SPEAKER", A.SPEAKER]]),
  k("collaboration-endpoints", "display", "display (DISPLAY)", [["DISPLAY", A.DISPLAY]]),
  k("collaboration-endpoints", "touch-panel", "touch-panel (TOUCH-PANEL)", [["TOUCH-PANEL", A.TOUCHPANEL]]),
  k("collaboration-endpoints", "headset", "headset (HEADSET)", [["HEADSET", A.HEADSET]]),
  k("collaboration-endpoints", "dect-base", "dect-base (DECT-BASE)", [["DECT-BASE", A.DECTBASE]]),
  k("collaboration-endpoints", "expansion-module", "expansion-module (EXPANSION-MODULE)", [["EXPANSION-MODULE", A.EXPANSION]]),
  k("collaboration-endpoints", "power-supply", "power (PSU) — rename power-supply->power", [["PSU", A.PSU]]),
  k("collaboration-endpoints", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("collaboration-endpoints", "power-cord", "power-cord (POWER-CORD)", [["POWER-CORD", A.POWERCORD]]),
  k("collaboration-endpoints", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("collaboration-endpoints", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  k("collaboration-endpoints", "unknown", "unknown", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.11 interfaces-modules ----
  k("interfaces-modules", "interface", "interface (MODULE + connector)", [["MODULE", A.MODULE], ["II.11", ["connector"]]]),
  k("interfaces-modules", "cellular", "cellular (CELLULAR)", [["CELLULAR", A.CELLULAR]]),
  k("interfaces-modules", "radio", "radio (RADIO)", [["RADIO", A.RADIO]]),
  k("interfaces-modules", "service", "module (MODULE; service modules)", [["MODULE", A.MODULE]]),
  k("interfaces-modules", "module", "module (MODULE)", [["MODULE", A.MODULE]]),
  k("interfaces-modules", "voice", "interface? (MODULE) — not in II.11 target list", [["MODULE", A.MODULE]]),
  k("interfaces-modules", "memory", "memory (MEMORY) — not in II.11 target list", [["MEMORY", A.MEMORY]]),
  k("interfaces-modules", "mux", "mux (MUX) — not in II.11 target list", [["MUX", A.MUX]]),
  k("interfaces-modules", "fabric", "fabric (FABRIC) — not in II.11 target list", [["FABRIC", A.FABRIC]]),
  k("interfaces-modules", "power", "power (PSU)", [["PSU", A.PSU]]),
  k("interfaces-modules", "fan", "fan (FAN) — not in II.11 target list", [["FAN", A.FAN]]),
  k("interfaces-modules", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("interfaces-modules", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("interfaces-modules", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.12 storage-networking ----
  k("storage-networking", "switch", "fc-switch (ETH minus PoE/stacking/mac_table/vlan_max, + data_rate) + ENV",
    [["ETH-SWITCHING-FC", ETH_NO_POE_STACK.filter((s) => !/^(mac_table|vlan_max)(:|$)/.test(s))], ["FC", ["data_rate"]], ["ENV", A.ENV]]),
  k("storage-networking", "director", "director (CHASSIS + fabric_bandwidth)", [["CHASSIS", A.CHASSIS], ["director", ["fabric_bandwidth"]]]),
  k("storage-networking", "linecard", "linecard (LINECARD)", [["LINECARD", A.LINECARD]]),
  k("storage-networking", "supervisor", "supervisor (SUPERVISOR)", [["SUPERVISOR", A.SUPERVISOR]]),
  k("storage-networking", "fabric", "fabric (FABRIC)", [["FABRIC", A.FABRIC]]),
  k("storage-networking", "power", "power (PSU)", [["PSU", A.PSU]]),
  k("storage-networking", "fan", "fan (FAN)", [["FAN", A.FAN]]),
  k("storage-networking", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("storage-networking", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("storage-networking", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  k("storage-networking", "pluggable", "-> category transceiver (OPTIC)", [["OPTIC", A.OPTIC]]),
  // ---- II.13 unified-communications ----
  k("unified-communications", "gateway", "gateway (GATEWAY + ENV)", [["GATEWAY", A.GATEWAY], ["ENV", A.ENV]]),
  k("unified-communications", "ata", "ata (ATA)", [["ATA", A.ATA]]),
  k("unified-communications", "phone", "phone (PHONE) — must equal collab phone", [["PHONE", A.PHONE]]),
  k("unified-communications", "server", "server (SERVER)", [["SERVER", A.SERVER]]),
  k("unified-communications", "power-supply", "power (PSU)", [["PSU", A.PSU]]),
  k("unified-communications", "speaker", "speaker (SPEAKER)", [["SPEAKER", A.SPEAKER]]),
  k("unified-communications", "voice-module", "module (MODULE) [mapping mine]", [["MODULE", A.MODULE]]),
  k("unified-communications", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("unified-communications", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.14 optical-networking ----
  k("optical-networking", "mux", "mux (MUX)", [["MUX", A.MUX]]),
  k("optical-networking", "roadm", "mux (MUX; ROADM)", [["MUX", A.MUX]]),
  k("optical-networking", "linecard", "linecard (LINECARD) + transponder cups (II.14)", [["LINECARD", A.LINECARD], ["TRANSPONDER", A.TRANSPONDER]]),
  k("optical-networking", "amplifier", "amplifier (AMPLIFIER)", [["AMPLIFIER", A.AMPLIFIER]]),
  k("optical-networking", "dcu", "dcu (DCU)", [["DCU", A.DCU]]),
  k("optical-networking", "chassis", "chassis (CHASSIS)", [["CHASSIS", A.CHASSIS]]),
  k("optical-networking", "controller", "controller — no target in II.14; SUPERVISOR measured [mapping mine]", [["SUPERVISOR", A.SUPERVISOR]]),
  k("optical-networking", "fabric", "fabric (FABRIC) — not in II.14 target list", [["FABRIC", A.FABRIC]]),
  k("optical-networking", "cable", "cable (CABLE)", [["CABLE", A.CABLE]]),
  k("optical-networking", "power", "power (PSU)", [["PSU", A.PSU]]),
  k("optical-networking", "fan", "fan (FAN)", [["FAN", A.FAN]]),
  k("optical-networking", "mechanical", "mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
  k("optical-networking", "accessory", "accessory (ACCESSORY)", [["ACCESSORY", A.ACCESSORY]]),
  k("optical-networking", "other", "unknown (rename other->unknown)", [["ACCESSORY", A.ACCESSORY]]),
  k("optical-networking", "pluggable", "-> category transceiver (OPTIC)", [["OPTIC", A.OPTIC]]),
  k("optical-networking", "pluggable-tunable", "-> category transceiver (TUNABLE)", [["OPTIC", A.OPTIC], ["TUNABLE", A.TUNABLE_ADD]]),
  // ---- II.15 meraki ----
  k("meraki", "switch", "switch (ETH-SWITCHING + ENV + MERAKI delta)", [["ETH-SWITCHING", A.ETH], ["ENV", A.ENV], ["II.1", ["ports"]], ["MERAKI", A.MERAKI]]),
  k("meraki", "access-point", "ap (AP + MERAKI delta)", [["AP", A.AP], ["MERAKI", A.MERAKI]]),
  k("meraki", "appliance", "security-appliance (FIREWALL + MERAKI delta)", [["ENV", A.ENV], ["APPLIANCE", A.APPLIANCE_ADD], ["FIREWALL", A.FIREWALL_ADD], ["MERAKI", A.MERAKI]]),
  k("meraki", "camera", "camera (CAMERA + MV deltas + MERAKI delta)", [["CAMERA", A.CAMERA], ["MV", ["storage_capacity", "video_quality_max", "ip_rating:g=deploy_role", "ir_illumination:opt"]], ["MERAKI", A.MERAKI]]),
  k("meraki", "gateway", "gateway (CELLULAR + ROUTER-lite + MERAKI delta)", [["CELLULAR", A.CELLULAR], ["ROUTER-lite", ["ports"]], ["MERAKI", A.MERAKI]]),
  k("meraki", "sensor", "sensor (sensors, battery_life + MERAKI delta)", [["MT", ["sensors", "battery_life"]], ["MERAKI", A.MERAKI]]),
  k("meraki", "unknown", "unknown (asks <= 1 cup)", [["ACCESSORY", A.ACCESSORY]]),
  // ---- II.16/17 ----
  k("conferencing", "server", "-> collaboration-endpoints server (SERVER)", [["SERVER", A.SERVER]]),
  k("data-center-networking", "switch", "-> switches switch, deploy_role=datacenter", [["ETH-SWITCHING", A.ETH], ["ENV", A.ENV], ["II.1", ["ports"]], ["ENV+", A.ENVPLUS],
    ["datacenter", ["latency", "fabric_bandwidth:g=form_factor", "max_ports_100g:opt", "max_ports_25g:opt", "max_ports_10g:opt"]]]),
  k("data-center-networking", "power", "-> switches power (PSU)", [["PSU", A.PSU]]),
  k("data-center-networking", "fan", "-> switches fan (FAN)", [["FAN", A.FAN]]),
  k("data-center-networking", "mechanical", "-> switches mechanical (MECHANICAL)", [["MECHANICAL", A.MECHANICAL]]),
];

// Priority order the report uses (instruction): big and contested first.
export const PRIORITY: [string, string][] = [
  ["switches", "switch"], ["wireless", "ap"], ["routers", "enterprise"], ["collaboration-endpoints", "phone"],
  ["transceiver", "pluggable"], ["servers-unified-computing", "server"], ["servers-unified-computing", "cpu"], ["servers-unified-computing", "drive"],
  ["video", "transmitter"], ["security", "firewall"],
];
