// GENERATED by scripts/universe/write-status.ts — do not edit by hand.
// Field labels for lib/specsRead.ts. Deliberately dependency-free: the content session's reader
// must not import anything from the scraper pipeline, or a mid-edit scraper file would break its
// build again. validate-schema.ts fails if this drifts from lib/fieldSchema.ts.
export const FIELD_LABELS: Record<string, { de: string; en: string; unit?: string }> = {
  "vendor": { de: "Hersteller", en: "Manufacturer" },
  "series": { de: "Produktserie", en: "Product series" },
  "mgmt_class": { de: "Verwaltung", en: "Management class" },
  "layer": { de: "Switching-Ebene", en: "Switching layer" },
  "form_factor": { de: "Bauform", en: "Form factor" },
  "rack_units": { de: "Höheneinheiten", en: "Rack units", unit: "HE" },
  "stackable": { de: "Stapelbar", en: "Stackable" },
  "deploy_role": { de: "Einsatzbereich", en: "Deployment role" },
  "ports": { de: "Port-Bestückung", en: "Port configuration" },
  "uplink_ports": { de: "Uplink-Ports", en: "Uplink ports" },
  "uplink_modular": { de: "Modulare Uplinks", en: "Modular uplinks" },
  "module_slots": { de: "Modulslots", en: "Module slots" },
  "mgmt_ports": { de: "Management-Ports", en: "Management ports" },
  "poe_standard": { de: "PoE-Standard", en: "PoE standard" },
  "poe_ports": { de: "Anzahl PoE-Ports", en: "PoE port count" },
  "poe_budget": { de: "PoE-Budget", en: "PoE budget", unit: "W" },
  "poe_per_port_max": { de: "Max. PoE je Port", en: "Max PoE per port", unit: "W" },
  "switching_capacity": { de: "Switching-Kapazität", en: "Switching capacity", unit: "Gbit/s" },
  "forwarding_rate": { de: "Weiterleitungsrate", en: "Forwarding rate", unit: "Mpps" },
  "stacking_bandwidth": { de: "Stacking-Bandbreite", en: "Stacking bandwidth", unit: "Gbit/s" },
  "stack_max_members": { de: "Max. Switches je Stack", en: "Max stack members" },
  "packet_buffer": { de: "Paketpuffer", en: "Packet buffer", unit: "MB" },
  "mac_table": { de: "MAC-Adresstabelle", en: "MAC address table", unit: "Einträge" },
  "vlan_max": { de: "VLANs (aktiv)", en: "Active VLANs" },
  "ipv4_routes": { de: "IPv4-Routen", en: "IPv4 routes" },
  "ipv6_routes": { de: "IPv6-Routen", en: "IPv6 routes" },
  "multicast_groups": { de: "Multicast-Gruppen", en: "Multicast groups" },
  "acl_entries": { de: "ACL-Einträge", en: "ACL entries" },
  "jumbo_mtu": { de: "Jumbo-Frames (max. MTU)", en: "Jumbo frame max MTU", unit: "Byte" },
  "latency": { de: "Latenz", en: "Latency", unit: "µs" },
  "cpu": { de: "CPU", en: "CPU" },
  "dram": { de: "Arbeitsspeicher", en: "DRAM", unit: "GB" },
  "flash": { de: "Flash-Speicher", en: "Flash memory", unit: "GB" },
  "psu_config": { de: "Netzteil-Konfiguration", en: "PSU configuration" },
  "psu_redundant": { de: "Redundante Stromversorgung", en: "Redundant PSU" },
  "psu_options": { de: "Netzteil-Optionen", en: "PSU options" },
  "cooling": { de: "Kühlung", en: "Cooling" },
  "airflow": { de: "Luftstromrichtung", en: "Airflow direction" },
  "power_typical": { de: "Leistungsaufnahme (typisch)", en: "Typical power draw", unit: "W" },
  "power_max": { de: "Leistungsaufnahme (max.)", en: "Max power draw", unit: "W" },
  "input_voltage": { de: "Eingangsspannung", en: "Input voltage", unit: "V" },
  "input_freq": { de: "Netzfrequenz", en: "Input frequency", unit: "Hz" },
  "heat_dissipation": { de: "Wärmeabgabe", en: "Heat dissipation", unit: "BTU/h" },
  "temp_operating": { de: "Betriebstemperatur", en: "Operating temperature", unit: "°C" },
  "temp_storage": { de: "Lagertemperatur", en: "Storage temperature", unit: "°C" },
  "humidity_operating": { de: "Rel. Luftfeuchtigkeit (Betrieb)", en: "Operating humidity", unit: "%" },
  "altitude_max": { de: "Max. Betriebshöhe", en: "Max operating altitude", unit: "m" },
  "acoustic_noise": { de: "Geräuschpegel", en: "Acoustic noise", unit: "dB(A)" },
  "mtbf": { de: "MTBF", en: "MTBF", unit: "h" },
  "ip_rating": { de: "Schutzart (IP)", en: "IP rating" },
  "dimensions": { de: "Abmessungen (H×B×T)", en: "Dimensions (H×W×D)", unit: "mm" },
  "weight": { de: "Gewicht", en: "Weight", unit: "kg" },
  "certifications": { de: "Zertifizierungen", en: "Certifications" },
  "ieee_standards": { de: "IEEE-Standards", en: "IEEE standards" },
  "standard": { de: "Übertragungsstandard", en: "Transmission standard" },
  "data_rate": { de: "Datenrate", en: "Data rate", unit: "Gbit/s" },
  "media": { de: "Übertragungsmedium", en: "Media" },
  "fiber_type": { de: "Fasertyp", en: "Fiber type" },
  "wavelength": { de: "Wellenlänge", en: "Wavelength", unit: "nm" },
  "reach_max": { de: "Max. Reichweite", en: "Max reach", unit: "m" },
  "connector": { de: "Anschlusstyp", en: "Connector" },
  "tx_power": { de: "Sendeleistung (TX)", en: "TX power", unit: "dBm" },
  "rx_sensitivity": { de: "Empfangsempfindlichkeit (RX)", en: "RX sensitivity", unit: "dBm" },
  "link_budget": { de: "Link-Budget", en: "Link budget", unit: "dB" },
  "laser_type": { de: "Lasertyp", en: "Laser type" },
  "mode": { de: "Übertragungsmodus", en: "Transmission mode" },
  "bidi_wavelengths": { de: "BiDi-Wellenlängen (TX/RX)", en: "BiDi wavelengths", unit: "nm" },
  "ddm": { de: "DDM/DOM", en: "DDM/DOM" },
  "fec": { de: "FEC-Anforderung", en: "FEC requirement" },
  "temp_class": { de: "Temperaturbereich", en: "Temperature class" },
  "cable_length": { de: "Kabellänge", en: "Cable length", unit: "m" },
  "wire_gauge": { de: "Leiterquerschnitt", en: "Wire gauge", unit: "AWG" },
  "msa": { de: "MSA-Konformität", en: "MSA compliance" },
};

// Enum values are STORED as machine slugs ("l3", "rack-19", "802.3at") so they compare and filter
// cleanly. These are the human strings; a page must never print the slug.
export const ENUM_LABELS: Record<string, Record<string, { de: string; en: string }>> = {
  "vendor": {
    "cisco": {
      "de": "Cisco",
      "en": "Cisco"
    },
    "hpe": {
      "de": "HPE",
      "en": "HPE"
    },
    "aruba": {
      "de": "Aruba",
      "en": "Aruba"
    },
    "juniper": {
      "de": "Juniper",
      "en": "Juniper"
    },
    "arista": {
      "de": "Arista",
      "en": "Arista"
    },
    "dell-emc": {
      "de": "Dell EMC",
      "en": "Dell EMC"
    },
    "lenovo": {
      "de": "Lenovo",
      "en": "Lenovo"
    },
    "extreme": {
      "de": "Extreme Networks",
      "en": "Extreme Networks"
    },
    "fortinet": {
      "de": "Fortinet",
      "en": "Fortinet"
    },
    "nvidia": {
      "de": "NVIDIA",
      "en": "NVIDIA"
    },
    "mikrotik": {
      "de": "MikroTik",
      "en": "MikroTik"
    },
    "ubiquiti": {
      "de": "Ubiquiti",
      "en": "Ubiquiti"
    },
    "supermicro": {
      "de": "Supermicro",
      "en": "Supermicro"
    }
  },
  "mgmt_class": {
    "managed": {
      "de": "Managed",
      "en": "Managed"
    },
    "smart-managed": {
      "de": "Smart Managed",
      "en": "Smart managed"
    },
    "unmanaged": {
      "de": "Unmanaged",
      "en": "Unmanaged"
    }
  },
  "layer": {
    "l2": {
      "de": "Layer 2",
      "en": "Layer 2"
    },
    "l2plus": {
      "de": "Layer 2+",
      "en": "Layer 2+"
    },
    "l3": {
      "de": "Layer 3",
      "en": "Layer 3"
    }
  },
  "form_factor": {
    "rack-19": {
      "de": "19-Zoll-Rackmontage",
      "en": "19-inch rack"
    },
    "desktop": {
      "de": "Desktop",
      "en": "Desktop"
    },
    "din-rail": {
      "de": "DIN-Schienenmontage",
      "en": "DIN rail"
    },
    "modular-chassis": {
      "de": "Modulares Chassis",
      "en": "Modular chassis"
    },
    "gbic": {
      "de": "GBIC",
      "en": "GBIC"
    },
    "x2": {
      "de": "X2",
      "en": "X2"
    },
    "xenpak": {
      "de": "XENPAK",
      "en": "XENPAK"
    },
    "xfp": {
      "de": "XFP",
      "en": "XFP"
    },
    "sfp": {
      "de": "SFP",
      "en": "SFP"
    },
    "sfp-plus": {
      "de": "SFP+",
      "en": "SFP+"
    },
    "sfp28": {
      "de": "SFP28",
      "en": "SFP28"
    },
    "sfp56": {
      "de": "SFP56",
      "en": "SFP56"
    },
    "qsfp-plus": {
      "de": "QSFP+",
      "en": "QSFP+"
    },
    "qsfp28": {
      "de": "QSFP28",
      "en": "QSFP28"
    },
    "qsfp56": {
      "de": "QSFP56",
      "en": "QSFP56"
    },
    "qsfp-dd": {
      "de": "QSFP-DD",
      "en": "QSFP-DD"
    },
    "cfp": {
      "de": "CFP",
      "en": "CFP"
    },
    "cfp2": {
      "de": "CFP2",
      "en": "CFP2"
    }
  },
  "deploy_role": {
    "access": {
      "de": "Access",
      "en": "Access"
    },
    "aggregation": {
      "de": "Aggregation",
      "en": "Aggregation"
    },
    "core": {
      "de": "Core",
      "en": "Core"
    },
    "datacenter-tor": {
      "de": "Rechenzentrum (Top-of-Rack)",
      "en": "Data centre (top-of-rack)"
    },
    "industrial": {
      "de": "Industrie",
      "en": "Industrial"
    }
  },
  "poe_standard": {
    "none": {
      "de": "Kein PoE",
      "en": "No PoE"
    },
    "802.3af": {
      "de": "PoE (IEEE 802.3af)",
      "en": "PoE (IEEE 802.3af)"
    },
    "802.3at": {
      "de": "PoE+ (IEEE 802.3at)",
      "en": "PoE+ (IEEE 802.3at)"
    },
    "802.3bt-t3": {
      "de": "PoE++ (IEEE 802.3bt Typ 3)",
      "en": "PoE++ (IEEE 802.3bt Type 3)"
    },
    "802.3bt-t4": {
      "de": "PoE++ (IEEE 802.3bt Typ 4)",
      "en": "PoE++ (IEEE 802.3bt Type 4)"
    },
    "upoe": {
      "de": "Cisco UPOE",
      "en": "Cisco UPOE"
    },
    "upoe-plus": {
      "de": "Cisco UPOE+",
      "en": "Cisco UPOE+"
    }
  },
  "psu_config": {
    "fixed-internal": {
      "de": "Fest eingebautes Netzteil",
      "en": "Fixed internal PSU"
    },
    "modular-single": {
      "de": "Modulares Netzteil (einzeln)",
      "en": "Modular PSU (single)"
    },
    "modular-redundant": {
      "de": "Modulare Netzteile, redundant",
      "en": "Modular PSUs, redundant"
    },
    "external": {
      "de": "Externes Netzteil",
      "en": "External PSU"
    }
  },
  "cooling": {
    "fanless": {
      "de": "Lüfterlos",
      "en": "Fanless"
    },
    "fixed-fans": {
      "de": "Fest verbaute Lüfter",
      "en": "Fixed fans"
    },
    "redundant-replaceable": {
      "de": "Redundante, austauschbare Lüfter",
      "en": "Redundant, field-replaceable fans"
    }
  },
  "airflow": {
    "front-to-back": {
      "de": "Vorne nach hinten",
      "en": "Front to back"
    },
    "back-to-front": {
      "de": "Hinten nach vorne",
      "en": "Back to front"
    },
    "side": {
      "de": "Seitlich",
      "en": "Side"
    },
    "reversible": {
      "de": "Umkehrbar",
      "en": "Reversible"
    }
  },
  "mgmt_ports": {
    "console-rj45": {
      "de": "Konsole (RJ45)",
      "en": "Console (RJ45)"
    },
    "console-usb": {
      "de": "Konsole (USB)",
      "en": "Console (USB)"
    },
    "oob-ethernet": {
      "de": "Out-of-Band-Ethernet",
      "en": "Out-of-band Ethernet"
    },
    "usb-a": {
      "de": "USB-A",
      "en": "USB-A"
    },
    "usb-c": {
      "de": "USB-C",
      "en": "USB-C"
    },
    "bluetooth": {
      "de": "Bluetooth",
      "en": "Bluetooth"
    }
  },
  "media": {
    "mmf": {
      "de": "Multimode-Faser (MMF)",
      "en": "Multimode fibre (MMF)"
    },
    "smf": {
      "de": "Singlemode-Faser (SMF)",
      "en": "Single-mode fibre (SMF)"
    },
    "dac-copper": {
      "de": "DAC-Kupferkabel",
      "en": "DAC copper"
    },
    "rj45-copper": {
      "de": "RJ45-Kupfer",
      "en": "RJ45 copper"
    },
    "aoc": {
      "de": "AOC (aktives optisches Kabel)",
      "en": "AOC (active optical cable)"
    }
  },
  "fiber_type": {
    "om1": {
      "de": "OM1",
      "en": "OM1"
    },
    "om2": {
      "de": "OM2",
      "en": "OM2"
    },
    "om3": {
      "de": "OM3",
      "en": "OM3"
    },
    "om4": {
      "de": "OM4",
      "en": "OM4"
    },
    "om5": {
      "de": "OM5",
      "en": "OM5"
    },
    "os1": {
      "de": "OS1",
      "en": "OS1"
    },
    "os2": {
      "de": "OS2",
      "en": "OS2"
    }
  },
  "connector": {
    "lc-duplex": {
      "de": "LC Duplex",
      "en": "LC duplex"
    },
    "lc-simplex": {
      "de": "LC Simplex",
      "en": "LC simplex"
    },
    "sc": {
      "de": "SC",
      "en": "SC"
    },
    "mpo-12": {
      "de": "MPO-12",
      "en": "MPO-12"
    },
    "mpo-16": {
      "de": "MPO-16",
      "en": "MPO-16"
    },
    "rj45": {
      "de": "RJ45",
      "en": "RJ45"
    },
    "integrated": {
      "de": "Fest konfektioniert",
      "en": "Integrated"
    }
  },
  "laser_type": {
    "vcsel": {
      "de": "VCSEL",
      "en": "VCSEL"
    },
    "fp": {
      "de": "Fabry-Pérot (FP)",
      "en": "Fabry-Pérot (FP)"
    },
    "dfb": {
      "de": "DFB",
      "en": "DFB"
    },
    "eml": {
      "de": "EML",
      "en": "EML"
    }
  },
  "mode": {
    "duplex": {
      "de": "Duplex (Zweifaser)",
      "en": "Duplex (two-fibre)"
    },
    "simplex-bidi": {
      "de": "BiDi (Einzelfaser)",
      "en": "BiDi (single-fibre)"
    }
  },
  "fec": {
    "none": {
      "de": "Nicht erforderlich",
      "en": "Not required"
    },
    "rs-fec": {
      "de": "RS-FEC",
      "en": "RS-FEC"
    },
    "fc-fec": {
      "de": "FC-FEC",
      "en": "FC-FEC"
    },
    "host-dependent": {
      "de": "Host-abhängig",
      "en": "Host dependent"
    }
  },
  "temp_class": {
    "commercial": {
      "de": "Kommerziell",
      "en": "Commercial"
    },
    "extended": {
      "de": "Erweitert",
      "en": "Extended"
    },
    "industrial": {
      "de": "Industrie",
      "en": "Industrial"
    }
  }
};
