// lib/inheritClasses.generated.ts — GENERATED by scripts/universe/apply-inheritance-classes.mjs.
// Do not edit by hand; re-run the classifier.
//
// specMerge.canInherit refuses any field with no inheritance class, so without this file the
// 29,703 mapped family-scoped facts — the majority of everything the corpus yields, because
// Cisco states most facts once per SERIES — are all discarded.
//
// A = property of the series, identical for every member (protocols, standards, software
//     feature sets, certifications).
// B = NEVER inherited; varies between members and inheriting it corrupts the whole series
//     (anything physical or electrical, port counts, PoE support, capacities).
// C = inheritable only when the document carries no per-SKU value (environmental envelopes,
//     architectural scale limits).
//
// Assigned per field from real sample values, biased towards B: an unclassified field only
// costs coverage, a wrong A silently writes one model's value onto every sibling.

export const GENERATED_CLASS_A: string[] = [
  "audio_codecs",   // A standards list (G.711, G.722, Opus, AAC-LD) implemented in shared software across the series.
  "automation_features",   // Automation/provisioning capability list (software and management features) shared by all members.
  "call_control",   // List of supported call-control platforms and registration modes - a software capability shared across the series.
  "console_port",   // Management console interface type (RJ-45 / virtual serial). A series shares one management interface design across all members.
  "crypto_algorithms",   // Lists of supported ciphers (AES, 3DES, IKE). Determined by the software/crypto engine of the series, not by an individual SKU.
  "cucm_versions",   // Supported call-control software releases - determined by the firmware the whole series runs.
  "deployment_mode",   // Prose capability list of deployment options; series-level software behaviour.
  "deployment_options",   // On-premises/cloud/hybrid describes how the product line is architected and sold, a series-level statement.
  "digital_signage",   // A software feature toggled in the cloud management platform; a series-level capability.
  "dual_stream",   // Protocol list (H.239 for H.323, BFCP for SIP) - standards support that is a property of the shared software stack.
  "eccn",   // Export control classification is a regulatory/compliance designation assigned at product-line level, identical for every member.
  "encryption",   // Standards-based media encryption (H.235, AES) implemented in software identically across the series.
  "firewall_traversal",   // Names the traversal technology and standards (Expressway, H.460.18/19) implemented in the shared software.
  "forwarding_mode",   // Prose capability statement of operating modes; a software property of the series.
  "google_meet_interop",   // An interoperability capability delivered by the shared software/cloud service rather than by an individual chassis.
  "host_os_support",   // Supported host OS list; software compatibility stated once per series.
  "hypervisor",   // Supported hypervisor list is a software-compatibility statement, uniform across a series.
  "ipv6_support",   // Protocol/standards support (dual-stack IPv4/IPv6, single call stack for H.323 and SIP) from the common software image.
  "languages_supported",   // Localization list; a software property identical across the series.
  "laser_safety_class",   // A safety certification class (Class 1) - a compliance designation held uniformly across the product line.
  "layer2_features",   // A protocol/feature capability list delivered by the shared software image; identical for every member of a series.
  "layer3_features",   // Routing protocol/feature list from the common software image — series-level by nature.
  "macro_customization",   // Macros and UI extensions are a software feature of the shared endpoint OS.
  "managed_by_fdm",   // Management interface support; a series-level software capability (differences seen in samples are across families, not within one).
  "managed_by_fmc",   // Management interface support; a software capability stated at series level.
  "management_mode",   // Prose list of management modes (Intersight Managed/Standalone); a software capability identical across the series.
  "mitigation_actions",   // Prose capability list of software actions (drop, reset, suspend) — software feature set, identical series-wide.
  "multicast_features",   // Multicast protocol support list, a property of the software image shared across the series.
  "operating_system",   // A list of supported/compatible operating systems — a software compatibility statement for the whole product line.
  "qos_features",   // Prose lists of QoS software capabilities (hierarchical QoS, ingress classification). Every member of a series runs the same image and suppor
  "regions_supported",   // Regulatory/market approval region list - a compliance statement that applies to the product line as a whole.
  "rohs_compliance",   // A compliance/certification statement that applies to the product line as manufactured.
  "safety_standards",   // Certification/compliance list; identical for every member of a series.
  "sdwan_capable",   // SD-WAN is a software/licensing capability of the platform image; all members of a series get the same answer.
  "security_features",   // No samples, but the field is a software/feature capability list; such feature sets are a property of the series software, identical across m
  "segment_routing_features",   // Prose list of segment-routing protocol capabilities and ISIS extensions — software feature set, uniform series-wide.
  "sip_h323_interop",   // Standards-based signalling support is a property of the shared software image.
  "snmp_mibs",   // A list of MIBs supported by the software image; identical across every member of the series.
  "status_leds",   // Prose description of LED colours and their meanings; an indicator semantics list shared across the series.
  "supported_browsers",   // Software compatibility list, identical across a series.
  "supported_fabric_interconnects",   // Compatibility list of supported FIs; a series-level interoperability statement, same for every node in the family.
  "supported_os",   // Supported operating systems is a software compatibility list, a series-level property.
  "system_management",   // Management interfaces and platforms supported (TMS, Control Hub) - a series-level software property.
  "third_party_apps",   // Software/feature capability (native web apps, webviews) delivered by the shared RoomOS build across the whole series.
  "ui_languages",   // A localisation list from the firmware; identical across every model running that software.
  "video_codecs",   // A standards list (H.264, H.265, AV1) provided by the common software stack.
  "whiteboarding",   // Named software applications supported (Webex Whiteboard, Miro, Mural, Microsoft Whiteboard) - a platform capability, identical across member
  "wireless_security",   // Prose list of supported authentication and encryption standards (WPA2/WPA3, AES) delivered by the shared software.
  "zoom_interop",   // Interop mode (SIP vs WebRTC) is a software capability of the platform, uniform across the series.
];

export const GENERATED_CLASS_B: string[] = [
  "ac_current",   // Electrical draw measured per model (0.48/0.49/0.50 A).
  "ac_through_current",   // Electrical rating in amps; a per-SKU housing/passive rating.
  "amplifier_type",   // Names the output device technology (GaN vs GaAs FET), which is exactly what differs between the high-output and standard variants of one amp
  "antenna_efficiency",   // Measured percentage/dB efficiency per band and per antenna model.
  "antenna_front_to_back",   // Measured dB ratio per band and per antenna model.
  "antenna_gain_ripple",   // Measured dB figure that varies between antenna variants (1.6 vs 1.3).
  "antenna_isolation",   // Measured port-to-port isolation in dB, differing per model (-14 vs -13).
  "antenna_type",   // Sector vs internal PIFA vs built-in panel is the physical radio hardware that distinguishes AP SKUs in one family.
  "attack_protection_time",   // A measured detection latency in seconds that differs between models (18s vs 10s).
  "audio_features",   // Values are tied to hardware counts (eight acoustic echo cancellers, frequency response of the fitted speakers), so they differ between model
  "audio_inputs",   // Physical connector and microphone counts (three mini-jack, eight phantom-powered mics) vary model to model.
  "audio_outputs",   // Enumerates physical audio connectors (1x vs 3x HDMI out, USB-C vs USB-A); connector counts and types differ between members of a room-system
  "battery_count",   // A physical component count differing per model (2 vs 4).
  "battery_life",   // Measured endurance in years differing per model (5 vs 2 years).
  "beamwidth_3db",   // Measured antenna radiation pattern in degrees — differs per antenna model.
  "beamwidth_azimuth",   // A measured antenna pattern in degrees; directional and omni variants of the same series differ completely.
  "boot_drive",   // Drive capacities differ per model (480GB vs 240GB M.2) even where the topology matches.
  "boot_drive_options",   // A per-model list of orderable drive PIDs tied to that node's supported configuration.
  "boot_storage",   // Physical internal media options (BMC FlexMMC, dual SD cards) differ per model generation within a family.
  "cache_drive_options",   // Orderable cache drive PIDs differ per node model (SATA SSD vs NVMe Optane).
  "call_bandwidth",   // A throughput measurement in Mbps (20 vs 16 vs 3 Mbps) that scales with the codec hardware of the specific model.
  "calling_platform",   // Webex Calling/UCM vs Teams Calling follows the per-SKU firmware variant, so it varies between members of one family.
  "capacity_drive_options",   // Data drive PID lists differ per node (HDD vs SATA SSD vs NVMe), reflecting each model's drive bays.
  "cellular_bands",   // Band lists are the regional/modem SKU variant (EU vs NA band sets) — the single most SKU-specific value on a cellular router.
  "cellular_category",   // CAT4 vs CAT6 is the modem fitted to a particular SKU; the whole point of the variant split within a series.
  "cellular_throughput",   // Numbers with units (150/50 vs 300/50 Mbps) tied to the modem category of that specific SKU.
  "channel_spacing",   // Numeric value with units (GHz/MHz) tied to the specific optical/RF variant; not a uniform series property.
  "chassis_config",   // Slot capacity and chassis build ('Chassis with 4-linecard capacity') is the physical differentiator between family members.
  "chipset",   // Silicon differs between family members (Intel C621 vs C621A) — a hardware generation marker.
  "cloud_management",   // Control Hub vs Teams Admin Center tracks the firmware variant SKU (e.g. -MSFT parts) sold within one family, so it differs between members.
  "color",   // A physical finish attribute with no samples to judge from; cannot be assumed uniform, so a per-SKU source is required.
  "compliance_model",   // A regulatory model identifier that is explicitly per-SKU (HS-WL-980 vs HS-WL-980-EC2-C vs -EC2-L); inheriting it mislabels every sibling.
  "composite_second_order",   // A measured RF distortion figure in dB; differs per amplifier/node model within a series.
  "composite_triple_beat",   // CTB distortion in dB - a measured RF performance figure that differs between amplifier variants.
  "compute_subsystem",   // CPU core count, clock, DRAM and storage sizes differ per model (8-core/8GB/32GB vs 4-core/32GB/128GB).
  "conference_parties_max",   // Per-model call-feature capacity; low-end and high-end members of a phone family differ.
  "console_ports",   // Physical port complement (RJ-45 vs RJ-45 + mini USB) differs per model.
  "console_ports_serial",   // A physical port count; small values but still per-chassis hardware inventory.
  "content_share_resolution",   // Sample values already split 3840x2160 vs 1920x1080 within the same field, so the sharing resolution tracks the individual model's silicon, n
  "copper_ethernet_ports",   // Raw port counts (6, 2, up to 16 modular) — the classic per-SKU physical variable within a series.
  "cpu_cores",   // Core count is the defining per-SKU difference between family members.
  "cpu_interconnect",   // UPI channel count and speed are properties of the specific processor/board in each model.
  "cpu_options",   // Supported processor PID lists differ per node model (single 6348 vs three-CPU choice).
  "cpu_threads",   // Thread count varies directly with the CPU fitted per SKU.
  "cross_modulation",   // Measured dB performance number, varies per member.
  "dc_input_current",   // Electrical current rating, per-SKU.
  "dc_input_voltage",   // Electrical input rating; differs per power-supply variant.
  "ddos_blocking_rate",   // pps capacity varying by an order of magnitude between members (0.357 to 2.7 billion).
  "ddos_blocking_throughput",   // Numeric throughput (240 Gbps to 3.4 Tbps) varying by model hardware.
  "ddos_mitigation_throughput",   // Numeric performance figure in Gbps that differs per model (6/20/60 Gbps) — the defining per-SKU spec.
  "ddos_prevention_rate",   // Packets-per-second measurement that is the model-differentiating figure (14 vs 35 vs 45 Mpps).
  "depth",   // Physical dimension; differs between chassis sizes in one series.
  "directivity",   // Measured directivity in dB, tied to the specific tap/coupler value of each SKU.
  "dispersion_penalty",   // Measured dB penalty tied to a specific optic's reach and rate.
  "display",   // Screen size, resolution and panel type are physical measurements and the primary differentiator between endpoint models.
  "dori_distances",   // Measured detection/recognition distances in metres, derived from each model's lens and sensor.
  "ethernet_switch",   // Port counts and link speeds (internal 2-port switch, 10/100BASE-T vs gigabit) - physical interface hardware that differs per model.
  "external_power",   // Whether external power is supported/required is a per-model hardware and functional difference (Yes/No/conditional).
  "extinction_ratio",   // Measured transmitter extinction ratio in dB - a per-SKU optical measurement.
  "fail_open_close",   // Describes which physical port groups have bypass hardware — differs with each model's port layout (modular copper vs integrated copper vs op
  "fan_hot_swap",   // No samples, but this is a physical/mechanical chassis property: fixed switches have fixed fans while modular siblings are hot-swappable.
  "field_of_view",   // Optics measurement in degrees that is precisely what distinguishes camera variants (114° vs 73° vs varifocal).
  "flows_per_second",   // Throughput capacity figure; scales with model size.
  "focal_length",   // Lens measurement in mm, the main differentiator between camera SKUs (2.8mm vs 3.8mm vs 3-9mm).
  "frequency_response",   // Measured flatness in dB across the band - a per-device measurement.
  "front_panel_ports",   // Physical connector complement varies by chassis/model.
  "fxo_ports",   // Port count; per-SKU physical fact.
  "fxs_ports",   // Port count; per-SKU physical fact.
  "gain_range",   // Measured amplifier gain in dB; the distinct gain variants are exactly what separate members of an amplifier family.
  "gpu_options",   // Supported GPU list depends on chassis slots, power and cooling — samples differ (L4 only vs A16/A30/A40/H100 vs three single-wide).
  "handset",   // Physical handset hardware, and a sample explicitly distinguishes '6821: narrowband handset' from the wideband handset on other members.
  "headset_support",   // Physical connectivity that varies per model - a sample states '6825 only: Bluetooth LE 4.1; 6823 and 6825: 3.5 mm'.
  "height",   // Physical faceplate dimension; per-SKU.
  "high_availability",   // Sample values are both Yes and No; clustering/HA support is gated per platform member, so inheriting could invert it.
  "housekeeping_drive_options",   // Per-model orderable drive PIDs (SD240GM1X-EV vs NVME2H-I1000).
  "housing_material",   // A physical construction property of the individual chassis; cheaper or ruggedised members of a phone family use different casings.
  "hum_modulation_12a",   // Measured dB hum figures quoted per frequency band, differing between members and band splits.
  "hum_modulation_15a",   // Measured dB hum figures at a specified current - a per-device electrical measurement.
  "image_sensor",   // Sensor size and resolution differ per camera model (1/3" 4MP vs 1/1.8" 8.4MP).
  "input_current",   // Electrical measurement in amps that scales with the PSU and port count of the individual model.
  "inrush_current",   // Electrical measurement (60 A peak, <50 A) tied to the specific power supply fitted to that SKU.
  "insertion_loss",   // Measured optical loss in dB, which scales with each variant's port count and construction.
  "insertion_loss_max",   // Measured optical loss in dB, differing per transceiver/module part (1.8, 2.1, 23).
  "internal_storage",   // Drive-bay counts and backplane options (10 SFF vs 28 x 2.5-inch); a physical per-chassis fact.
  "internal_tilt",   // Tilt in dB is a per-model RF design value (0, 1, 2, 21) with a stated tolerance - a measurement, not an envelope.
  "iops_random_mixed_4k",   // Measured performance number, per-SKU.
  "iops_random_read_4k",   // Measured performance number tied to the specific drive/config.
  "iops_random_write_4k",   // Measured performance number, per-SKU.
  "ir_illumination",   // Illuminator range in metres and presence/absence differ between siblings (15m, 30m, not supported).
  "isolation",   // Measured port isolation in dB, dependent on each device's port arrangement.
  "keys_buttons",   // Physical key and button inventory; a sample value itself enumerates different models (6821, 6841, 6851...) because they differ.
  "lan_interfaces",   // Port counts and speeds (four 10/100 vs 4x 10/100/1000) are exactly what distinguishes SKUs inside one router series.
  "led_indicators",   // Physical front-panel indicators; the sample values are also junk-extracted, so a series-level inherit would spread garbage. Physical layout 
  "lens_adjustment_range",   // Mechanical travel in degrees, differing per mount/form factor (Rotation 350° vs ±90°).
  "lens_aperture",   // Optical f-stop measurement differing per lens variant (f/1.8, f/1.2-2.3, f/2.0).
  "managed_devices_max",   // Sizing capacity that distinguishes appliance/licence tiers within a family.
  "max_endpoints",   // Appliance sizing capacity (16k/32k/80k) that is the whole point of the SKU difference.
  "max_optical_input_power",   // Receiver damage/overload threshold in dBm - a measured per-device electrical limit.
  "max_port_density",   // Port counts; the single most model-specific physical fact.
  "max_resolution",   // Pixel dimensions and frame rates - a measured hardware capability differing per model.
  "mezzanine_options",   // Physical slot/adapter options; front vs rear mezzanine availability differs between family members.
  "min_illumination",   // Measured lux sensitivity, and night-mode figure present on some models only.
  "modulation_format",   // Transmitter/receiver device type and modulation (APD, external modulator, DP-QPSK/8QAM) is a per-SKU optical property.
  "mtr_native",   // Native Teams Rooms mode is exactly what separates the -MSFT SKU from its Webex sibling in the same family; Yes/No differs per part.
  "multipoint",   // States a numeric conferencing capacity (5-way embedded SIP/H.323) versus ad-hoc only - a capacity figure that differs between low- and high-
  "network_adapter",   // Physically installed NIC/SuperNIC configuration differs between members.
  "network_interfaces",   // Counts and speeds of physical RJ-45/SFP ports; the defining difference between members of a family.
  "noise_figure",   // Measured dB figure tied to a specific gain point, differing per amplifier variant.
  "oir_support",   // Depends on chassis construction — modular members support OIR, fixed-configuration siblings do not.
  "optical_frequency",   // ITU channel frequency (195.9/195.8/195.7 THz) is the per-SKU identity of a DWDM optic.
  "optical_input_range",   // Input power window in mW/dBm - a receiver-specific measured range that differs between node variants.
  "optical_return_loss",   // Measured optical return loss in dB per device.
  "optical_test_point_scale",   // Test point scaling in V/mW - a measured electrical characteristic of the specific receiver board.
  "optical_zoom",   // Presence of a zoom lens is hardware and is exactly what separates members of a camera family.
  "optional_accessories",   // Accessory lists are model-specific (VESA/wall-mount kits, PTZ cameras, extra microphones fit particular chassis sizes only).
  "output_holdup_time",   // A millisecond measurement tied to the specific power supply and its input voltage.
  "passband",   // RF pass band in MHz (5-85, 105-1002, 54-1218) - the split-frequency variants are precisely how RF amplifier SKUs differ.
  "path_isolation",   // Port-to-port isolation in dB quoted per segmentation option and band - varies with each model's segmentation hardware.
  "physical_security",   // Describes physical fixtures (Kensington slot, security screws) present on some chassis and not others; physical, so inherit is unsafe.
  "poe_af_support",   // Same PoE/non-PoE SKU split, and one sample even shows it depends on a daughter card fitted to a particular model.
  "poe_at_support",   // PoE vs non-PoE is a primary SKU split inside every switch series; inheriting Yes would falsely make every model PoE+.
  "poe_budget_redundant",   // PoE wattage budget differing per model (720W/1152W/1440W) and dependent on PSU and port count.
  "power_load_idle_max",   // Measured watts (99 W vs 990.3 W across siblings) — the clearest possible per-SKU electrical value.
  "power_load_range",   // Wattage measurement from idle to maximum; varies with port count and PSU on every member.
  "presenter_tracking",   // Values name specific hardware pairings ('Board Pro G2 with the Cisco P...', 'requires an additional PTZ camera'); support depends on the ind
  "psu_output_power",   // Wattage figures (250W/400W/50W) are the defining difference between power supply and switch SKUs.
  "psu_output_rating",   // Voltage and current ratings (-56V at 19.64A vs 6.25A) are per power-supply-SKU electrical measurements.
  "raid_controller",   // Specific controller hardware fitted differs per model (24-Gbps tri-mode vs 12-Gbps modular).
  "raid_level",   // Reflects the controller actually fitted (Level 0 vs Level 10), which varies by member.
  "rear_panel_ports",   // Physical connector complement; per-SKU by nature.
  "return_loss",   // Measured reflectance/return loss in dB - a per-device electrical/optical measurement.
  "rf_gain",   // Operational gain in dB - a measured per-model amplifier rating.
  "rf_output_level",   // Output level in dBmV at a stated optical input - a measured per-model performance figure.
  "room_booking",   // Values name the platform and an accompanying hardware touch panel, which differ between the Webex and Microsoft variants of the same family.
  "rx_overload",   // Receiver overload threshold in dBm - a measured per-optic limit tied to the specific detector.
  "security_contexts",   // Licensed capacity that scales with the model (2/20, 2/50, 2/100).
  "sensors",   // Which sensor hardware is actually fitted (ultrasound presence, temperature/humidity/TVOC) differs between members.
  "sfp_ports",   // A physical uplink port count and speed (2 GE vs 4 FE, 2 GE) that varies model to model.
  "shutter_speed",   // An electrical/optical measurement range; even though samples agree, it is a per-model sensor spec and a wrong inherit corrupts the series.
  "simultaneous_content_sources",   // Bare counts (3, 2, 1) driven by the number of physical inputs on each model.
  "slots_occupied",   // Physical chassis footprint - slot count and card dimensions differ between line cards.
  "smsr",   // Side-mode suppression ratio in dB - a measured laser characteristic per optic.
  "spectral_width",   // Measured spectral width in nm, differing between laser types within a transceiver family.
  "ssd_capacity",   // Storage capacity in GB; a per-SKU hardware measurement.
  "ssl_connections_per_sec",   // CPS performance measurement differing per model (43/50/95/100 KCPS).
  "stack_ports",   // A physical port count — never inheritable across members.
  "supply_current",   // Electrical current draw in mA, differing per module (200 vs 300).
  "surge_rating",   // Electrical immunity figures in kV that differ between the samples (1kV vs 2kV DM/CM) per model's power design.
  "system_memory",   // No samples, but memory capacity is a hardware quantity and one of the main ways SKUs in a series differ.
  "test_point_level",   // Test point offset in dB with a stated tolerance - a per-model hardware design value.
  "timing_sync",   // Mixes protocol support with the presence of an integrated GNSS receiver — a hardware option that some members lack, so samples differ per mo
  "tls_hw_acceleration",   // Presence of dedicated crypto acceleration silicon is a hardware property; lower members of a series routinely lack it.
  "total_output_power",   // Output power in dBm - a per-SKU electrical/optical rating.
  "touchscreen",   // Display hardware construction (in-cell vs projected capacitive, optically bonded glass) - a per-model physical property.
  "tpm",   // Presence of a physical TPM chip; a hardware fitment fact that can differ per member.
  "tx_wavelength",   // Optical wavelength (1310, 1550, 850 nm bands) is the defining per-SKU parameter of an optic; inheriting it destroys the family.
  "uc_proxy_sessions",   // Session capacity number that scales per appliance model.
  "usb_passthrough",   // Bus generation and throughput (USB 3.2 gen1, maximum 5 Gbps) plus presence/absence - physical interface capability per model.
  "usb_ports",   // A physical port count (1, 2) that differs between members of a series.
  "vibration",   // Measured Grms tolerance differs per chassis (0.41 vs 1.12 Grms).
  "video_encode_decode",   // Resolution and frame-rate performance figures (1080p60 vs 1080p30, 4K content stream) that vary directly with each model's codec hardware.
  "video_inputs",   // Counts and types of physical connectors (1x USB-C vs two HDMI) differ between models in one family.
  "video_outputs",   // Physical output connector counts (3x HDMI vs 1 HDMI) are per-SKU hardware inventory.
  "video_quality_max",   // Maximum resolution/framerate is a hardware capability differing per model (4K vs 2x5MP vs 1080p).
  "vm_reserved_cpu",   // Numeric MHz resource reservation that scales per OVA/model size.
  "vm_reserved_ram",   // Numeric GB reservation that scales per model size.
  "voice_lines",   // Numeric line count (8, 1, 4) - the primary differentiator between phone models within one series.
  "wan_interfaces",   // Counts and types of physical WAN slots/ports differ between members (2x PIM vs LTE vs 10/100 uplinks). Physical interface inventory is per-S
  "webex_native",   // Mirror of the Teams variant split: some members of one family ship Webex-native and others do not.
];

export const GENERATED_CLASS_C: string[] = [
  "altitude_storage",   // An environmental envelope (up to 4000/13,000), typically series-wide, but a per-model figure in the same document must override.
  "attack_concurrent_sessions",   // An architectural scale limit ('Unlimited'), normally uniform across a series, but a per-model figure in the document must win.
  "cluster_min_nodes",   // An architectural minimum for the solution, normally stated once per series, but a per-model statement must override.
  "fabric_host_entries",   // Forwarding-table scale limit; inherit only when the document gives no per-model figure.
  "humidity_storage",   // An environmental envelope, normally uniform across a series, but a document stating a per-model range must win.
  "max_ssids",   // An architectural scale limit (16 per radio), normally uniform for the platform, but a per-model figure in the document must win.
  "max_wlans",   // An architectural scale limit (table size), usually uniform, but a per-model figure in the document must win.
  "netflow_acl_entries",   // An architectural table-size limit (1,000 ingress / 2,000 egress) — usually uniform per ASIC family, but a stated per-model figure must win.
  "queues_per_port",   // An architectural queuing limit, normally uniform across a series, but a document stating a per-model figure must win.
  "sgacl_entries",   // Architectural table-size limit; inherit only if no per-SKU value is stated.
  "sgt_bindings",   // A hardware table-size scale limit; usually uniform but a per-model figure in the document must win.
  "sgt_policies",   // Architectural table-size limit; inherit only if no per-SKU value is stated.
  "virtual_networks",   // VN/VRF scale limit; an architectural ceiling, per-model value wins if present.
];
