// src/core/derivedFillPaths.ts — the registered derivations: a cup whose tap is a function of data the store
// already holds (a SKU, a name), not a source that publishes it.
//
// ONE DEFINITION, because three consumers read it: the ledger builder (a derivation is an observed fill path),
// the completeness report (`fill_path: "derived"`), and the phase-1 freeze (a new or changed derivation moves
// the arrangement). It lived inside scripts/build-cup-ledger.mts until 13 Sep 2026, where nothing else could
// import it — which is how a second copy starts.
//
// A DERIVATION IS A TAP ONLY WHEN IT IS REGISTERED HERE WITH ITS VALIDATION (CLAUDE.md halting rules). The
// `validated` sentence carries the counts that licensed it; changing the function or its population means
// re-running the validation and changing the sentence, on the same commit as the rebuilt ledgers and freeze.
//
// COVERAGE DECIDES REQUIRED, and that is why `layer` is listed and still OPTIONAL: its derivation is exact
// (precision 1.000 over the 1,054 seeds) but speaks for 10.1% of switches, and a cup required of 4,931 parts on
// a path that reaches 500 is still mostly a gap nobody can close.
export const DERIVED_FILL_PATHS: Readonly<Record<string, { by: string; validated: string }>> = {
  form_factor_a: { by: "src/core/breakoutEnds.ts breakoutEndsFor", validated: "51 of 51 breakout-cable parts; SKU table agrees with the text reading on all 32 that have text" },
  form_factor_b: { by: "src/core/breakoutEnds.ts breakoutEndsFor", validated: "51 of 51 breakout-cable parts; SKU table agrees with the text reading on all 32 that have text" },
  breakout_count: { by: "src/core/breakoutEnds.ts breakoutEndsFor", validated: "51 of 51 breakout-cable parts; SKU table agrees with the text reading on all 32 that have text" },
  // round-7 ruling C (12 Sep 2026): the condition bundle_contents was approved under. Counts from the SKU control
  // (an independent reading of the SKU checked against the name parse), over the plan's 277 rows.
  bundle_contents: { by: "src/core/bundleContents.ts bundleContents (the bundle's own name)", validated: "277 plan rows (groups 4, 5, 6, 13): parsed 250, refused 27 with a reason (20 'required, not included', 4 no contents, 1 range, 1 unrecognised item, 1 drive with no unit); SKU control on the 250: agree 175, DISAGREE 2 (the vendor's name and SKU name different servers), SKU names nothing 73. +8 UCS-SPM-MDS rows: agree 8/8. The 101 'Cisco <sku>' rows are refused by rule (the name is only the SKU). Operator ruling 13 Sep 2026, routers `bundle` 19 rows: parsed 17, refused 2 (100GE-MSC-BNDL=, 100GE-FP140-BNDL= state no port count); SKU control (card + capacity / ASR5K 2322<GB><V><S><3|B> code) on the 17: agree 16, DISAGREE 1 (10GE-EMSE-OS-140G= '20x10GE Ethernet MSE Bundle': the SKU's 140G is an OVERSUBSCRIBED card, the name's 20 ports are right). Layers review A.4 (14 Sep 2026), the bundle rule widened: switches `bundle` 183 rows parsed 0, refused 183 with a reason; routers +71 rows parsed 0, refused 71 (routers `bundle` now 80: parsed 7, refused 73). Two refusals added on that measurement, both of which had produced a wrong line: an uncounted chassis after 'slot' / 'line card' / 'for' is the chassis the parts fit (C4500E-7R-S8E-MGIG 'upgrade for 7 slot chassis bundle' and CRS-8-LCC-FILTER= '… Line Card Chassis Filter - 5 Pack' had parsed '1x chassis'), and a named Nexus/Catalyst model or FEX word no line consumed refuses the row (C1-N5596UP-4FEX had parsed ['4x Nexus 2232 fabric extender'], N6004EF-8FEX-10G ['1x chassis']); the 277 plan rows stay parsed 250, refused 27" },
  // kind-layer (13 Sep 2026): layer 3. Hand-read rule table, reproduced exactly by the repo module (9,783 of 9,783 rows,
  // same role and same rule as III.0 item 3), 54 witnesses and 5 sabotaged rule lists in tests/deployRole.test.ts.
  deploy_role: { by: "src/core/deployRole.ts deployRole(category, kind, sku, name)", validated: "III.0 item 3 over 9,783 live switch/ap/router/phone rows: members placed 8,881, kind issues (not the kind) 899, null 3 (C8455-G2, C8475-G2, WS-C4928-10GE); name-token control over role-assigned rows found 6 contradictions, all 6 false positives of the control ('Spare Chassis', 'Israel' containing ISR, 'No DECT Radio'). Operator rulings 13 Sep 2026: the 3 nulls placed (C8455-G2/C8475-G2 branch, WS-C4928-10GE datacenter) — the table now differs from item 3 on exactly those 3 of 9,783 rows — plus 36 rows outside item 3's population placed by new or anchored rules (HF6100 9 datacenter, bare Meraki MS families 14, AP1572 bare 3 outdoor, SPA302D 7 dect, SLINK 3 wireless)" },
  // kind-layer (13 Sep 2026): the length a fixed-length transceiver cable's SKU states. Validation script and per-row
  // output: D:\tmp\kindlayer-impl\4-servers-transceiver\validate-cable-length.mts / cable-length-validation.tsv.
  cable_length: { by: "src/core/cableLength.ts cableLengthFromSku (transceiver `cable` and `breakout-cable` SKUs)", validated: "Cisco transceiver `cable` 183 rows: derived 158, refused 22 with a reason (20 range/family rows, 2 passive copper over 7 m: SFP-H10GB-CU15M/CU25M), no token 3 (PQSF2PXA*); against the 106 stored cable_length facts 106 agree 0 disagree, against the 122 names stating one length 122 agree 0 disagree. Cisco `breakout-cable` 60: derived 55 (4/4 facts, 36/36 names agree), refused 2, no token 3. Other vendors' cables (item-5 dump): derived 118 of 848, 118 of 118 agree with the name, the rest silent — their names carry the length for description mining" },
  // reviewer C.1 / ruling 4 (13 Sep 2026): the router PLATFORM table, column-backed, the gate of module_slots on `router`.
  modular: { by: "src/core/modularPlatform.ts modularPlatform (router platform table by SKU token, 16 families)", validated: "routers.router live rows 13 Sep 2026: members 1,238 -> modular 514, fixed 551, null 173 (14%: ISR 1100 93 — some 'Pluggable' models take a PIM and the SKU does not say which — 8100/8500/8600 G2 Secure Routers, ASR 1000 bundles); kind-issue rows 255 -> null 250 (not routers; they leave with their plans). Control: 0 router-kind rows hold a stored module_slots fact, so no fact control exists — each family row carries its datasheet evidence in the table instead. Witnesses and refusals in tests/linkProvenance.test.ts" },
  // REGISTERED 29 Sep 2026. `cellular` was derived into parts.cellular on 28 Sep (runs 1277/1278) and gates cellular_bands,
  // but was never registered here -- so tests/source-fields named routers/cellular as "required and no source publishes it",
  // a derivation reported as a coverage gap (the exact case requiredKeysByCategory's exemption exists for). It surfaced
  // again when ruling (d) declared the gate for modules in four more categories.
  cellular: { by: "src/core/cellular.ts cellularOf (SKU markers, then the name's first four markers; scripts/derive-cellular.mts)", validated: "all vendors, run 1277 (28 Sep 2026): 91,533 live parts written, 477 true (489 after run 1278), NULL 0; gate precision 1 over the 62 parts holding a cellular_bands fact (every one derived true), recall 1 from tests/cellular.test.ts" },
  layer: { by: "src/core/layerFromSku.ts", validated: "precision 1.000 over the 1,054 seeds (276 agree, 0 disagree); speaks for 500 of 4,931 switches (10.1%) — which is why the cup is optional" },
  // reviewer ruling (29 Sep 2026): pon_standard is a registered derivation, not a demotion. docs/decisions/2026-09-29-pon-cups.md
  pon_standard: { by: "src/core/ponStandard.ts ponStandardFromStandards (the ITU-T / IEEE recommendation NUMBER in the part's standards list)", validated: "all vendors, 29 Sep 2026: 8 live-part facts carry a PON recommendation number (Cisco 7 ieee_standards from the Catalyst PON sheet, 1 standard on SFP-10G-OLT20-X): derived 8 (gpon 7, xgs-pon 1), refused 0, and 8 of 8 agree with the family the part's own name states; witness table data/reference/pon-standard-witnesses.json, re-run by tests/ponStandard.test.ts" },
};
