// GENERATED by scripts/universe/write-status.ts — do not edit by hand.
// Field labels for lib/specsRead.ts. Deliberately dependency-free: the content session's reader
// must not import anything from the scraper pipeline, or a mid-edit scraper file would break its
// build again. validate-schema.ts fails if this drifts from lib/fieldSchema.ts.
export const FIELD_LABELS: Record<string, { de: string; en: string; unit?: string }> = {
  "vendor": { de: "Hersteller", en: "Manufacturer" },
  "series": { de: "Produktserie", en: "Product series" },
  "mgmt_class": { de: "Verwaltung", en: "Management class" },
  "layer": { de: "Switching-Ebene", en: "Switching layer" },
  "form_factor": { de: "Bauform", en: "Form factor" },
  "rack_units": { de: "Höheneinheiten", en: "Rack units", unit: "HE" },
  "stackable": { de: "Stapelbar", en: "Stackable" },
  "deploy_role": { de: "Einsatzbereich", en: "Deployment role" },
  "ports": { de: "Port-Bestückung", en: "Port configuration" },
  "uplink_ports": { de: "Uplink-Ports", en: "Uplink ports" },
  "uplink_modular": { de: "Modulare Uplinks", en: "Modular uplinks" },
  "module_slots": { de: "Modulslots", en: "Module slots" },
  "mgmt_ports": { de: "Management-Ports", en: "Management ports" },
  "poe_standard": { de: "PoE-Standard", en: "PoE standard" },
  "poe_ports": { de: "Anzahl PoE-Ports", en: "PoE port count" },
  "poe_budget": { de: "PoE-Budget", en: "PoE budget", unit: "W" },
  "poe_per_port_max": { de: "Max. PoE je Port", en: "Max PoE per port", unit: "W" },
  "switching_capacity": { de: "Switching-Kapazität", en: "Switching capacity", unit: "Gbit/s" },
  "forwarding_rate": { de: "Weiterleitungsrate", en: "Forwarding rate", unit: "Mpps" },
  "stacking_bandwidth": { de: "Stacking-Bandbreite", en: "Stacking bandwidth", unit: "Gbit/s" },
  "stack_max_members": { de: "Max. Switches je Stack", en: "Max stack members" },
  "packet_buffer": { de: "Paketpuffer", en: "Packet buffer", unit: "MB" },
  "mac_table": { de: "MAC-Adresstabelle", en: "MAC address table", unit: "Einträge" },
  "vlan_max": { de: "VLANs (aktiv)", en: "Active VLANs" },
  "ipv4_routes": { de: "IPv4-Routen", en: "IPv4 routes" },
  "ipv6_routes": { de: "IPv6-Routen", en: "IPv6 routes" },
  "multicast_groups": { de: "Multicast-Gruppen", en: "Multicast groups" },
  "acl_entries": { de: "ACL-Einträge", en: "ACL entries" },
  "jumbo_mtu": { de: "Jumbo-Frames (max. MTU)", en: "Jumbo frame max MTU", unit: "Byte" },
  "latency": { de: "Latenz", en: "Latency", unit: "µs" },
  "cpu": { de: "CPU", en: "CPU" },
  "dram": { de: "Arbeitsspeicher", en: "DRAM", unit: "GB" },
  "flash": { de: "Flash-Speicher", en: "Flash memory", unit: "GB" },
  "psu_config": { de: "Netzteil-Konfiguration", en: "PSU configuration" },
  "psu_redundant": { de: "Redundante Stromversorgung", en: "Redundant PSU" },
  "psu_options": { de: "Netzteil-Optionen", en: "PSU options" },
  "cooling": { de: "Kühlung", en: "Cooling" },
  "airflow": { de: "Luftstromrichtung", en: "Airflow direction" },
  "power_typical": { de: "Leistungsaufnahme (typisch)", en: "Typical power draw", unit: "W" },
  "power_max": { de: "Leistungsaufnahme (max.)", en: "Max power draw", unit: "W" },
  "input_voltage": { de: "Eingangsspannung", en: "Input voltage", unit: "V" },
  "input_freq": { de: "Netzfrequenz", en: "Input frequency", unit: "Hz" },
  "heat_dissipation": { de: "Wärmeabgabe", en: "Heat dissipation", unit: "BTU/h" },
  "temp_operating": { de: "Betriebstemperatur", en: "Operating temperature", unit: "°C" },
  "temp_storage": { de: "Lagertemperatur", en: "Storage temperature", unit: "°C" },
  "humidity_operating": { de: "Rel. Luftfeuchtigkeit (Betrieb)", en: "Operating humidity", unit: "%" },
  "altitude_max": { de: "Max. Betriebshöhe", en: "Max operating altitude", unit: "m" },
  "acoustic_noise": { de: "Geräuschpegel", en: "Acoustic noise", unit: "dB(A)" },
  "mtbf": { de: "MTBF", en: "MTBF", unit: "h" },
  "ip_rating": { de: "Schutzart (IP)", en: "IP rating" },
  "dimensions": { de: "Abmessungen (H×B×T)", en: "Dimensions (H×W×D)", unit: "mm" },
  "weight": { de: "Gewicht", en: "Weight", unit: "kg" },
  "certifications": { de: "Zertifizierungen", en: "Certifications" },
  "ieee_standards": { de: "IEEE-Standards", en: "IEEE standards" },
  "standard": { de: "Übertragungsstandard", en: "Transmission standard" },
  "data_rate": { de: "Datenrate", en: "Data rate", unit: "Gbit/s" },
  "media": { de: "Übertragungsmedium", en: "Media" },
  "fiber_type": { de: "Fasertyp", en: "Fiber type" },
  "wavelength": { de: "Wellenlänge", en: "Wavelength", unit: "nm" },
  "reach_max": { de: "Max. Reichweite", en: "Max reach", unit: "m" },
  "connector": { de: "Anschlusstyp", en: "Connector" },
  "tx_power": { de: "Sendeleistung (TX)", en: "TX power", unit: "dBm" },
  "rx_sensitivity": { de: "Empfangsempfindlichkeit (RX)", en: "RX sensitivity", unit: "dBm" },
  "link_budget": { de: "Link-Budget", en: "Link budget", unit: "dB" },
  "laser_type": { de: "Lasertyp", en: "Laser type" },
  "mode": { de: "Übertragungsmodus", en: "Transmission mode" },
  "bidi_wavelengths": { de: "BiDi-Wellenlängen (TX/RX)", en: "BiDi wavelengths", unit: "nm" },
  "ddm": { de: "DDM/DOM", en: "DDM/DOM" },
  "fec": { de: "FEC-Anforderung", en: "FEC requirement" },
  "temp_class": { de: "Temperaturbereich", en: "Temperature class" },
  "cable_length": { de: "Kabellänge", en: "Cable length", unit: "m" },
  "wire_gauge": { de: "Leiterquerschnitt", en: "Wire gauge", unit: "AWG" },
  "msa": { de: "MSA-Konformität", en: "MSA compliance" },
  "firewall_throughput": { de: "Firewall-Durchsatz", en: "Firewall throughput", unit: "Gbit/s" },
  "threat_throughput": { de: "Threat-Inspection-Durchsatz", en: "Threat inspection throughput", unit: "Gbit/s" },
  "ips_throughput": { de: "IPS-Durchsatz", en: "IPS throughput", unit: "Gbit/s" },
  "vpn_throughput": { de: "IPsec-VPN-Durchsatz", en: "IPsec VPN throughput", unit: "Gbit/s" },
  "concurrent_sessions": { de: "Gleichzeitige Sessions", en: "Concurrent sessions", unit: "Sessions" },
  "new_conn_per_sec": { de: "Neue Verbindungen/s", en: "New connections per second", unit: "1/s" },
  "vpn_peers": { de: "IPsec-VPN-Peers", en: "IPsec VPN peers", unit: "Peers" },
  "max_interfaces": { de: "Max. Schnittstellen", en: "Maximum interfaces" },
  "storage_capacity": { de: "Onboard-Speicher", en: "Onboard storage", unit: "GB" },
  "wifi_generation": { de: "WLAN-Generation", en: "Wi-Fi generation" },
  "spatial_streams": { de: "Spatial Streams", en: "Spatial streams" },
  "radio_count": { de: "Anzahl Funkmodule", en: "Radio count" },
  "max_data_rate": { de: "Max. Datenrate", en: "Maximum data rate", unit: "Gbit/s" },
  "ap_max_clients": { de: "Max. Clients je AP", en: "Max clients per AP" },
  "wlc_ap_capacity": { de: "Max. Access Points (Controller)", en: "Max access points (controller)" },
  "wlc_client_capacity": { de: "Max. Clients (Controller)", en: "Max clients (controller)" },
  "radio_bands": { de: "Frequenzbänder", en: "Frequency bands" },
  "router_throughput": { de: "System-Durchsatz", en: "System throughput", unit: "Gbit/s" },
  "ipsec_throughput": { de: "IPsec-Durchsatz", en: "IPsec throughput", unit: "Gbit/s" },
  "ipsec_tunnels": { de: "IPsec-Tunnel", en: "IPsec tunnels" },
  "advanced_functions": { de: "Erweiterte Funktionen", en: "Advanced functions" },
  "antenna_connector": { de: "Antennenanschluss", en: "Antenna connector" },
  "antenna_gain": { de: "Antennengewinn", en: "Antenna gain", unit: "dBi" },
  "anyconnect_sessions": { de: "AnyConnect-/Clientless-VPN-Benutzersitzungen", en: "AnyConnect/clientless VPN user sessions", unit: "Sitzungen" },
  "attenuation_dead_zone": { de: "Dämpfungstotzone", en: "Attenuation dead zone", unit: "m" },
  "beamwidth_elevation": { de: "Vertikaler Öffnungswinkel (3 dB)", en: "Elevation 3-dB beamwidth", unit: "°" },
  "chassis_compatibility": { de: "Chassis-Kompatibilität", en: "Chassis compatibility" },
  "coherent_interop_standards": { de: "Kohärente Interop-Standards", en: "Coherent interoperability standards" },
  "cross_connect": { de: "Cross-Connect", en: "Cross-connect" },
  "diagnostics": { de: "Diagnose und Fehlerbehebung", en: "Diagnostics and troubleshooting tools" },
  "emc_emissions": { de: "EMV-Störaussendung", en: "EMC emissions" },
  "emc_immunity": { de: "EMV-Störfestigkeit", en: "EMC immunity" },
  "etsi_standards": { de: "ETSI-Normen", en: "ETSI standards" },
  "expansion_io": { de: "Erweiterungs-I/O", en: "Expansion I/O" },
  "fabric_services": { de: "Fabric-Dienste", en: "Fabric services" },
  "input_power_range": { de: "Eingangsleistungsbereich (optisch)", en: "Optical input power range", unit: "dBm" },
  "itu_channel": { de: "ITU-Kanal", en: "ITU channel" },
  "jacket_color": { de: "Mantelfarbe", en: "Cable jacket color" },
  "jacket_material": { de: "Mantelmaterial", en: "Cable jacket material" },
  "min_software_release": { de: "Mindest-Systemsoftware", en: "Minimum system software release" },
  "mounting": { de: "Montage", en: "Mounting" },
  "optical_pm": { de: "Optische Leistungsüberwachung (Trunk)", en: "Trunk optical performance monitoring" },
  "otn_pm": { de: "OTN-Leistungsüberwachung", en: "OTN performance monitoring" },
  "polarization": { de: "Polarisation", en: "Polarization" },
  "power_full_load": { de: "Leistungsaufnahme bei 100% Durchsatz", en: "Power consumption at 100% throughput", unit: "W" },
  "product_compatibility": { de: "Produktkompatibilität", en: "Product compatibility" },
  "programming_interfaces": { de: "Programmierschnittstellen", en: "Programming interfaces" },
  "recycled_content": { de: "Rezyklatanteil", en: "Recycled content" },
  "redundancy": { de: "Redundanz", en: "Redundancy" },
  "reflective_dead_zone": { de: "Reflexionstotzone", en: "Reflective dead zone", unit: "m" },
  "rfc_compliance": { de: "RFC-Konformität", en: "RFC compliance" },
  "rx_wavelength": { de: "Empfangswellenlänge (Eingang)", en: "Receiver input wavelength", unit: "nm" },
  "serviceability": { de: "Wartungsfunktionen", en: "Serviceability" },
  "shelf_assembly": { de: "Baugruppenträger / Shelf-Assembly", en: "Shelf assembly" },
  "shock": { de: "Schockfestigkeit", en: "Shock resistance" },
  "slot_compatibility": { de: "Slot-Kompatibilität", en: "Slot compatibility" },
  "supported_modules": { de: "Unterstützte Module", en: "Supported modules" },
  "supported_protocols": { de: "Unterstützte Protokolle", en: "Supported protocols" },
  "supported_transceivers": { de: "Unterstützte Transceiver-Module", en: "Supported transceiver modules" },
  "usb_console": { de: "Integrierte USB-Konsole", en: "Integrated USB console" },
  "threat_defense_throughput": { de: "Threat-Defense-Durchsatz", en: "Threat Defense throughput", unit: "Gbit/s" },
  "tls_throughput": { de: "TLS-Entschlüsselungsdurchsatz", en: "TLS decryption throughput", unit: "Gbit/s" },
  "qos_features": { de: "QoS-Funktionen", en: "QoS features" },
  "security_features": { de: "Sicherheitsfunktionen", en: "Security features" },
  "crypto_algorithms": { de: "Kryptografische Algorithmen", en: "Cryptographic algorithms" },
  "wan_interfaces": { de: "WAN-Schnittstellen", en: "WAN interfaces" },
  "lan_interfaces": { de: "LAN-Schnittstellen", en: "LAN interfaces" },
  "cellular_category": { de: "Mobilfunk-Kategorie", en: "Cellular category" },
  "cellular_bands": { de: "Unterstützte Mobilfunkbänder", en: "Supported cellular bands" },
  "cellular_throughput": { de: "Mobilfunk-Downlink/Uplink-Durchsatz", en: "Cellular downlink/uplink throughput", unit: "Mbps" },
  "sdwan_capable": { de: "SD-WAN-fähig", en: "SD-WAN capable" },
  "led_indicators": { de: "LED-Anzeigen", en: "LED indicators" },
  "input_current": { de: "AC-Eingangsstrom (max.)", en: "AC input current (max)", unit: "A" },
  "inrush_current": { de: "AC-Einschaltstrom", en: "AC inrush/surge current", unit: "A" },
  "humidity_storage": { de: "Lagerfeuchtigkeit", en: "Storage humidity", unit: "%" },
  "usb_ports": { de: "USB-Anschlüsse (Typ A)", en: "USB ports (type A)" },
  "oir_support": { de: "Online-Wechsel im Betrieb (OIR)", en: "Online insertion and removal (OIR)" },
  "poe_at_support": { de: "IEEE 802.3at (PoE+) Unterstützung", en: "IEEE 802.3at (PoE+) support" },
  "poe_af_support": { de: "IEEE 802.3af (PoE) Unterstützung", en: "IEEE 802.3af (PoE) support" },
  "rohs_compliance": { de: "RoHS-Konformität", en: "RoHS compliance" },
  "psu_output_power": { de: "Netzteil-Ausgangsleistung", en: "Power supply output power", unit: "W" },
  "psu_output_rating": { de: "Netzteil-Ausgangsnennwert", en: "Power supply output rating" },
  "fan_hot_swap": { de: "Hot-Swap-Lüfter", en: "Hot-swappable fans" },
  "power_load_idle_max": { de: "Leistungsaufnahme, Leerlauf und Maximum", en: "Power consumption, idle and maximum", unit: "W" },
  "output_holdup_time": { de: "Ausgangs-Haltezeit", en: "Output holdup time", unit: "ms" },
  "console_ports_serial": { de: "RS-232 serielle Konsolenanschlüsse", en: "RS-232 serial console ports" },
  "netflow_acl_entries": { de: "NetFlow-ACL-Einträge", en: "NetFlow ACL entries" },
  "snmp_mibs": { de: "Unterstützte SNMP-MIBs", en: "Supported SNMP MIBs" },
  "sfp_ports": { de: "SFP-Anschlüsse", en: "SFP ports" },
  "altitude_storage": { de: "Lagerhöhe", en: "Storage altitude" },
  "antenna_type": { de: "Antennentyp", en: "Antenna type" },
  "beamwidth_azimuth": { de: "Azimut-3-dB-Öffnungswinkel", en: "Azimuth 3-dB beamwidth", unit: "degrees" },
  "physical_security": { de: "Physische Sicherung", en: "Physical security" },
  "nonoverlapping_channels": { de: "Maximale nicht überlappende Kanäle", en: "Maximum non-overlapping channels" },
  "operating_system": { de: "Betriebssystem", en: "Operating system" },
  "system_memory": { de: "Systemspeicher", en: "System memory" },
  "max_ssids": { de: "Maximale SSIDs", en: "Maximum SSIDs" },
  "wireless_security": { de: "WLAN-Authentifizierung und -Sicherheit", en: "Wireless authentication and security" },
  "ui_languages": { de: "Sprachen der Benutzeroberfläche", en: "User interface languages" },
  "display": { de: "Display", en: "Display" },
  "digital_signage": { de: "Digital-Signage-Unterstützung", en: "Digital signage support" },
  "cloud_management": { de: "Cloud-Verwaltungsplattform", en: "Cloud management platform" },
  "room_booking": { de: "Raumbuchung", en: "Room booking" },
  "audio_features": { de: "Audiofunktionen", en: "Audio features" },
  "audio_codecs": { de: "Audio-Codecs", en: "Audio codecs" },
  "video_codecs": { de: "Video-Codecs", en: "Video codecs" },
  "call_bandwidth": { de: "Maximale Anrufbandbreite", en: "Maximum call bandwidth", unit: "Mbps" },
  "encryption": { de: "Medienverschlüsselung", en: "Media encryption" },
  "google_meet_interop": { de: "Google-Meet-Interoperabilität", en: "Google Meet interoperability" },
  "zoom_interop": { de: "Zoom-Meetings-Interoperabilität", en: "Zoom Meetings interoperability" },
  "sip_h323_interop": { de: "Standardbasierte SIP/H.323-Interoperabilität", en: "Standards-based SIP/H.323 interoperability" },
  "mtr_native": { de: "Native Microsoft-Teams-Rooms-Erfahrung", en: "Native Microsoft Teams Rooms experience" },
  "webex_native": { de: "Native Webex-Meeting-Erfahrung", en: "Native Webex meeting experience" },
  "calling_platform": { de: "Enterprise-Telefonieplattform", en: "Enterprise calling platform" },
  "deployment_options": { de: "Bereitstellungsoptionen", en: "Deployment options" },
  "macro_customization": { de: "Makros und UI-Erweiterungen", en: "Macros and UI extension support" },
  "firewall_traversal": { de: "Firewall-Traversal", en: "Firewall traversal" },
  "video_inputs": { de: "Videoeingänge", en: "Video inputs" },
  "video_outputs": { de: "Videoausgänge", en: "Video outputs" },
  "audio_inputs": { de: "Audioeingänge", en: "Audio inputs" },
  "audio_outputs": { de: "Audioausgänge", en: "Audio outputs" },
  "content_share_resolution": { de: "Auflösung der Inhaltsfreigabe", en: "Content sharing resolution" },
  "simultaneous_content_sources": { de: "Gleichzeitige lokale Inhaltsquellen", en: "Simultaneous local content sources" },
  "third_party_apps": { de: "Unterstützung von Drittanbieter-Apps", en: "Third-party app support" },
  "whiteboarding": { de: "Whiteboarding", en: "Whiteboarding" },
  "presenter_tracking": { de: "Referenten-Tracking", en: "Presenter tracking" },
  "multipoint": { de: "Integrierte Mehrpunktkonferenz", en: "Embedded multipoint conferencing" },
  "dual_stream": { de: "Dual-Stream-Protokoll", en: "Dual-stream content protocol" },
  "video_encode_decode": { de: "Encode-/Decode-Leistung", en: "Encode/decode capability" },
  "max_resolution": { de: "Maximale unterstützte Auflösung", en: "Maximum supported resolution" },
  "ipv6_support": { de: "IPv6-Unterstützung", en: "IPv6 support" },
  "ethernet_switch": { de: "Integrierter Ethernet-Switch", en: "Integrated Ethernet switch" },
  "network_interfaces": { de: "Netzwerkschnittstellen", en: "Network interfaces" },
  "system_management": { de: "Systemverwaltung", en: "System management" },
  "compliance_model": { de: "Compliance-Modellnummer", en: "Compliance model number" },
  "cucm_versions": { de: "Unterstützte Cisco-Unified-CM-Versionen", en: "Supported Cisco Unified CM releases" },
  "call_control": { de: "Anrufsteuerung", en: "Call control support" },
  "voice_lines": { de: "Sprachleitungen", en: "Voice lines", unit: "lines" },
  "keys_buttons": { de: "Tasten und Schaltflächen", en: "Keys and buttons" },
  "handset": { de: "Hörer", en: "Handset" },
  "headset_support": { de: "Headset-Unterstützung", en: "Headset support" },
  "touchscreen": { de: "Touchscreen", en: "Touchscreen" },
  "sensors": { de: "Integrierte Sensoren", en: "Built-in sensors" },
  "housing_material": { de: "Gehäusematerial", en: "Housing material" },
  "usb_passthrough": { de: "USB-Passthrough", en: "USB passthrough" },
  "optional_accessories": { de: "Optionale Hardwarekomponenten", en: "Optional hardware components" },
  "tx_wavelength": { de: "Sendewellenlängenbereich", en: "Transmitter wavelength range", unit: "nm" },
  "modulation_format": { de: "Modulationsformat", en: "Modulation format" },
  "regions_supported": { de: "Unterstützte Länder und Regionen", en: "Countries and regions supported" },
  "gain_range": { de: "Verstärkungsbereich", en: "Gain range", unit: "dB" },
  "noise_figure": { de: "Rauschzahl", en: "Noise figure", unit: "dB" },
  "insertion_loss": { de: "Einfügedämpfung", en: "Insertion loss", unit: "dB" },
  "return_loss": { de: "Rückflussdämpfung", en: "Return loss", unit: "dB" },
  "total_output_power": { de: "Gesamtausgangsleistung", en: "Total output power", unit: "dBm" },
  "rx_overload": { de: "Empfänger-Überlastgrenze", en: "Receiver overload", unit: "dBm" },
  "laser_safety_class": { de: "Laserschutzklasse", en: "Laser safety class" },
  "optical_frequency": { de: "Optische Frequenz", en: "Optical frequency", unit: "THz" },
  "slots_occupied": { de: "Belegte Steckplätze", en: "Slots occupied", unit: "slots" },
  "smsr": { de: "Seitenmodenunterdrückung (SMSR)", en: "Side-mode suppression ratio", unit: "dB" },
  "spectral_width": { de: "Spektrale Breite", en: "Spectral width", unit: "nm" },
  "extinction_ratio": { de: "Extinktionsverhältnis", en: "Extinction ratio", unit: "dB" },
  "max_optical_input_power": { de: "Maximale optische Eingangsleistung", en: "Maximum optical input power", unit: "dBm" },
  "passband": { de: "Durchlassbereich", en: "Pass band", unit: "MHz" },
  "frequency_response": { de: "Frequenzgang", en: "Frequency response (flatness)", unit: "dB" },
  "rf_gain": { de: "Betriebsverstärkung (minimal)", en: "Operational gain (minimum)", unit: "dB" },
  "amplifier_type": { de: "Verstärkertechnologie", en: "Amplifier device technology" },
  "hum_modulation_12a": { de: "Brummmodulation bei 12 A", en: "Hum modulation at 12 A", unit: "dB" },
  "hum_modulation_15a": { de: "Brummmodulation bei 15 A", en: "Hum modulation at 15 A", unit: "dB" },
  "internal_tilt": { de: "Interne Neigung", en: "Internal tilt", unit: "dB" },
  "directivity": { de: "Richtschärfe", en: "Directivity", unit: "dB" },
  "isolation": { de: "Isolation", en: "Isolation", unit: "dB" },
  "path_isolation": { de: "Pfad-zu-Pfad-Isolation", en: "Path-to-path / port-to-port isolation", unit: "dB" },
  "optical_return_loss": { de: "Optische Rückflussdämpfung", en: "Optical return loss", unit: "dB" },
  "optical_input_range": { de: "Optischer Eingangsleistungsbereich", en: "Optical input power range", unit: "dBm" },
  "rf_output_level": { de: "RF-Ausgangspegel", en: "RF output level", unit: "dBmV" },
  "test_point_level": { de: "Messpunktpegel", en: "Test point level", unit: "dB" },
  "optical_test_point_scale": { de: "Skalierung des optischen Messpunkts", en: "Optical input test point scaling", unit: "V/mW" },
  "composite_triple_beat": { de: "Composite Triple Beat (CTB)", en: "Composite triple beat (CTB)", unit: "dB" },
  "composite_second_order": { de: "Composite Second Order (CSO)", en: "Composite second order (CSO)", unit: "dB" },
  "cross_modulation": { de: "Kreuzmodulation", en: "Cross modulation", unit: "dB" },
  "channel_spacing": { de: "Kanalabstand", en: "Channel spacing", unit: "GHz" },
  "ac_current": { de: "AC-Stromaufnahme", en: "AC current draw", unit: "A" },
  "ac_through_current": { de: "Maximaler AC-Durchgangsstrom (Dauer)", en: "Maximum AC through current (continuous)", unit: "A" },
  "depth": { de: "Tiefe", en: "Depth", unit: "in / cm" },
  "height": { de: "Frontplattenhöhe", en: "Faceplate height", unit: "in / cm" },
  "management_mode": { de: "Verwaltungsmodus", en: "Management mode" },
  "supported_fabric_interconnects": { de: "Unterstützte Fabric Interconnects", en: "Supported fabric interconnects" },
  "internal_storage": { de: "Interne Laufwerksschächte", en: "Internal drive bays" },
  "boot_storage": { de: "Boot- und Hilfsspeicher", en: "Boot and utility storage" },
  "mezzanine_options": { de: "Mezzanine-Adapteroptionen", en: "Mezzanine adapter options" },
  "raid_controller": { de: "RAID-Controller", en: "RAID controller" },
  "hypervisor": { de: "Unterstützter Hypervisor", en: "Supported hypervisor" },
  "supported_os": { de: "Unterstützte Betriebssysteme", en: "Supported operating systems" },
  "cpu_cores": { de: "CPU-Kerne", en: "CPU cores", unit: "cores" },
  "cpu_threads": { de: "CPU-Threads", en: "CPU threads", unit: "threads" },
  "network_adapter": { de: "Netzwerkadapter", en: "Network adapter" },
  "front_panel_ports": { de: "Anschlüsse Vorderseite", en: "Front-panel connectors" },
  "rear_panel_ports": { de: "Anschlüsse Rückseite", en: "Rear-panel connectors" },
  "iops_random_read_4k": { de: "Zufällige Lese-IOPS (4 KB)", en: "Random read IOPS (4 KB)", unit: "IOPS" },
  "iops_random_write_4k": { de: "Zufällige Schreib-IOPS (4 KB)", en: "Random write IOPS (4 KB)", unit: "IOPS" },
  "iops_random_mixed_4k": { de: "Gemischte IOPS (70/30, 4 KB)", en: "Random mixed IOPS (70/30, 4 KB)", unit: "IOPS" },
  "queues_per_port": { de: "Warteschlangen pro Port", en: "Queues per port" },
  "max_port_density": { de: "Maximale Portdichte", en: "Maximum port density" },
  "safety_standards": { de: "Sicherheitsnormen", en: "Safety standards" },
  "status_leds": { de: "Status-LEDs", en: "Status LEDs" },
  "max_wlans": { de: "Maximale Anzahl WLANs", en: "Maximum WLANs" },
  "console_ports": { de: "Konsolen-/Serielle Anschlüsse", en: "Console / serial ports" },
  "high_availability": { de: "Hochverfügbarkeit", en: "High availability" },
  "vibration": { de: "Vibrationsfestigkeit", en: "Vibration tolerance", unit: "Grms" },
  "ssd_capacity": { de: "SSD-Kapazität", en: "Solid-state drive" },
  "dc_input_voltage": { de: "DC-Eingangsspannung", en: "DC input voltage", unit: "VDC" },
  "dc_input_current": { de: "DC-Eingangsstrom", en: "DC input current", unit: "A" },
  "raid_level": { de: "RAID-Level", en: "RAID level" },
  "security_contexts": { de: "Security-Kontexte (inklusive/maximal)", en: "Security contexts (included/maximum)" },
  "flows_per_second": { de: "Flows pro Sekunde", en: "Flows per second" },
  "uc_proxy_sessions": { de: "Maximale Unified-Communications-Proxy-Sitzungen", en: "Unified Communications proxy sessions (max)" },
  "tpm": { de: "TPM-Chip", en: "TPM chip" },
  "managed_by_fmc": { de: "Verwaltung über Firewall Management Center", en: "Managed by Firewall Management Center" },
  "managed_by_fdm": { de: "Verwaltung über Firewall Device Manager", en: "Managed by Firewall Device Manager" },
  "supported_browsers": { de: "Unterstützte Webbrowser", en: "Supported web browsers" },
  "vm_reserved_cpu": { de: "Reservierte CPU-Ressource (VM)", en: "Reserved CPU resource (virtual machine)", unit: "MHz" },
  "vm_reserved_ram": { de: "Reservierter Arbeitsspeicher (VM)", en: "Reserved RAM (virtual machine)", unit: "GB" },
  "fxs_ports": { de: "FXS-Ports", en: "FXS ports" },
  "fxo_ports": { de: "FXO-Ports", en: "FXO ports" },
  "conference_parties_max": { de: "Maximale Konferenzteilnehmer", en: "Maximum conference parties" },
  "languages_supported": { de: "Unterstützte Sprachen", en: "Supported languages" },
  "max_endpoints": { de: "Maximale Anzahl Endpunkte", en: "Maximum endpoints", unit: "endpoints" },
  "sgt_bindings": { de: "IPv4-SGT-Bindungen", en: "IPv4 SGT bindings", unit: "entries" },
  "sgacl_entries": { de: "SGACL-Einträge (Contract-Aktionen)", en: "SGACL entries (contract actions)", unit: "entries" },
  "sgt_policies": { de: "SGT/DGT-Richtlinien", en: "SGT/DGT policies", unit: "entries" },
  "fabric_host_entries": { de: "Fabric-Host-Einträge", en: "Fabric host entries", unit: "entries" },
  "virtual_networks": { de: "Virtuelle Netzwerke (VNs/VRFs)", en: "Virtual networks (VNs/VRFs)", unit: "count" },
  "host_os_support": { de: "Unterstützte Host-Betriebssysteme", en: "Supported host operating systems" },
  "managed_devices_max": { de: "Maximale Anzahl verwalteter Geräte", en: "Maximum managed devices", unit: "devices" },
  "forwarding_mode": { de: "Weiterleitungsmodus", en: "Network forwarding mode" },
  "deployment_mode": { de: "Betriebs-/Einsatzmodus", en: "Deployment mode" },
  "copper_ethernet_ports": { de: "Kupfer-Ethernet-Ports (10/100/1000)", en: "Copper Ethernet ports (10/100/1000)", unit: "ports" },
  "console_port": { de: "Konsolenanschluss", en: "Console / management console port" },
  "mitigation_actions": { de: "Abwehrmassnahmen", en: "Mitigation / block actions" },
  "ddos_mitigation_throughput": { de: "DDoS-Mitigationsdurchsatz", en: "DDoS mitigation throughput", unit: "Gbps" },
  "ddos_blocking_throughput": { de: "DDoS-Blockierdurchsatz", en: "DDoS blocking throughput", unit: "Gbps" },
  "ddos_prevention_rate": { de: "DDoS-Flood-Abwehrrate", en: "DDoS flood attack prevention rate", unit: "pps" },
  "ddos_blocking_rate": { de: "DDoS-Blockierrate", en: "DDoS blocking rate", unit: "pps" },
  "ssl_connections_per_sec": { de: "SSL/TLS-Verbindungen pro Sekunde", en: "SSL/TLS connections per second", unit: "CPS" },
  "fail_open_close": { de: "Fail-Open-/Fail-Close-Verhalten", en: "Fail-open / fail-close behavior" },
  "eccn": { de: "Ausfuhrkontrollnummer (ECCN)", en: "Export Control Classification Number (ECCN)" },
  "attack_concurrent_sessions": { de: "Max. gleichzeitige Angriffssitzungen", en: "Maximum attack concurrent sessions" },
  "attack_protection_time": { de: "Zeit bis zur Angriffsabwehr", en: "Attack detection and protection time", unit: "s" },
  "tls_hw_acceleration": { de: "TLS-1.3-PFS-Hardwarebeschleunigung", en: "TLS 1.3 PFS hardware acceleration" },
  "boot_drive": { de: "Boot-Laufwerke", en: "Boot drives" },
  "gpu_options": { de: "Unterstützte GPUs", en: "Supported GPUs" },
  "cluster_min_nodes": { de: "Mindestanzahl Cluster-Knoten", en: "Minimum cluster nodes" },
  "beamwidth_3db": { de: "3-dB-Öffnungswinkel (H/V)", en: "3 dB beamwidth (H/V)", unit: "deg" },
  "antenna_efficiency": { de: "Antennenwirkungsgrad", en: "Antenna efficiency", unit: "%" },
  "antenna_gain_ripple": { de: "Gewinnwelligkeit", en: "Gain ripple", unit: "dB" },
  "antenna_isolation": { de: "Antennenisolation", en: "Port-to-port isolation", unit: "dB" },
  "antenna_front_to_back": { de: "Vor-Rück-Verhältnis", en: "Front-to-back ratio", unit: "dB" },
  "field_of_view": { de: "Sichtfeld", en: "Field of view", unit: "deg" },
  "image_sensor": { de: "Bildsensor", en: "Image sensor" },
  "video_quality_max": { de: "Maximale Videoqualität", en: "Maximum video quality" },
  "dori_distances": { de: "DORI-Reichweiten", en: "DORI distances", unit: "m" },
  "focal_length": { de: "Brennweite", en: "Focal length", unit: "mm" },
  "lens_aperture": { de: "Blende", en: "Aperture", unit: "f-stop" },
  "ir_illumination": { de: "IR-Beleuchtung", en: "IR illumination range", unit: "m" },
  "shutter_speed": { de: "Verschlusszeit", en: "Shutter speed", unit: "s" },
  "lens_adjustment_range": { de: "Objektiv-Verstellbereich", en: "Lens adjustment range", unit: "deg" },
  "min_illumination": { de: "Mindestbeleuchtung", en: "Minimum illumination", unit: "lux" },
  "optical_zoom": { de: "Optischer Zoom", en: "Optical zoom" },
  "stack_ports": { de: "Stacking-Ports (Anzahl)", en: "Stacking ports" },
  "power_load_range": { de: "Leistungsaufnahme (Leerlauf bis Maximum)", en: "Power load (idle to max)", unit: "W" },
  "poe_budget_redundant": { de: "PoE-Budget mit zweitem Netzteil", en: "PoE budget with second PSU", unit: "W" },
  "battery_count": { de: "Anzahl Batterien", en: "Number of batteries" },
  "battery_life": { de: "Erwartete Batterielebensdauer", en: "Expected battery life", unit: "years" },
  "external_power": { de: "Externe Stromversorgung", en: "External power supported" },
  "chassis_config": { de: "Chassis-Konfiguration", en: "Chassis configuration" },
  "color": { de: "Farbe", en: "Color" },
  "insertion_loss_max": { de: "Maximale Einfügedämpfung", en: "Maximum insertion loss", unit: "dB" },
  "dispersion_penalty": { de: "Dispersionsverlust", en: "Dispersion penalty", unit: "dB" },
  "supply_current": { de: "Versorgungsstrom", en: "Supply current", unit: "mA" },
  "timing_sync": { de: "Timing und Synchronisation", en: "Timing and synchronization" },
  "layer2_features": { de: "Layer-2-Funktionen", en: "Layer 2 features" },
  "layer3_features": { de: "Layer-3-Funktionen", en: "Layer 3 features" },
  "multicast_features": { de: "Multicast-Funktionen", en: "Multicast features" },
  "segment_routing_features": { de: "Segment Routing", en: "Segment routing" },
  "automation_features": { de: "Automatisierung und Bereitstellung", en: "Automation and provisioning" },
  "surge_rating": { de: "Stossspannungsfestigkeit (IEC 61000-4-5)", en: "Surge rating (IEC 61000-4-5)", unit: "kV" },
  "compute_subsystem": { de: "CPU, Arbeitsspeicher und Speicher", en: "CPU, memory and storage" },
  "boot_drive_options": { de: "Boot-Laufwerk Optionen", en: "Boot drive options" },
  "cache_drive_options": { de: "Cache-Laufwerk Optionen", en: "Cache drive options" },
  "capacity_drive_options": { de: "Kapazitäts-Laufwerk Optionen", en: "Capacity drive options" },
  "housekeeping_drive_options": { de: "Housekeeping-Laufwerk Optionen", en: "Housekeeping drive options" },
  "cpu_options": { de: "CPU-Optionen", en: "CPU options" },
  "chipset": { de: "Chipsatz", en: "Chipset" },
  "cpu_interconnect": { de: "CPU-Interconnect", en: "CPU interconnect" },
};

// Enum values are STORED as machine slugs ("l3", "rack-19", "802.3at") so they compare and filter
// cleanly. These are the human strings; a page must never print the slug.
export const ENUM_LABELS: Record<string, Record<string, { de: string; en: string }>> = {
  "vendor": {
    "cisco": {
      "de": "Cisco",
      "en": "Cisco"
    },
    "hpe": {
      "de": "HPE",
      "en": "HPE"
    },
    "aruba": {
      "de": "Aruba",
      "en": "Aruba"
    },
    "juniper": {
      "de": "Juniper",
      "en": "Juniper"
    },
    "arista": {
      "de": "Arista",
      "en": "Arista"
    },
    "dell-emc": {
      "de": "Dell EMC",
      "en": "Dell EMC"
    },
    "lenovo": {
      "de": "Lenovo",
      "en": "Lenovo"
    },
    "extreme": {
      "de": "Extreme Networks",
      "en": "Extreme Networks"
    },
    "fortinet": {
      "de": "Fortinet",
      "en": "Fortinet"
    },
    "nvidia": {
      "de": "NVIDIA",
      "en": "NVIDIA"
    },
    "mikrotik": {
      "de": "MikroTik",
      "en": "MikroTik"
    },
    "ubiquiti": {
      "de": "Ubiquiti",
      "en": "Ubiquiti"
    },
    "supermicro": {
      "de": "Supermicro",
      "en": "Supermicro"
    }
  },
  "mgmt_class": {
    "managed": {
      "de": "Managed",
      "en": "Managed"
    },
    "smart-managed": {
      "de": "Smart Managed",
      "en": "Smart managed"
    },
    "unmanaged": {
      "de": "Unmanaged",
      "en": "Unmanaged"
    }
  },
  "layer": {
    "l2": {
      "de": "Layer 2",
      "en": "Layer 2"
    },
    "l2plus": {
      "de": "Layer 2+",
      "en": "Layer 2+"
    },
    "l3": {
      "de": "Layer 3",
      "en": "Layer 3"
    }
  },
  "form_factor": {
    "rack-19": {
      "de": "19-Zoll-Rackmontage",
      "en": "19-inch rack"
    },
    "desktop": {
      "de": "Desktop",
      "en": "Desktop"
    },
    "din-rail": {
      "de": "DIN-Schienenmontage",
      "en": "DIN rail"
    },
    "modular-chassis": {
      "de": "Modulares Chassis",
      "en": "Modular chassis"
    },
    "gbic": {
      "de": "GBIC",
      "en": "GBIC"
    },
    "x2": {
      "de": "X2",
      "en": "X2"
    },
    "xenpak": {
      "de": "XENPAK",
      "en": "XENPAK"
    },
    "xfp": {
      "de": "XFP",
      "en": "XFP"
    },
    "sfp": {
      "de": "SFP",
      "en": "SFP"
    },
    "sfp-plus": {
      "de": "SFP+",
      "en": "SFP+"
    },
    "sfp28": {
      "de": "SFP28",
      "en": "SFP28"
    },
    "sfp56": {
      "de": "SFP56",
      "en": "SFP56"
    },
    "qsfp-plus": {
      "de": "QSFP+",
      "en": "QSFP+"
    },
    "qsfp28": {
      "de": "QSFP28",
      "en": "QSFP28"
    },
    "qsfp56": {
      "de": "QSFP56",
      "en": "QSFP56"
    },
    "qsfp-dd": {
      "de": "QSFP-DD",
      "en": "QSFP-DD"
    },
    "cfp": {
      "de": "CFP",
      "en": "CFP"
    },
    "cfp2": {
      "de": "CFP2",
      "en": "CFP2"
    }
  },
  "deploy_role": {
    "access": {
      "de": "Access",
      "en": "Access"
    },
    "aggregation": {
      "de": "Aggregation",
      "en": "Aggregation"
    },
    "core": {
      "de": "Core",
      "en": "Core"
    },
    "datacenter-tor": {
      "de": "Rechenzentrum (Top-of-Rack)",
      "en": "Data centre (top-of-rack)"
    },
    "industrial": {
      "de": "Industrie",
      "en": "Industrial"
    }
  },
  "poe_standard": {
    "none": {
      "de": "Kein PoE",
      "en": "No PoE"
    },
    "802.3af": {
      "de": "PoE (IEEE 802.3af)",
      "en": "PoE (IEEE 802.3af)"
    },
    "802.3at": {
      "de": "PoE+ (IEEE 802.3at)",
      "en": "PoE+ (IEEE 802.3at)"
    },
    "802.3bt-t3": {
      "de": "PoE++ (IEEE 802.3bt Typ 3)",
      "en": "PoE++ (IEEE 802.3bt Type 3)"
    },
    "802.3bt-t4": {
      "de": "PoE++ (IEEE 802.3bt Typ 4)",
      "en": "PoE++ (IEEE 802.3bt Type 4)"
    },
    "upoe": {
      "de": "Cisco UPOE",
      "en": "Cisco UPOE"
    },
    "upoe-plus": {
      "de": "Cisco UPOE+",
      "en": "Cisco UPOE+"
    }
  },
  "psu_config": {
    "fixed-internal": {
      "de": "Fest eingebautes Netzteil",
      "en": "Fixed internal PSU"
    },
    "modular-single": {
      "de": "Modulares Netzteil (einzeln)",
      "en": "Modular PSU (single)"
    },
    "modular-redundant": {
      "de": "Modulare Netzteile, redundant",
      "en": "Modular PSUs, redundant"
    },
    "external": {
      "de": "Externes Netzteil",
      "en": "External PSU"
    }
  },
  "cooling": {
    "fanless": {
      "de": "Lüfterlos",
      "en": "Fanless"
    },
    "fixed-fans": {
      "de": "Fest verbaute Lüfter",
      "en": "Fixed fans"
    },
    "redundant-replaceable": {
      "de": "Redundante, austauschbare Lüfter",
      "en": "Redundant, field-replaceable fans"
    }
  },
  "airflow": {
    "front-to-back": {
      "de": "Vorne nach hinten",
      "en": "Front to back"
    },
    "back-to-front": {
      "de": "Hinten nach vorne",
      "en": "Back to front"
    },
    "side": {
      "de": "Seitlich",
      "en": "Side"
    },
    "reversible": {
      "de": "Umkehrbar",
      "en": "Reversible"
    }
  },
  "mgmt_ports": {
    "console-rj45": {
      "de": "Konsole (RJ45)",
      "en": "Console (RJ45)"
    },
    "console-usb": {
      "de": "Konsole (USB)",
      "en": "Console (USB)"
    },
    "oob-ethernet": {
      "de": "Out-of-Band-Ethernet",
      "en": "Out-of-band Ethernet"
    },
    "usb-a": {
      "de": "USB-A",
      "en": "USB-A"
    },
    "usb-c": {
      "de": "USB-C",
      "en": "USB-C"
    },
    "bluetooth": {
      "de": "Bluetooth",
      "en": "Bluetooth"
    }
  },
  "media": {
    "mmf": {
      "de": "Multimode-Faser (MMF)",
      "en": "Multimode fibre (MMF)"
    },
    "smf": {
      "de": "Singlemode-Faser (SMF)",
      "en": "Single-mode fibre (SMF)"
    },
    "dac-copper": {
      "de": "DAC-Kupferkabel",
      "en": "DAC copper"
    },
    "rj45-copper": {
      "de": "RJ45-Kupfer",
      "en": "RJ45 copper"
    },
    "aoc": {
      "de": "AOC (aktives optisches Kabel)",
      "en": "AOC (active optical cable)"
    }
  },
  "fiber_type": {
    "om1": {
      "de": "OM1",
      "en": "OM1"
    },
    "om2": {
      "de": "OM2",
      "en": "OM2"
    },
    "om3": {
      "de": "OM3",
      "en": "OM3"
    },
    "om4": {
      "de": "OM4",
      "en": "OM4"
    },
    "om5": {
      "de": "OM5",
      "en": "OM5"
    },
    "os1": {
      "de": "OS1",
      "en": "OS1"
    },
    "os2": {
      "de": "OS2",
      "en": "OS2"
    }
  },
  "connector": {
    "lc-duplex": {
      "de": "LC Duplex",
      "en": "LC duplex"
    },
    "lc-simplex": {
      "de": "LC Simplex",
      "en": "LC simplex"
    },
    "sc": {
      "de": "SC",
      "en": "SC"
    },
    "mpo-12": {
      "de": "MPO-12",
      "en": "MPO-12"
    },
    "mpo-16": {
      "de": "MPO-16",
      "en": "MPO-16"
    },
    "rj45": {
      "de": "RJ45",
      "en": "RJ45"
    },
    "integrated": {
      "de": "Fest konfektioniert",
      "en": "Integrated"
    }
  },
  "laser_type": {
    "vcsel": {
      "de": "VCSEL",
      "en": "VCSEL"
    },
    "fp": {
      "de": "Fabry-Pérot (FP)",
      "en": "Fabry-Pérot (FP)"
    },
    "dfb": {
      "de": "DFB",
      "en": "DFB"
    },
    "eml": {
      "de": "EML",
      "en": "EML"
    }
  },
  "mode": {
    "duplex": {
      "de": "Duplex (Zweifaser)",
      "en": "Duplex (two-fibre)"
    },
    "simplex-bidi": {
      "de": "BiDi (Einzelfaser)",
      "en": "BiDi (single-fibre)"
    }
  },
  "fec": {
    "none": {
      "de": "Nicht erforderlich",
      "en": "Not required"
    },
    "rs-fec": {
      "de": "RS-FEC",
      "en": "RS-FEC"
    },
    "fc-fec": {
      "de": "FC-FEC",
      "en": "FC-FEC"
    },
    "host-dependent": {
      "de": "Host-abhängig",
      "en": "Host dependent"
    }
  },
  "temp_class": {
    "commercial": {
      "de": "Kommerziell",
      "en": "Commercial"
    },
    "extended": {
      "de": "Erweitert",
      "en": "Extended"
    },
    "industrial": {
      "de": "Industrie",
      "en": "Industrial"
    }
  }
};
