// src/core/kindOverrides.ts — kinds for SKUs no axis can classify, one entry per SKU, ruled 28 Sep 2026
// (docs/decisions/2026-09-28-unknown-kind-106.md; reviewer ruling 12). Consulted by partKind ONLY where the category's axis
// answers unknown, so an axis that learns a SKU wins; tests/kindOverrides.test.ts fails on such a stale entry and on any
// kind the category does not declare. 4036797.1610 (the D-PON ONT) is the switch axis's ont rule (12b). The 13 collab
// bundles joined with 12a. The 12 MobileAccessVE units are `device` per the q28 decision, named by the wireless AXIS
// (wirelessKind), not here. CIT3-FI-M-6324 applies once it has moved to servers-unified-computing.
/** `evidence`: the line of the part's OWN document that decides the kind (ruling Q9, 29 Sep 2026: "kind from their
 *  documents, read row by row"). Entries before Q9 carry their reasoning in their decision file instead. */
export type KindOverride = { category: string; kind: string; evidence?: string };
export const KIND_OVERRIDES: Readonly<Record<string, KindOverride>> = {
  // collaboration-endpoints
  "CS-R-USB-UPG-BUN": { category: "collaboration-endpoints", kind: "accessory" },
  "WBP54G": { category: "collaboration-endpoints", kind: "accessory" },
  // collaboration-endpoints: carts, promo bundles and demo kits -> bundle (ruling 12a, 28 Sep 2026)
  "AVIZ-EDU=": { category: "collaboration-endpoints", kind: "bundle" },
  "AVIZ-SYN=": { category: "collaboration-endpoints", kind: "bundle" },
  "AVIZ-TAC-K9": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-ATP-MX200-K9": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-ATP-MX300-K9": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-ATP-PHD-USB": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-ATP-PHD4XS1": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-ATP-QSC20-K9": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-ATP-QSC20-MIC": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-MXNMTCH-PRM-K9": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-TPEB-PRM-K9": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-TPSB-PRM-K9": { category: "collaboration-endpoints", kind: "bundle" },
  "CTS-VNDCNCT-PR-K9": { category: "collaboration-endpoints", kind: "bundle" },
  // servers-unified-computing: the FI that sat in collab moves here (ruling 12, 28 Sep 2026)
  "CIT3-FI-M-6324": { category: "servers-unified-computing", kind: "fabric-interconnect" },
  // interfaces-modules
  "AIM-DES/BP": { category: "interfaces-modules", kind: "module" },
  "SM-EC-3DES": { category: "interfaces-modules", kind: "module" },
  "SM-EC-3DES=": { category: "interfaces-modules", kind: "module" },
  "SM-EC-DES": { category: "interfaces-modules", kind: "module" },
  "WDM-SFP-2CH-CONV=": { category: "interfaces-modules", kind: "mux" },
  // optical-networking
  "15216-FLAMP36.6-SK": { category: "optical-networking", kind: "amplifier" },
  "15216-FLAMP44.5-SK": { category: "optical-networking", kind: "amplifier" },
  "15216-FLAMP52.5-SK": { category: "optical-networking", kind: "amplifier" },
  "15216-FLAMP60.6-SK": { category: "optical-networking", kind: "amplifier" },
  "EWDM-OA=": { category: "optical-networking", kind: "amplifier" },
  "15454-10GEXPE-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-10GEXPE-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454-80ROADM-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-80ROADM-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454-ARE-K9-SK": { category: "optical-networking", kind: "linecard" },
  "15454-ARE-L-K9-SK": { category: "optical-networking", kind: "linecard" },
  "15454-MSEXT24-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-MSEXT24-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454-OTU2XP-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-OTU2XP-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454-PPMESH8-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-PPMESH8-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454W-2X100G-SK": { category: "optical-networking", kind: "linecard" },
  "15454W-5X40GMXP-SK": { category: "optical-networking", kind: "linecard" },
  "15454W-5XOTU2XP-SK": { category: "optical-networking", kind: "linecard" },
  "NCS2K-10X200XP-SK": { category: "optical-networking", kind: "linecard" },
  "NCS2K-10XMXP-SK": { category: "optical-networking", kind: "linecard" },
  "NCS2K-400G-BUN-SK": { category: "optical-networking", kind: "linecard" },
  "NCS2K-400GXP-SK": { category: "optical-networking", kind: "linecard" },
  "15216-CMXDMX-SK": { category: "optical-networking", kind: "mux" },
  "15454-40SMR2-LLP3": { category: "optical-networking", kind: "roadm" },
  "15454-40SMR2-LLP5": { category: "optical-networking", kind: "roadm" },
  "15454-OPTAMPC-LLP3": { category: "optical-networking", kind: "roadm" },
  "15454-OPTAMPC-LLP5": { category: "optical-networking", kind: "roadm" },
  "15454-PP4SMR-LLP3": { category: "optical-networking", kind: "roadm" },
  "15454-PP4SMR-LLP5": { category: "optical-networking", kind: "roadm" },
  "NCS2006-FS-RDR-SK": { category: "optical-networking", kind: "roadm" },
  // servers-unified-computing
  "UCS-ASR5700-01": { category: "servers-unified-computing", kind: "bundle" },
  "UCSC-OCP-100G": { category: "servers-unified-computing", kind: "nic" },
  "UCSC-OCP-100G=": { category: "servers-unified-computing", kind: "nic" },
  "UCSC-OCP-1025G": { category: "servers-unified-computing", kind: "nic" },
  "UCSC-OCP-1025G=": { category: "servers-unified-computing", kind: "nic" },
  "XRV-PCIE-C40Q-03": { category: "servers-unified-computing", kind: "nic" },
  "SVC-E1120D-M3": { category: "servers-unified-computing", kind: "server" },
  "SVC-E160S-M3": { category: "servers-unified-computing", kind: "server" },
  "SVC-E180D-M3": { category: "servers-unified-computing", kind: "server" },
  // unified-communications
  "CIT-E160D-M2BUN/K9": { category: "unified-communications", kind: "server" },
  "CTI-ATP-VCS-CTRLK9": { category: "unified-communications", kind: "server" },
  "CTI-ATP-VCS-EXPWK9": { category: "unified-communications", kind: "server" },
  "CTI-ATP-VCS-SPAKK9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-BASE-K9=": { category: "unified-communications", kind: "server" },
  "CTI-VCS-BASE=": { category: "unified-communications", kind: "server" },
  "CTI-VCS-CNTRL-K9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-CONTRL-K9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-EXPRESS-K9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-EXPWY-K9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-STPAK-K9": { category: "unified-communications", kind: "server" },
  "EXPWY-C-K9": { category: "unified-communications", kind: "server" },
  "EXPWY-E-K9": { category: "unified-communications", kind: "server" },
  "UNITYCN7-BUNDLE": { category: "unified-communications", kind: "server" },
  // video
  "4029111": { category: "video", kind: "node" },
  "750185": { category: "video", kind: "passive" },
  "9220F-DIFL": { category: "video", kind: "passive" },
  "BUNDLE1-3G60-DS384": { category: "video", kind: "system" },
  "DS38410X64UPGRADRF": { category: "video", kind: "system" },
  // wireless
  "AIR-BR1310G": { category: "wireless", kind: "ap" },
  "ASCT-EX3200": { category: "wireless", kind: "appliance" },
  "CWWLSE-1130-19-K9": { category: "wireless", kind: "appliance" },
  "ON100-M6-K9": { category: "wireless", kind: "appliance" },
  "2KI-FINAL-PKG-RU": { category: "wireless", kind: "mechanical" },
  "FINAL-PKG-RUSSIA": { category: "wireless", kind: "mechanical" },
  "AIR-BLE-BEACON-BLK": { category: "wireless", kind: "wireless-sensor" },
  "AIR-BLE-TAG-BULK": { category: "wireless", kind: "wireless-sensor" },
  "AIR-VBLE1-K9": { category: "wireless", kind: "wireless-sensor" },
  // ---- RULING Q9 (29 Sep 2026): the DOC-LINKED unknowns, each by its own document (docs/reviewer/2026-09-28/batch-d-report.md). ----
  // FLMESH-HW-ACC-<n>: the URWB end-of-life bulletin names each one's Fluidmesh product (FM-...), which wirelessKind already
  // classifies: 32 cables, 3 mechanical, 3 PoE injectors, 6 accessories (FM-EMP, which the axis cannot place, takes Q9 (1)'s
  // family default). Q9 (1) had said 'accessory by SKU' for all 44 -- my premise, and the bulletin shows it was wrong.
  // The video PIDs: each bulletin row names the Prisma II / GS7000 product, which videoKind classifies. HX-16-*: the spec
  // sheet says Windows Server 2016 licences: NOT here -- a named kind asked nothing on a HARDWARE part broke the round-7 acceptance
  // (cupLedger: asked-nothing is the fallback kinds only), so the 12 stay unknown (evidenced) until the class change to licence
  // (Q16) takes them out of hardware. Twins (X / X=) follow.
"CIUS-BATTERY=": { category: "collaboration-endpoints", kind: "power", evidence: "Lithium Batteries product bulletin row: 'Cius Spare Battery - Cius Tablet'" },
  "SPVAC-C7416-S-JP=": { category: "collaboration-endpoints", kind: "conference-camera", evidence: "VXME Accessories data sheet row: 'LogiCool Webcam C920-C - Smoke - Japan'" },
  "SPVAC-C7416-S=": { category: "collaboration-endpoints", kind: "conference-camera", evidence: "VXME Accessories data sheet row: 'Logitech Webcam C920-C - Smoke - Global'" },
  "SPVAC-H5610-S-CL=": { category: "collaboration-endpoints", kind: "headset", evidence: "VXME Accessories data sheet row: 'Jabra Handset 450 for Cisco - Smoke' (CL)" },
  "SPVAC-H5610-S-EU=": { category: "collaboration-endpoints", kind: "headset", evidence: "VXME Accessories data sheet row: 'Jabra Handset 450 for Cisco - Smoke' (EU)" },
  "SPVAC-H5610-S-JP=": { category: "collaboration-endpoints", kind: "headset", evidence: "VXME Accessories data sheet row: 'Jabra Handset 450 for Cisco - Smoke' (JP)" },
  "SPVAC-H5610-S-TW=": { category: "collaboration-endpoints", kind: "headset", evidence: "VXME Accessories data sheet row: 'Jabra Handset 450 for Cisco - Smoke' (TW)" },
  "SPVAC-H5610-S-US=": { category: "collaboration-endpoints", kind: "headset", evidence: "VXME Accessories data sheet row: 'Jabra Handset 450 for Cisco - Smoke' (US)" },
  "SPVAC-UC725-S-BDL=": { category: "collaboration-endpoints", kind: "bundle", evidence: "VXME Accessories data sheet row: 'Logitech UC Solution for Cisco 725-C Bundle ... Includes: Logitech UC Keyboard ...'" },
  "SPVAC-UC725JP-S-BDL=": { category: "collaboration-endpoints", kind: "bundle", evidence: "VXME Accessories data sheet row: 'LogiCool UC Solution for Cisco 725-C Bundle - Japan Only'" },
  "HCIX-NVL2-H200": { category: "hyperconverged-infrastructure", kind: "mechanical", evidence: "X580p PCIe Node spec sheet: 'The NVL Bridge (HCIX-NVL2-H200)' - a passive NVLink bridge between two H200 GPUs" },
  "HCIX-NVL2-H200=": { category: "hyperconverged-infrastructure", kind: "mechanical", evidence: "twin of HCIX-NVL2-H200 (spare = base): X580p PCIe Node spec sheet: 'The NVL Bridge (HCIX-NVL2-H200)' - a passive NVLink bridge between two H200 GPUs" },
  "UCSX-NVL2-H200": { category: "servers-unified-computing", kind: "mechanical", evidence: "X580p PCIe Node spec sheet: 'The NVL Bridge (UCSX-NVL2-H200)' - a passive NVLink bridge between two H200 GPUs" },
  "UCSX-NVL2-H200=": { category: "servers-unified-computing", kind: "mechanical", evidence: "twin of UCSX-NVL2-H200 (spare = base): X580p PCIe Node spec sheet: 'The NVL Bridge (UCSX-NVL2-H200)' - a passive NVLink bridge between two H200 GPUs" },
  "UCSXE-1U-E3S-1L": { category: "servers-unified-computing", kind: "mechanical", evidence: "XE150c M8 spec sheet: 'the UCSXE-1U-E3S-1L storage riser' - a passive riser (as Q8's riser)" },
  "UCSXE-1U-E3S-2L": { category: "servers-unified-computing", kind: "mechanical", evidence: "XE150c M8 spec sheet: 'If the UCSXE-1U-E3S-2L riser is ...' - a passive riser" },
  "UCSXE-1U-PCI-L": { category: "servers-unified-computing", kind: "mechanical", evidence: "XE150c M8 spec sheet: 'the UCSXE-1U-PCI-L IO riser' - a passive riser" },
  "4002242": { category: "video", kind: "plug-in", evidence: "EoL bulletin row: 4002242 = P2-OPSW-FP-LOINPUT" },
  "4002243": { category: "video", kind: "plug-in", evidence: "EoL bulletin row: 4002243 = P2-OPSW-E2-LOINPUT" },
  "4010485.114.000.AA": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 4010485.114.000.AA = P2-EDFA-FPST-18X18.9-LA" },
  "4030095": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030095 = GS7000-OP-CWDM-1X8-1470-1610-SA-MPO" },
  "4030098": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030098 = GS7000-OP-DWDM-1X8-100G-3643-SA-MPO" },
  "4030099": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030099 = GS7000-OP-DWDM-1X8-100G-4451-SA-MPO" },
  "4030100": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030100 = GS7000-OP-BWDM-NCBC8D4-BC3941NC2059SAMPO" },
  "4030101": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030101 = GS7000-OP-BWDM-NCBC8D4-BC18-NC2059-SAMPO" },
  "4030106": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030106 = GS7000-OP-BWDM-NCBC8D4-BC18NC2027F-SAMPO" },
  "4030107": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030107 = GS7000-OP-BWDM-NCBC8D4-BC18NC2835F-SAMPO" },
  "4030108": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030108 = GS7000-OP-BWDM-NCBC8D4-BC18NC3643F-SAMPO" },
  "4030109": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4030109 = GS7000-OP-BWDM-NCBC8D4-BC18NC4551F-SAMPO" },
  "4033327": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4033327 = GS7000-OP-COUPLER-2X2-EVEN-SA" },
  "4033328": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4033328 = GS7000-OP-COUPLER-1X2-95-05-SA" },
  "4033329": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4033329 = GS7000-OP-OADM-200G-ITU18-SA" },
  "4035899": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4035899 = CYL-BWDM-DPON-13101490/15501610-900-SA" },
  "4037358": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4037358 = GS7000-OP-BWDM-1X2-2035-3651-SA" },
  "4037359": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4037359 = GS7000-OP-BWDM-1X2-2027-2835-SA" },
  "4037360": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4037360 = GS7000-OP-BWDM-1X2-3643-4451-SA" },
  "4039503": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 4039503 = P2-15TXM-12-EM-GHZ-SA-CHC-1WD" },
  "4039505": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 4039505 = P2-15TXM-12-EM-GHZ-SA-CHE-1WD" },
  "4039506": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 4039506 = P2-15TXM-12-EM-GHZ-SA-CHF-1WD" },
  "4039507": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 4039507 = P2-15TXM-12-EM-GHZ-SA-CHG-1WD" },
  "4039508": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 4039508 = P2-15TXM-12-EM-GHZ-SA-CHH-1WD" },
  "4040566": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 4040566 = P2-EDFA-MOD-4X16-SA" },
  "4042697": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 4042697 = P2-HD-EDFA-VGF-1X21-SA" },
  "4043499": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 4043499 = P2-HD-EDFA-VGF-1X17-SA" },
  "4043500": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 4043500 = P2-HD-EDFA-VGF-1X20-SA" },
  "4043574": { category: "video", kind: "passive", evidence: "EoL bulletin row: 4043574 = GS7000-OP-DWDM-SQAM-8CH-100G-SA-EXPDTP-C" },
  "737015": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 737015 = P2-EDFA-MOD-GF-1X17-FA" },
  "737016": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 737016 = P2-EDFA-MOD-GF-1X17-E2" },
  "737018": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 737018 = P2-EDFA-MOD-GF-1X20-FA" },
  "737019": { category: "video", kind: "amplifier", evidence: "EoL bulletin row: 737019 = P2-EDFA-MOD-GF-1X20-E2" },
  "737689": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737689 = P2-HD-15TXQ-Super-SA-ITU32-FS" },
  "737690": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737690 = P2-HD-15TXQ-Super-SA-ITU33-FS" },
  "737824": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737824 = P2-HD-15TXQ-IWDM-SA-CH1-FS" },
  "737825": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737825 = P2-HD-15TXQ-IWDM-SA-CH2-FS" },
  "737826": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737826 = P2-HD-15TXQ-IWDM-SA-CH3-FS" },
  "737827": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737827 = P2-HD-15TXQ-IWDM-SA-CH4-FS" },
  "737828": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737828 = P2-HD-15TXQ-IWDM-SA-CH5-FS" },
  "737829": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737829 = P2-HD-15TXQ-IWDM-SA-CH6-FS" },
  "737830": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737830 = P2-HD-15TXQ-IWDM-SA-CH7-FS" },
  "737831": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737831 = P2-HD-15TXQ-IWDM-SA-CH8-FS" },
  "737832": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737832 = P2-HD-15TXQ-IWDM-SA-CH9-FS" },
  "737833": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737833 = P2-HD-15TXQ-IWDM-SA-CH10-FS" },
  "737834": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737834 = P2-HD-15TXQ-IWDM-SA-CH11-FS" },
  "737835": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737835 = P2-HD-15TXQ-IWDM-SA-CH12-FS" },
  "737836": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737836 = P2-HD-15TXQ-IWDM-SA-CH13-FS" },
  "737837": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737837 = P2-HD-15TXQ-IWDM-SA-CH14-FS" },
  "737838": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737838 = P2-HD-15TXQ-IWDM-SA-CH15-FS" },
  "737839": { category: "video", kind: "transmitter", evidence: "EoL bulletin row: 737839 = P2-HD-15TXQ-IWDM-SA-CH16-FS" },
  "ASCT-EX2000": { category: "wireless", kind: "appliance", evidence: "EoL row 'Exciter' - the AeroScout exciter, as its sibling ASCT-EX3200 (ruling 12, 28 Sep)" },
  "FLMESH-HW-ACC-1": { category: "wireless", kind: "mechanical", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-1 = FM-BRKT" },
  "FLMESH-HW-ACC-10": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-10 = FM-LMR240-RPSMA2QMA-4FT" },
  "FLMESH-HW-ACC-17": { category: "wireless", kind: "accessory", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-17 = FM-EMP (axis cannot place it: Q9 (1)'s family default)" },
  "FLMESH-HW-ACC-19": { category: "wireless", kind: "power-injector", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-19 = FM-POE-LOW" },
  "FLMESH-HW-ACC-20": { category: "wireless", kind: "power-injector", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-20 = FM-POE-LOW-48" },
  "FLMESH-HW-ACC-21": { category: "wireless", kind: "power-injector", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-21 = FM-POE-STD" },
  "FLMESH-HW-ACC-23": { category: "wireless", kind: "accessory", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-23 = FM-QMA2SMA" },
  "FLMESH-HW-ACC-24": { category: "wireless", kind: "accessory", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-24 = FM-SPLITTER" },
  "FLMESH-HW-ACC-25": { category: "wireless", kind: "accessory", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-25 = FM-SURGE" },
  "FLMESH-HW-ACC-26": { category: "wireless", kind: "mechanical", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-26 = FM-WMOUNT" },
  "FLMESH-HW-ACC-31": { category: "wireless", kind: "mechanical", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-31 = FM-BRKT-SLIDING" },
  "FLMESH-HW-ACC-32": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-32 = FM-LMR240-N2N-6FT" },
  "FLMESH-HW-ACC-33": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-33 = FM-CABLE-M12PWR-2M" },
  "FLMESH-HW-ACC-34": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-34 = FM-CABLE-M12XM12-10M" },
  "FLMESH-HW-ACC-35": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-35 = FM-CABLE-M12XM12-1M" },
  "FLMESH-HW-ACC-36": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-36 = FM-CABLE-M12XM12-20M" },
  "FLMESH-HW-ACC-37": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-37 = FM-CABLE-M12XM12-2M" },
  "FLMESH-HW-ACC-38": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-38 = FM-CABLE-M12XM12-5M" },
  "FLMESH-HW-ACC-39": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-39 = FM-CABLE-M12XRJ45-10M" },
  "FLMESH-HW-ACC-40": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-40 = FM-CABLE-M12XRJ45-2M" },
  "FLMESH-HW-ACC-41": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-41 = FM-CABLE-M12XRJ45-5M" },
  "FLMESH-HW-ACC-42": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-42 = FM-LMR240-N2N-4FT" },
  "FLMESH-HW-ACC-43": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-43 = FM-LMR240-N2N-2FT" },
  "FLMESH-HW-ACC-44": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-44 = FM-LMR240-QMA2N-2FT" },
  "FLMESH-HW-ACC-46": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-46 = FM-LMR240-RPSMA2N-4FT" },
  "FLMESH-HW-ACC-47": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-47 = FM-LMR240-QMA2N-4FT" },
  "FLMESH-HW-ACC-48": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-48 = FM-LMR240-QMA2N-6FT" },
  "FLMESH-HW-ACC-49": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-49 = FM-LMR240-QMA2N-CU" },
  "FLMESH-HW-ACC-50": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-50 = FM-LMR240-QMA2QMA-2FT" },
  "FLMESH-HW-ACC-51": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-51 = FM-LMR240-QMA2QMA-4FT" },
  "FLMESH-HW-ACC-52": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-52 = FM-LMR240-QMA2QMA-6FT" },
  "FLMESH-HW-ACC-53": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-53 = FM-LMR240-QMA2QMA-CU" },
  "FLMESH-HW-ACC-54": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-54 = FM-LMR240-RPSMA2N-2FT" },
  "FLMESH-HW-ACC-55": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-55 = FM-LMR240-RPSMA2N-6FT" },
  "FLMESH-HW-ACC-56": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-56 = FM-LMR240-RPSMA2N-CU" },
  "FLMESH-HW-ACC-57": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-57 = FM-LMR240-RPSMA2QMA-2FT" },
  "FLMESH-HW-ACC-58": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-58 = FM-LMR240-RPSMA2QMA-6FT" },
  "FLMESH-HW-ACC-59": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-59 = FM-LMR240-RPSMA2RPSMA-2FT" },
  "FLMESH-HW-ACC-60": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-60 = FM-LMR240-RPSMA2RPSMA-4FT" },
  "FLMESH-HW-ACC-61": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-61 = FM-LMR240-RPSMA2RPSMA-6FT" },
  "FLMESH-HW-ACC-62": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-62 = FM-LMR240-RPSMA2RPSMA-CU" },
  "FLMESH-HW-ACC-63": { category: "wireless", kind: "cable", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-63 = FM-SHIELD-RPSMA-CABLE" },
  "FLMESH-HW-ACC-64": { category: "wireless", kind: "accessory", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-64 = FM-RPSMA2RPSMA" },
  "FLMESH-HW-ACC-65": { category: "wireless", kind: "accessory", evidence: "EoL bulletin 'Cisco Ultra-Reliable Wireless Backhaul' (19f6506d) row: FLMESH-HW-ACC-65 = FM-ATT-06-N" },
};
