// src/core/kindOverrides.ts — kinds for SKUs no axis can classify, one entry per SKU, ruled 28 Sep 2026
// (docs/decisions/2026-09-28-unknown-kind-106.md; reviewer ruling 12). Consulted by partKind ONLY where the category's axis
// answers unknown, so an axis that learns a SKU wins; tests/kindOverrides.test.ts fails on such a stale entry and on any
// kind the category does not declare. Parked, not here: 13 collab bundles (no bundle kind in collab), 4036797.1610 (ont
// is declared nowhere), CIT3-FI-M-6324 (a category move).
export type KindOverride = { category: string; kind: string };
export const KIND_OVERRIDES: Readonly<Record<string, KindOverride>> = {
  // collaboration-endpoints
  "CS-R-USB-UPG-BUN": { category: "collaboration-endpoints", kind: "accessory" },
  "WBP54G": { category: "collaboration-endpoints", kind: "accessory" },
  // interfaces-modules
  "AIM-DES/BP": { category: "interfaces-modules", kind: "module" },
  "SM-EC-3DES": { category: "interfaces-modules", kind: "module" },
  "SM-EC-3DES=": { category: "interfaces-modules", kind: "module" },
  "SM-EC-DES": { category: "interfaces-modules", kind: "module" },
  "WDM-SFP-2CH-CONV=": { category: "interfaces-modules", kind: "mux" },
  // optical-networking
  "15216-FLAMP36.6-SK": { category: "optical-networking", kind: "amplifier" },
  "15216-FLAMP44.5-SK": { category: "optical-networking", kind: "amplifier" },
  "15216-FLAMP52.5-SK": { category: "optical-networking", kind: "amplifier" },
  "15216-FLAMP60.6-SK": { category: "optical-networking", kind: "amplifier" },
  "EWDM-OA=": { category: "optical-networking", kind: "amplifier" },
  "15454-10GEXPE-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-10GEXPE-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454-80ROADM-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-80ROADM-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454-ARE-K9-SK": { category: "optical-networking", kind: "linecard" },
  "15454-ARE-L-K9-SK": { category: "optical-networking", kind: "linecard" },
  "15454-ML100T-12": { category: "optical-networking", kind: "linecard" },
  "15454-MSEXT24-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-MSEXT24-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454-OTU2XP-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-OTU2XP-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454-PPMESH8-LLP3": { category: "optical-networking", kind: "linecard" },
  "15454-PPMESH8-LLP5": { category: "optical-networking", kind: "linecard" },
  "15454E-ML100T-12": { category: "optical-networking", kind: "linecard" },
  "15454W-2X100G-SK": { category: "optical-networking", kind: "linecard" },
  "15454W-5X40GMXP-SK": { category: "optical-networking", kind: "linecard" },
  "15454W-5XOTU2XP-SK": { category: "optical-networking", kind: "linecard" },
  "NCS2K-10X200XP-SK": { category: "optical-networking", kind: "linecard" },
  "NCS2K-10XMXP-SK": { category: "optical-networking", kind: "linecard" },
  "NCS2K-400G-BUN-SK": { category: "optical-networking", kind: "linecard" },
  "NCS2K-400GXP-SK": { category: "optical-networking", kind: "linecard" },
  "15216-CMXDMX-SK": { category: "optical-networking", kind: "mux" },
  "15454-40SMR2-LLP3": { category: "optical-networking", kind: "roadm" },
  "15454-40SMR2-LLP5": { category: "optical-networking", kind: "roadm" },
  "15454-OPTAMPC-LLP3": { category: "optical-networking", kind: "roadm" },
  "15454-OPTAMPC-LLP5": { category: "optical-networking", kind: "roadm" },
  "15454-PP4SMR-LLP3": { category: "optical-networking", kind: "roadm" },
  "15454-PP4SMR-LLP5": { category: "optical-networking", kind: "roadm" },
  "NCS2006-FS-RDR-SK": { category: "optical-networking", kind: "roadm" },
  // servers-unified-computing
  "UCS-ASR5700-01": { category: "servers-unified-computing", kind: "bundle" },
  "UCSC-OCP-100G": { category: "servers-unified-computing", kind: "nic" },
  "UCSC-OCP-100G=": { category: "servers-unified-computing", kind: "nic" },
  "UCSC-OCP-1025G": { category: "servers-unified-computing", kind: "nic" },
  "UCSC-OCP-1025G=": { category: "servers-unified-computing", kind: "nic" },
  "XRV-PCIE-C40Q-03": { category: "servers-unified-computing", kind: "nic" },
  "SVC-E1120D-M3": { category: "servers-unified-computing", kind: "server" },
  "SVC-E160S-M3": { category: "servers-unified-computing", kind: "server" },
  "SVC-E180D-M3": { category: "servers-unified-computing", kind: "server" },
  // unified-communications
  "CIT-E160D-M2BUN/K9": { category: "unified-communications", kind: "server" },
  "CTI-ATP-VCS-CTRLK9": { category: "unified-communications", kind: "server" },
  "CTI-ATP-VCS-EXPWK9": { category: "unified-communications", kind: "server" },
  "CTI-ATP-VCS-SPAKK9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-BASE-K9=": { category: "unified-communications", kind: "server" },
  "CTI-VCS-BASE=": { category: "unified-communications", kind: "server" },
  "CTI-VCS-CNTRL-K9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-CONTRL-K9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-EXPRESS-K9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-EXPWY-K9": { category: "unified-communications", kind: "server" },
  "CTI-VCS-STPAK-K9": { category: "unified-communications", kind: "server" },
  "EXPWY-C-K9": { category: "unified-communications", kind: "server" },
  "EXPWY-E-K9": { category: "unified-communications", kind: "server" },
  "UNITYCN7-BUNDLE": { category: "unified-communications", kind: "server" },
  // video
  "4029111": { category: "video", kind: "node" },
  "750185": { category: "video", kind: "passive" },
  "9220F-DIFL": { category: "video", kind: "passive" },
  "BUNDLE1-3G60-DS384": { category: "video", kind: "system" },
  "DS38410X64UPGRADRF": { category: "video", kind: "system" },
  // wireless
  "AIR-330-EXP-BOX": { category: "wireless", kind: "accessory" },
  "AIR-330-EXP-BOX=": { category: "wireless", kind: "accessory" },
  "AIR-330-MB-1": { category: "wireless", kind: "accessory" },
  "AIR-330-MB-1=": { category: "wireless", kind: "accessory" },
  "AIR-330-MB-2": { category: "wireless", kind: "accessory" },
  "AIR-330-MB-2=": { category: "wireless", kind: "accessory" },
  "AIR-330-RB-1": { category: "wireless", kind: "accessory" },
  "AIR-330-RB-1=": { category: "wireless", kind: "accessory" },
  "AIR-VAP-CELLPCS": { category: "wireless", kind: "accessory" },
  "AIR-VAP-CELLPCS=": { category: "wireless", kind: "accessory" },
  "AIR-VCU-CELLPCS12": { category: "wireless", kind: "accessory" },
  "AIR-VCU-CELLPCS12=": { category: "wireless", kind: "accessory" },
  "AIR-BR1310G": { category: "wireless", kind: "ap" },
  "ASCT-EX3200": { category: "wireless", kind: "appliance" },
  "CWWLSE-1130-19-K9": { category: "wireless", kind: "appliance" },
  "ON100-M6-K9": { category: "wireless", kind: "appliance" },
  "2KI-FINAL-PKG-RU": { category: "wireless", kind: "mechanical" },
  "FINAL-PKG-RUSSIA": { category: "wireless", kind: "mechanical" },
  "AIR-BLE-BEACON-BLK": { category: "wireless", kind: "wireless-sensor" },
  "AIR-BLE-TAG-BULK": { category: "wireless", kind: "wireless-sensor" },
  "AIR-N-3006-DTA-K9": { category: "wireless", kind: "wireless-sensor" },
  "AIR-VBLE1-K9": { category: "wireless", kind: "wireless-sensor" },
};
