/**
 * Build the phase-1 freeze for a vendor: data/freeze/<vendor>.json + data/freeze/<vendor>-kinds.tsv.
 *
 *     npx tsx scripts/build-freeze.mts [--vendor cisco]
 *
 * Run it ONLY on the commit that also carries the rebuilt ledgers, censuses, traces and completeness report
 * (CLAUDE.md "The arrangement is frozen"). It reads the store once, read-only, for the live hardware parts and
 * their names; every other unit comes from code and committed files (src/core/arrangementFreeze.ts).
 *
 * Its own cross-check before writing: the snapshot's per-category part counts must equal the committed ledgers'
 * totals.parts. A freeze whose kind table and ledgers describe different populations would pin a contradiction.
 */
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { getPool, closePool } from "../src/store/index.js";
import { REPO_ROOT } from "../src/config.js";
import { LEDGER_KINDS } from "../src/core/cupLedger.js";
import { partKind } from "../src/core/partKind.js";
import { freezeUnits, freezeHash, kindLine, liveRoleOf, type KindRow } from "../src/core/arrangementFreeze.js";

const arg = (n: string): string | undefined => { const i = process.argv.indexOf(n); return i >= 0 ? process.argv[i + 1] : undefined; };

async function main(): Promise<void> {
  const vendor = arg("--vendor") ?? "cisco";
  const pool = getPool();
  const client = await pool.connect();
  let rows: { category: string; sku: string; name: string }[];
  try {
    await client.query("SET application_name = 'freeze/build'");
    await client.query("SET default_transaction_read_only = on");
    rows = (await client.query<{ category: string; sku: string; name: string }>(`
      SELECT c.slug AS category, p.sku, coalesce(p.name, '') AS name
        FROM parts p JOIN vendors v ON v.id = p.vendor_id JOIN categories c ON c.id = p.category_id
       WHERE v.slug = $1 AND p.retired_at IS NULL AND p.product_class = 'hardware' AND c.slug = ANY($2::text[])
       ORDER BY c.slug, p.sku`, [vendor, Object.keys(LEDGER_KINDS)])).rows;
  } finally {
    client.release();
    await closePool();
  }
  // kind-layer infra (13 Sep 2026): the fifth column is the derived deploy_role ("" when none), by liveRoleOf — the one
  // function tests/arrangementFreeze.test.ts re-derives every row with, so the builder and the test cannot disagree on
  // what "the role of this row" means.
  const kindRows: KindRow[] = rows.map((r) => {
    const row: KindRow = { ...r, kind: partKind(r.category, r.sku, r.name || undefined) ?? "(none)" };
    return { ...row, deploy_role: liveRoleOf(row) };
  });
  const units = freezeUnits(vendor, REPO_ROOT, kindRows);

  const bad = Object.entries(units.denominators)
    .filter(([c, d]) => (units.kinds.by_category[c] ?? 0) !== d.parts)
    .map(([c, d]) => `${c}: store ${units.kinds.by_category[c] ?? 0}, ledger ${d.parts}`);
  if (bad.length) throw new Error(`freeze REFUSED — the ledgers and the store describe different populations (rebuild the ledgers first): ${bad.join("; ")}`);

  const dir = path.join(REPO_ROOT, "data", "freeze");
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, `${vendor}-kinds.tsv`), kindRows.map(kindLine).join("\n") + "\n");
  let head = "unknown";
  try { head = execSync("git rev-parse --short HEAD", { cwd: REPO_ROOT }).toString().trim(); } catch { /* recorded as unknown */ }
  const out = {
    _about: "GENERATED by scripts/build-freeze.mts — the phase-1 arrangement pinned as one unit (profiles, dictionary projection, the kind mapping of every live hardware part, the deploy_role rule table and the role of every live part (layer 3), mapper rule file + frozen conflict table, registered derivations, spec-bearing document classes, ledger denominators). tests/arrangementFreeze.test.ts fails when code or committed artifacts no longer reproduce it. Rebuild only with a recorded decision in docs/decisions/, on the same commit as the ledgers, censuses, traces and completeness report.",
    built_on_parent_commit: head,
    generated_at: new Date().toISOString(),
    freeze_hash: freezeHash(units),
    units,
  };
  fs.writeFileSync(path.join(dir, `${vendor}.json`), JSON.stringify(out, null, 1) + "\n");
  console.log(`freeze ${vendor}: ${out.freeze_hash.slice(0, 16)} — ${units.kinds.parts} hardware parts, ${units.dictionary.keys} keys, ${units.mapper.conflicts} frozen conflicts, ${units.derived_fill_paths.keys.length} derivations, ${Object.keys(units.profiles).length} profiles, ${units.roles.rules} role rules, ${units.roles.parts_with_axis} parts on a role axis (${units.roles.unresolved} unresolved)`);
}

main().catch((e) => { console.error(e instanceof Error ? e.message : e); process.exit(1); });
